import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/action-research.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/action-research.json';
import wordsko from '../i18n/resources/ko/pages/action-research.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import './ActionResearch.css';

/** Action-Research — one component for every language, generated by
 *  scripts/convert-pages.mjs from Action-Research.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/action-research.json; the
 *  line-heights that differ by language are custom properties in ActionResearch.css.
 *  Edit the legacy pages, not this file. */
export default function ActionResearch() {
  const t = usePageWords("action-research", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Action-Research.EN.dc.html" className="page-action-research" footer={{ loop: "0.148", cta: "#1E648C" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (key color · deep blue) */}
        <section style={{ background: "var(--color-deepblue)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "26px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "rgba(250,244,226,0.82)", marginBottom: "24px" }}>
              {t("000_div")}
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(42px, 6vw, 80px)", lineHeight: "var(--in-action-research-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "18ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
            <div style={{ display: "inline-flex", alignItems: "center", gap: "10px", marginTop: "26px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", background: "rgba(250,244,226,0.16)", border: "1px solid rgba(250,244,226,0.4)", borderRadius: "999px", padding: "9px 16px" }}>
              <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-amber)" }} />
              {t("003_div")}
            </div>
          </div>
        </section>
        {/* HOW IT WORKS */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "26px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "24px" }}>
            {t("004_div")}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "22px" }}>
            <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "12px" }}>
                {t("005_div")}
              </div>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("006_p")}
              </p>
            </div>
            <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1A263A", marginBottom: "12px" }}>
                {t("007_div")}
              </div>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("008_p")}
              </p>
            </div>
            <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "12px" }}>
                {t("009_div")}
              </div>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("010_p")}
              </p>
            </div>
          </div>
        </section>
        {/* PUBLICATIONS */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "26px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "24px" }}>
            {t("011_div")}
          </div>
          <div style={{ display: "flex", flexDirection: "column", maxWidth: "1000px" }}>
            <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", gap: "24px", padding: "22px 0", borderTop: "1px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-deepblue)" }}>
                2024
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                {t("012_div")}
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", gap: "24px", padding: "22px 0", borderTop: "1px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-deepblue)" }}>
                2022
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                {t("013_div")}
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", gap: "24px", padding: "22px 0", borderTop: "1px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-deepblue)" }}>
                2021
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                {t("014_div")}
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", gap: "24px", padding: "22px 0", borderTop: "1px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-deepblue)" }}>
                2020
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                {t("015_div")}
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", gap: "24px", padding: "22px 0", borderTop: "1px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-deepblue)" }}>
                2018
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                {t("016_div")}
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", gap: "24px", padding: "22px 0", borderTop: "1px solid rgba(46,59,64,0.16)", borderBottom: "1px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-deepblue)" }}>
                2015
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                {t("017_div")}
              </div>
            </div>
          </div>
          <p style={{ fontFamily: "var(--font-sans)", fontWeight: "600", fontSize: "13px", letterSpacing: "0.04em", color: "rgba(46,59,64,0.55)", margin: "20px 0 0" }}>
            {t("018_p")}
          </p>
        </section>
        {/* CTA (teal · constant) */}
        <section style={{ background: "var(--color-deepblue)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("019_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("020_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/mewe", locale)} style={{ textDecoration: "none", color: "var(--color-teal)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("021_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("022_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
