import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/are-you-in.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/are-you-in.json';
import wordsko from '../i18n/resources/ko/pages/are-you-in.json';
import SiteLayout from '../components/SiteLayout';
import SupabaseForm from '../components/SupabaseForm';
import './AreyouIN.css';

/** Are-you-IN — one component for every language, generated by
 *  scripts/convert-pages.mjs from Are-you-IN.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/are-you-in.json; the
 *  line-heights that differ by language are custom properties in AreyouIN.css.
 *  Edit the legacy pages, not this file. */
export default function AreyouIN() {
  const t = usePageWords("are-you-in", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });

  return (
    <SiteLayout page="Are-you-IN.EN.dc.html" className="page-areyou-in" footer={{ loop: "0.920", cta: "#1E8A86" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO ===================== */}
        <section style={{ background: "#1E8A86", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "72px 28px 76px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.82)", marginBottom: "22px" }}>
              {t("000_div")}
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(46px, 6.6vw, 96px)", lineHeight: "var(--in-are-you-in-0)", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.3vw, 27px)", lineHeight: "1.42", maxWidth: "680px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* ===================== VIDEO + FORM (two columns) ===================== */}
        <section id="inquiry" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "52px", alignItems: "flex-start" }}>
            <div style={{ flex: "1 1 460px", minWidth: "320px" }}>
              <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 40px)", lineHeight: "var(--in-are-you-in-1)", margin: "0 0 8px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                {t("003_h2")}
              </h2>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", margin: "0 0 28px", color: "rgba(46,59,64,0.78)", maxWidth: "520px" }}>
                {t("004_p")}
              </p>
              <SupabaseForm table="submissions" thanks="Thank you — your message is with us. We read every one, and we'll be in touch soon." id="cf-form" style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                <div aria-hidden="true" style={{ position: "absolute", left: "-9999px", width: "1px", height: "1px", overflow: "hidden" }}>
                  <label>
                    {t("005_label")}
                    <input type="text" name="_hp" tabIndex={-1} autoComplete="off" />
                  </label>
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "16px" }}>
                  <div style={{ flex: "1 1 200px", minWidth: "180px" }}>
                    <label htmlFor="cf-name" style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)", marginBottom: "8px" }}>
                      {t("006_label")}
                    </label>
                    <input className="in-field" type="text" name="name" id="cf-name" placeholder="Your name" required={true} />
                  </div>
                  <div style={{ flex: "1 1 200px", minWidth: "180px" }}>
                    <label htmlFor="cf-email" style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)", marginBottom: "8px" }}>
                      {t("007_label")}
                    </label>
                    <input className="in-field" type="email" name="email" id="cf-email" placeholder="you@example.com" required={true} />
                  </div>
                </div>
                <div>
                  <label htmlFor="cf-brings" style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)", marginBottom: "8px" }}>
                    {t("008_label")}
                  </label>
                  <select className="in-field" id="cf-brings" name="brings">
                    <option>
                      {t("009_option")}
                    </option>
                    <option>
                      {t("010_option")}
                    </option>
                    <option>
                      {t("011_option")}
                    </option>
                    <option>
                      {t("012_option")}
                    </option>
                    <option>
                      {t("013_option")}
                    </option>
                    <option>
                      {t("014_option")}
                    </option>
                  </select>
                </div>
                <div id="cf-msg-wrap">
                  <label htmlFor="cf-message" style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)", marginBottom: "8px" }}>
                    {t("015_label")}
                  </label>
                  <textarea className="in-field" name="message" id="cf-message" rows={5} placeholder="What are you hoping to explore?" style={{ resize: "vertical" }} />
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: "18px", flexWrap: "wrap", marginTop: "4px" }}>
                  <button type="submit" style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.02em", color: "#FAF4E2", background: "#2E3B40", border: "none", borderRadius: "999px", padding: "15px 34px", cursor: "pointer" }}>
                    {t("016_button")}
                  </button>
                  <span data-in-status="1" style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", lineHeight: "1.4", color: "rgba(46,59,64,0.55)" }}>
                    {t("017_span")}
                  </span>
                </div>
              </SupabaseForm>
            </div>
            <div style={{ flex: "1 1 480px", minWidth: "320px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "18px" }}>
                {t("018_div")}
              </div>
              <div style={{ position: "relative", width: "100%", aspectRatio: "16 / 9", background: "#2E3B40" }}>
                <iframe src="https://www.youtube-nocookie.com/embed/RRV2gOjVx3U?rel=0" title={t("019_title")} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" style={{ position: "absolute", inset: "0", width: "100%", height: "100%", border: "0" }} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen={true} />
              </div>
            </div>
          </div>
        </section>
        {/* ===================== THREE CARDS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "22px" }}>
            <div style={{ background: "#BDDAE7", color: "#2E3B40", display: "flex", flexDirection: "column" }}>
              <img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80" alt={t("020_alt")} style={{ display: "block", width: "100%", aspectRatio: "16 / 9", objectFit: "cover" }} />
              <div style={{ display: "flex", gap: "16px", padding: "26px 28px 28px", flex: "1", backgroundColor: "#F0D23C" }}>
                <div style={{ flex: "0 0 auto", display: "flex", flexDirection: "column", alignItems: "center", gap: "10px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#2E3B40" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)" }}>
                    {t("021_span")}
                  </span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", flex: "1" }}>
                  <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", lineHeight: "var(--in-are-you-in-2)", margin: "0 0 10px" }}>
                    {t("022_h3")}
                  </h3>
                  <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.2", margin: "0 0 22px", color: "rgba(46,59,64,0.8)" }}>
                    {t("023_p")}
                  </p>
                  <a href="#cf-form" data-scroll-form="1" style={{ marginTop: "auto", alignSelf: "flex-start", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "12px 24px" }} className="in-plain">
                    {t("024_a")}
                  </a>
                </div>
              </div>
            </div>
            <div style={{ background: "#46325A", color: "#FAF4E2", display: "flex", flexDirection: "column" }}>
              <img src="https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=900&q=80" alt={t("025_alt")} style={{ display: "block", width: "100%", aspectRatio: "16 / 9", objectFit: "cover" }} />
              <div style={{ display: "flex", gap: "16px", padding: "26px 28px 28px", flex: "1" }}>
                <div style={{ flex: "0 0 auto", display: "flex", flexDirection: "column", alignItems: "center", gap: "10px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#FAF4E2" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)" }}>
                    {t("026_span")}
                  </span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", flex: "1" }}>
                  <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", lineHeight: "var(--in-are-you-in-3)", margin: "0 0 10px" }}>
                    {t("027_h3")}
                  </h3>
                  <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.2", margin: "0 0 22px", color: "rgba(250,244,226,0.9)" }}>
                    {t("028_p")}
                  </p>
                  <a href="#cf-form" data-scroll-form="1" data-prefill="Just keep me posted about events" style={{ marginTop: "auto", alignSelf: "flex-start", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "#46325A", background: "#FAF4E2", borderRadius: "999px", padding: "12px 24px" }} className="in-plain">
                    {t("029_a")}
                  </a>
                </div>
              </div>
            </div>
            {/* Card 3: NEWS — structured for a future Instagram auto-feed; static entry until connected */}
            <div data-ig-feed="innoco.co" style={{ background: "#F3EAD0", color: "#2E3B40", display: "flex", flexDirection: "column" }}>
              <img src="https://images.unsplash.com/photo-1522543558187-768b6df7c25c?auto=format&fit=crop&w=900&q=80" alt={t("030_alt")} style={{ display: "block", width: "100%", aspectRatio: "16 / 9", objectFit: "cover" }} />
              <div style={{ display: "flex", gap: "16px", padding: "26px 28px 28px", flex: "1", backgroundColor: "#D21E28" }}>
                <div style={{ flex: "0 0 auto", display: "flex", flexDirection: "column", alignItems: "center", gap: "10px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#2E3B40" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)" }}>
                    {t("031_span")}
                  </span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", flex: "1" }}>
                  <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", lineHeight: "var(--in-are-you-in-4)", margin: "0 0 10px" }}>
                    {t("032_h3")}
                  </h3>
                  <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.2", margin: "0 0 22px", color: "rgba(46,59,64,0.8)" }}>
                    {t("033_p")}
                  </p>
                  <a href="https://instagram.com/innoco.co" target="_blank" rel="noopener" style={{ marginTop: "auto", alignSelf: "flex-start", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "12px 24px" }} className="in-plain">
                    {t("034_a")}
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== TRIAD BOX (teal) ===================== */}
        <section style={{ background: "#1E8A86", color: "#FAF4E2", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(30px, 4vw, 52px)", lineHeight: "var(--in-are-you-in-5)", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("035_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", margin: "0", color: "rgba(250,244,226,0.9)" }}>
              {t("036_p")}
            </p>
          </div>
        </section>
        {/* ===================== FOOTER (no CTA on this page → ribbon transparent, loop only) ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
