import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/bridgebuilder.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/bridgebuilder.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import './BridgeBuilderEN.css';

/** BridgeBuilder.EN.dc.html — generated by scripts/convert-pages.mjs. Serves /bridge-builder and
 *  /zh-tw/bridge-builder: this page's KO twin did not collapse into it, but
 *  zh-TW has no edition in site/ and reads this one. Its words are in
 *  src/i18n/resources/<locale>/pages/bridgebuilder.json.
 *  Edit the legacy page, or take this file over by hand and remove it from
 *  the converter's input. */
export default function BridgeBuilderEN() {
  const t = usePageWords("bridgebuilder", { "en": wordsen, "zh-TW": wordszhTW });
  const locale = useLocale();

  return (
    <SiteLayout page="BridgeBuilder.EN.dc.html" className="page-bridge-builder-en" footer={{ loop: "0.312", cta: "#F05A28" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO */}
        <section style={{ background: "var(--color-orange)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "22px 28px 0" }}>
            <Link to={localize("/pathway", locale)} style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "rgba(250,244,226,0.78)", textDecoration: "none" }} className="in-plain">
              {t("000_a")}
            </Link>
          </div>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("001_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(48px, 6.4vw, 96px)", lineHeight: "0.96", letterSpacing: "-0.025em", margin: "0 0 22px", maxWidth: "18ch", textWrap: "balance" }}>
              {t("002_h1")}
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.3", maxWidth: "720px", margin: "0 0 30px", color: "rgba(250,244,226,0.94)" }}>
              <i>
                {t("003_i")}
              </i>
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-orange)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("004_a")}
              </Link>
              <Link to={localize("/pathway", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("005_a")}
              </Link>
            </div>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.8)", marginTop: "30px" }}>
              {t("006_div")}
            </div>
          </div>
        </section>
        {/* WHAT IS A BRIDGEBUILDER */}
        <section style={{ maxWidth: "1320px", margin: "84px auto 0", padding: "0 28px" }}>
          <div style={{ maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "22px" }}>
              {t("007_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("008_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("009_p")}
            </p>
          </div>
        </section>
        {/* WHAT WILL YOU DO */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ maxWidth: "940px", marginBottom: "34px" }}>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "20px" }}>
                {t("010_div")}
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 20px", textWrap: "balance", color: "var(--color-ink)" }}>
                {t("011_h2")}
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
                {t("012_p")}
              </p>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
              <Link to={localize("/", locale)} target="_blank" rel="noopener" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
                <div style={{ width: "92px", height: "92px", borderRadius: "50%", background: "var(--color-orange)", display: "flex", alignItems: "center", justifyContent: "center", flex: "0 0 auto" }}>
                  <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "14px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-paper)" }}>
                    {t("013_span")}
                  </span>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                    {t("014_div")}
                  </div>
                  <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.02", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                    {t("015_h3")}
                  </h3>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                    {t("016_p")}
                  </p>
                </div>
                <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                  {t("017_span")}
                  <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                    {t("018_span")}
                  </span>
                </span>
              </Link>
              <Link to={localize("/", locale)} target="_blank" rel="noopener" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
                <div style={{ width: "92px", height: "92px", borderRadius: "50%", background: "var(--color-orange)", display: "flex", alignItems: "center", justifyContent: "center", flex: "0 0 auto" }}>
                  <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "14px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-paper)" }}>
                    {t("019_span")}
                  </span>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                    {t("020_div")}
                  </div>
                  <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.02", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                    {t("021_h3")}
                  </h3>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                    {t("022_p")}
                  </p>
                </div>
                <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                  {t("023_span")}
                  <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                    {t("024_span")}
                  </span>
                </span>
              </Link>
              <Link to={localize("/", locale)} target="_blank" rel="noopener" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
                <div style={{ width: "92px", height: "92px", borderRadius: "50%", background: "var(--color-orange)", display: "flex", alignItems: "center", justifyContent: "center", flex: "0 0 auto" }}>
                  <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "14px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-paper)" }}>
                    {t("025_span")}
                  </span>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                    {t("026_div")}
                  </div>
                  <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.02", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                    {t("027_h3")}
                  </h3>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                    {t("028_p")}
                  </p>
                </div>
                <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                  {t("029_span")}
                  <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                    {t("030_span")}
                  </span>
                </span>
              </Link>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "34px 0 0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("031_p")}
            </p>
          </div>
        </section>
        {/* POP-UP LAB */}
        <section style={{ maxWidth: "1320px", margin: "46px auto 0", padding: "0 28px" }}>
          <div style={{ background: "var(--color-paper-dim)", padding: "56px 52px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "40px", alignItems: "center" }}>
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "16px" }}>
                {t("032_div")}
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.4vw, 46px)", lineHeight: "1.02", letterSpacing: "-0.01em", margin: "0", textWrap: "balance", color: "var(--color-ink)" }}>
                {t("033_h2")}
              </h2>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                {t("034_p")}
              </p>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                {t("035_p")}
                <b>
                  {t("036_b")}
                </b>
              </p>
            </div>
          </div>
        </section>
        {/* WHO CAN BE */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "20px" }}>
              {t("037_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 26px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("038_h2")}
            </h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "14px", marginBottom: "28px" }}>
              <div style={{ display: "flex", gap: "16px", alignItems: "baseline" }}>
                <span style={{ flex: "0 0 auto", width: "10px", height: "10px", borderRadius: "50%", background: "var(--color-orange)" }} />
                <p style={{ margin: "0", fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.5", color: "rgba(46,59,64,0.85)" }}>
                  {t("039_p")}
                </p>
              </div>
              <div style={{ display: "flex", gap: "16px", alignItems: "baseline" }}>
                <span style={{ flex: "0 0 auto", width: "10px", height: "10px", borderRadius: "50%", background: "var(--color-orange)" }} />
                <p style={{ margin: "0", fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.5", color: "rgba(46,59,64,0.85)" }}>
                  {t("040_p")}
                </p>
              </div>
              <div style={{ display: "flex", gap: "16px", alignItems: "baseline" }}>
                <span style={{ flex: "0 0 auto", width: "10px", height: "10px", borderRadius: "50%", background: "var(--color-orange)" }} />
                <p style={{ margin: "0", fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.5", color: "rgba(46,59,64,0.85)" }}>
                  {t("041_p")}
                </p>
              </div>
              <div style={{ display: "flex", gap: "16px", alignItems: "baseline" }}>
                <span style={{ flex: "0 0 auto", width: "10px", height: "10px", borderRadius: "50%", background: "var(--color-orange)" }} />
                <p style={{ margin: "0", fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.5", color: "rgba(46,59,64,0.85)" }}>
                  {t("042_p")}
                </p>
              </div>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(22px, 2.4vw, 28px)", lineHeight: "1.32", margin: "0", maxWidth: "760px", color: "var(--color-ink)", textWrap: "pretty" }}>
              {t("043_p")}
            </p>
          </div>
        </section>
        {/* WHAT YOU WILL BE PART OF */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "20px" }}>
              {t("044_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("045_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 22px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("046_p")}
            </p>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 26px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("047_p")}
            </p>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 26px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("048_p")}
              <Link to={localize("/project/asia-exchange", locale)}>
                {t("049_a")}
              </Link>
              {t("050_p")}
            </p>
            <Link to={localize("/project/asia-exchange", locale)} style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", letterSpacing: "0.04em", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "14px 28px" }} className="in-plain">
              {t("051_a")}
            </Link>
          </div>
        </section>
        {/* CTA BAND */}
        <section style={{ background: "var(--color-orange)", color: "var(--color-paper)", marginTop: "84px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("052_p")}
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("053_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-orange)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2" }} className="in-plain">
                {t("054_a")}
              </Link>
              <Link to={localize("/pathway", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2" }} className="in-plain">
                {t("055_a")}
              </Link>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.5", margin: "30px 0 0", color: "rgba(250,244,226,0.86)" }}>
              {t("056_p")}
            </p>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
