import { Fragment } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import useLogic from '../logic/CollectivesEN';
import './CollectivesEN.css';

/** Collectives.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function CollectivesEN() {
  const { closedToNew, openToNew, roster } = useLogic();

  return (
    <SiteLayout lang="EN" page="Collectives.EN.dc.html" className="page-collectives-en" footer={{ loop: "0.103", cta: "#46325A" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO (plum band) = the CONCEPT ===================== */}
        <section style={{ background: "#46325A", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#FAF4E2", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#FAF4E2" }}>
                Collectives
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "18ch", textWrap: "balance" }}>
              A Collective doesn't join. A Collective begins.
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(21px, 2.6vw, 30px)", lineHeight: "1.35", maxWidth: "800px", margin: "0", color: "rgba(250,244,226,0.92)" }}>
              Every protagonist practices MEWE. A few carry it into their own community, in their own way — without being asked. Those are IN-Collectives.
            </p>
          </div>
        </section>
        {/* ===================== SECTION = the PEOPLE ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#43326D", marginBottom: "20px" }}>
            IN-Collectives
          </div>
          <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 4vw, 52px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 24px", textWrap: "balance" }}>
            The ones who started within.
          </h2>
          <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "20px", lineHeight: "1.55", maxWidth: "800px", margin: "0 0 30px", color: "rgba(46,59,64,0.82)" }}>
            IN grows with independent partners and collaborators, called IN-Collectives. We are the team behind the workshops — a close-knit group of like-minded people who want to bring out the best in themselves and society. Working in their own communities across diverse fields — teaching, hosting workshops, developing local initiatives — each brings MEWE into their own context. Each IN-Collective contributes learning back into the wider studio network, allowing the work to grow through shared experience. We are all about spreading joy, sparking creativity, and helping one another make the world a better place.
          </p>
        </section>
        {/* ===================== IN-COLLECTIVES ROSTER ===================== */}
        <section id="facilitators" style={{ maxWidth: "1320px", margin: "56px auto 0", padding: "0 28px 24px" }}>
          <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#46325A", marginBottom: "40px" }}>
            IN-Collective Network
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "26px" }}>
            {(roster ?? []).map((person, personIndex) => (
              <Fragment key={personIndex}>
                <article style={{ background: "#FAF4E2" }}>
                  <img className="tm-photo" src={person.photo} alt={person.name} />
                  <div style={{ padding: "16px 2px 0" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.03em", color: "rgba(38,42,56,0.45)", marginBottom: "4px" }}>
                      #{person.num}
                    </div>
                    <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "23px", lineHeight: "1.1", marginBottom: "6px" }}>
                      {person.name}
                    </div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.03em", color: "#3C8246", marginBottom: "8px" }}>
                      {person.role}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "16px", lineHeight: "1.45", margin: "0 0 12px", color: "rgba(38,42,56,0.75)" }}>
                      {person.oneLiner}
                    </p>
                    <button className="tm-more" onClick={person.toggle}>
                      {person.toggleLabel}
                    </button>
                    {person.expanded ? (
                      <>
                      <p style={{ fontFamily: "'Newsreader', serif", fontSize: "16px", lineHeight: "1.5", margin: "14px 0 0", color: "rgba(38,42,56,0.85)" }}>
                        {person.fullBio}
                      </p>
                      </>
                    ) : null}
                  </div>
                </article>
              </Fragment>
            ))}
          </div>
        </section>
        {/* ===================== FOUNDER'S NOTE ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.14)", paddingTop: "44px" }}>
            <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontWeight: "400", fontSize: "20px", lineHeight: "1.5", width: "800px", maxWidth: "100%", margin: "0", color: "#43326D" }}>
              Roll up your sleeves. Let's Co-Design what comes next. Every generation carries curiosity, creativity, and courage. Welcome to IN, where every story adds its light.
            </p>
            <div style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontWeight: "400", fontSize: "20px", lineHeight: "1.5", marginTop: "20px", color: "#43326D" }}>
              — Yunsun Chung, Founder
            </div>
          </div>
        </section>
        {/* ===================== JOIN CTA (green) ===================== */}
        <section id="join" style={{ background: "#46325A", color: "#FAF4E2", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.78)", marginBottom: "18px" }}>
              The door is open
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 60px)", lineHeight: "1.04", margin: "0 auto 18px", maxWidth: "18ch", letterSpacing: "-0.01em", textWrap: "balance" }}>
              Carry MEWE into your own community.
            </h2>
            {openToNew ? (
              <>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", maxWidth: "620px", margin: "0 auto 32px", color: "rgba(250,244,226,0.9)" }}>
                We're welcoming new facilitators and BridgeBuilders. If these questions resonate with your work, we'd be glad to begin a conversation.
              </p>
              </>
            ) : null}
            {closedToNew ? (
              <>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", maxWidth: "620px", margin: "0 auto 32px", color: "rgba(250,244,226,0.9)" }}>
                Facilitator intake is currently paused. Leave your details and we'll reach out when the next cohort opens.
              </p>
              </>
            ) : null}
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/connect" style={{ textDecoration: "none", color: "#46325A", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                Facilitator interest form
              </Link>
              <Link to="/connect" style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                BridgeBuilder interest form
              </Link>
            </div>
          </div>
        </section>
        {/* ===================== FOOTER ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
