import { Fragment } from 'react';
import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/collectives.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/collectives.json';
import wordsko from '../i18n/resources/ko/pages/collectives.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import useLogic from '../logic/Collectives';
import './Collectives.css';

/** Collectives — one component for every language, generated by
 *  scripts/convert-pages.mjs from Collectives.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/collectives.json; the
 *  line-heights that differ by language are custom properties in Collectives.css.
 *  Edit the legacy pages, not this file. */
export default function Collectives() {
  const t = usePageWords("collectives", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();
  const { closedToNew, openToNew, roster } = useLogic();

  return (
    <SiteLayout page="Collectives.EN.dc.html" className="page-collectives" footer={{ loop: "0.103", cta: "#46325A" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO (plum band) = the CONCEPT ===================== */}
        <section style={{ background: "var(--color-plum)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "var(--in-collectives-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "18ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(21px, 2.6vw, 30px)", lineHeight: "1.35", maxWidth: "800px", margin: "0", color: "rgba(250,244,226,0.92)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* ===================== SECTION = the PEOPLE ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#43326D", marginBottom: "20px" }}>
            {t("003_div")}
          </div>
          <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 4vw, 52px)", lineHeight: "var(--in-collectives-1)", letterSpacing: "-0.01em", margin: "0 0 24px", textWrap: "balance" }}>
            {t("004_h2")}
          </h2>
          <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "20px", lineHeight: "1.55", maxWidth: "800px", margin: "0 0 30px", color: "rgba(46,59,64,0.82)" }}>
            {t("005_p")}
          </p>
        </section>
        {/* ===================== IN-COLLECTIVES ROSTER ===================== */}
        <section id="facilitators" style={{ maxWidth: "1320px", margin: "56px auto 0", padding: "0 28px 24px" }}>
          <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-plum)", marginBottom: "40px" }}>
            {t("006_div")}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "26px" }}>
            {(roster ?? []).map((person, personIndex) => (
              <Fragment key={personIndex}>
                <article style={{ background: "var(--color-paper)" }}>
                  <img className="tm-photo" src={person.photo} alt={person.name} />
                  <div style={{ padding: "16px 2px 0" }}>
                    <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.03em", color: "rgba(38,42,56,0.45)", marginBottom: "4px" }}>
                      #{person.num}
                    </div>
                    <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "23px", lineHeight: "1.1", marginBottom: "6px" }}>
                      {person.name}
                    </div>
                    <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.03em", color: "var(--color-green)", marginBottom: "8px" }}>
                      {person.role}
                    </div>
                    <p style={{ fontFamily: "var(--font-serif)", fontSize: "16px", lineHeight: "1.45", margin: "0 0 12px", color: "rgba(38,42,56,0.75)" }}>
                      {person.oneLiner}
                    </p>
                    <button className="tm-more" onClick={person.toggle}>
                      {person.toggleLabel}
                    </button>
                    {person.expanded ? (
                      <>
                      <p style={{ fontFamily: "var(--font-serif)", fontSize: "16px", lineHeight: "1.5", margin: "14px 0 0", color: "rgba(38,42,56,0.85)" }}>
                        {person.fullBio}
                      </p>
                      </>
                    ) : null}
                  </div>
                </article>
              </Fragment>
            ))}
          </div>
        </section>
        {/* ===================== FOUNDER'S NOTE ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.14)", paddingTop: "44px" }}>
            <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-collectives-2)", fontWeight: "400", fontSize: "var(--in-collectives-3)", lineHeight: "var(--in-collectives-4)", width: "800px", maxWidth: "100%", margin: "0", color: "#43326D" }}>
              {t("007_p")}
            </p>
            <div style={{ fontFamily: "var(--in-collectives-5)", fontStyle: "italic", fontWeight: "var(--in-collectives-6)", fontSize: "var(--in-collectives-7)", lineHeight: "1.5", marginTop: "20px", color: "var(--in-collectives-8)" }}>
              {t("008_div")}
            </div>
          </div>
        </section>
        {/* ===================== JOIN CTA (green) ===================== */}
        <section id="join" style={{ background: "var(--color-plum)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.78)", marginBottom: "18px" }}>
              {t("009_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 60px)", lineHeight: "var(--in-collectives-9)", margin: "0 auto 18px", maxWidth: "18ch", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("010_h2")}
            </h2>
            {openToNew ? (
              <>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.45", maxWidth: "620px", margin: "0 auto 32px", color: "rgba(250,244,226,0.9)" }}>
                {t("011_p")}
              </p>
              </>
            ) : null}
            {closedToNew ? (
              <>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.45", maxWidth: "620px", margin: "0 auto 32px", color: "rgba(250,244,226,0.9)" }}>
                {t("012_p")}
              </p>
              </>
            ) : null}
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-plum)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("013_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("014_a")}
              </Link>
            </div>
          </div>
        </section>
        {/* ===================== FOOTER ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
