import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/community-index.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/community-index.json';
import wordsko from '../i18n/resources/ko/pages/community-index.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import CommunityIndexList from '../components/CommunityIndexList';
import { localize, useLocale } from '../lib/lang';
import './CommunityIndex.css';

/** Community-Index — one component for every language, generated by
 *  scripts/convert-pages.mjs from Community-Index.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/community-index.json; the
 *  line-heights that differ by language are custom properties in CommunityIndex.css.
 *  Edit the legacy pages, not this file. */
export default function CommunityIndex() {
  const t = usePageWords("community-index", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Community-Index.EN.dc.html" className="page-community-index" footer={{ loop: "0.74", cta: "#D21E28" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        <section style={{ background: "var(--color-red)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <Link to={localize("/community", locale)} style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(250,244,226,0.85)", textDecoration: "none", display: "inline-block", marginBottom: "28px" }} className="in-plain">
              {t("000_a")}
            </Link>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("001_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              {t("002_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 26px)", lineHeight: "1.3", maxWidth: "700px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("003_p")}
            </p>
          </div>
        </section>
        <section style={{ maxWidth: "1000px", margin: "80px auto 0", padding: "0 28px 20px" }}>
          <CommunityIndexList />
        </section>
        <section style={{ background: "var(--color-red)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("004_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("005_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-red)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("006_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
