import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/community.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/community.json';
import wordsko from '../i18n/resources/ko/pages/community.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import NewsGrid from '../components/cards/NewsGrid';
import CommunityGrid from '../components/cards/CommunityGrid';
import { localize, useLocale } from '../lib/lang';
import './Community.css';

/** Community — one component for every language, generated by
 *  scripts/convert-pages.mjs from Community.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/community.json; the
 *  line-heights that differ by language are custom properties in Community.css.
 *  Edit the legacy pages, not this file. */
export default function Community() {
  const t = usePageWords("community", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Community.EN.dc.html" className="page-community" footer={{ loop: "0.716", cta: "#D21E28" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO */}
        <section style={{ background: "var(--color-red)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "var(--in-community-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "15ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "720px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* SECTION 1 · COMMUNITIES */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px 12px" }}>
          <div style={{ marginBottom: "28px" }}>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.4vw, 44px)", lineHeight: "var(--in-community-1)", margin: "0 0 14px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("003_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", maxWidth: "60ch", margin: "0", color: "rgba(46,59,64,0.8)" }}>
              {t("004_p")}
            </p>
          </div>
          <CommunityGrid />
          <div style={{ display: "flex", justifyContent: "center", marginTop: "32px" }}>
            <Link to={localize("/community/all", locale)} style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--color-red)", textDecoration: "none", border: "1.5px solid var(--color-red)", borderRadius: "999px", padding: "13px 28px" }} className="in-plain">
              {t("005_a")}
            </Link>
          </div>
        </section>
        {/* NEWS */}
        <section id="news" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px 12px" }}>
          <div style={{ marginBottom: "28px" }}>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.4vw, 44px)", lineHeight: "var(--in-community-2)", margin: "0 0 14px", letterSpacing: "-0.01em" }}>
              {t("006_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", maxWidth: "60ch", margin: "0", color: "rgba(46,59,64,0.8)" }}>
              {t("007_p")}
            </p>
          </div>
          <NewsGrid feed="community" />
          <div style={{ display: "flex", justifyContent: "center", marginTop: "32px" }}>
            <Link to={localize("/story", locale)} style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--color-red)", textDecoration: "none", border: "1.5px solid var(--color-red)", borderRadius: "999px", padding: "13px 28px" }} className="in-plain">
              {t("008_a")}
            </Link>
          </div>
        </section>
        {/* CONSTELLATION */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px 20px" }}>
          <div style={{ marginBottom: "20px" }}>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "var(--in-community-3)", margin: "0", letterSpacing: "-0.01em" }}>
              {t("009_h2")}
            </h2>
          </div>
          <Link to={localize("/constellation", locale)} className="cm-card in-plain" style={{ display: "block", backgroundColor: "var(--color-yellow)", color: "var(--color-ink)", padding: "40px 40px 42px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "32px", alignItems: "flex-end", justifyContent: "space-between" }}>
              <div style={{ flex: "1 1 460px", minWidth: "300px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "14px" }}>
                  {t("010_div")}
                </div>
                <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 40px)", lineHeight: "var(--in-community-4)", margin: "0 0 14px" }}>
                  {t("011_h3")}
                </h3>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "18px", lineHeight: "1.44", margin: "0", maxWidth: "560px", color: "rgba(46,59,64,0.86)" }}>
                  {t("012_p")}
                </p>
              </div>
              <span className="cm-arrow" style={{ flex: "0 0 auto", width: "56px", height: "56px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "24px" }}>
                →
              </span>
            </div>
          </Link>
        </section>
        {/* CTA BAND */}
        <section style={{ background: "var(--color-red)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("013_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "var(--in-community-5)", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("014_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/pathway", locale)} style={{ textDecoration: "none", color: "var(--color-red)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("015_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("016_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
