import { Fragment } from 'react';
import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/constellation.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/constellation.json';
import wordsko from '../i18n/resources/ko/pages/constellation.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import { sx } from '../lib/sx';
import useLogic from '../logic/Constellation';
import './Constellation.css';

/** Constellation — one component for every language, generated by
 *  scripts/convert-pages.mjs from Constellation.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/constellation.json; the
 *  line-heights that differ by language are custom properties in Constellation.css.
 *  Edit the legacy pages, not this file. */
export default function Constellation() {
  const t = usePageWords("constellation", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();
  const { cancelClose, closeSel, closeSoon, dots, hasMedia, hasRead, hasSel, hasView, labels, legend, mediaLabel, modeButtons, popStyle, selCaption, selDot, selFormat, selMedia, selMeta, selRead, selTitle, selView, skyHint } = useLogic();

  return (
    <SiteLayout page="Constellation.EN.dc.html" className="page-constellation" footer={{ loop: "0.897", cta: "#F0D23C" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (unchanged) */}
        <section data-screen-label="Hero" style={{ background: "var(--color-yellow)", color: "#1A1A1A" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#1A1A1A", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#1A1A1A" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "var(--in-constellation-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "16ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "720px", margin: "0", color: "rgba(26,26,26,0.82)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* THE SKY */}
        <section data-screen-label="The Sky" style={{ background: "#16242E", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 44px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "14px", alignItems: "center", justifyContent: "space-between", marginBottom: "8px" }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", alignItems: "center" }}>
                <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.6)" }}>
                  {t("003_span")}
                </span>
                {(modeButtons ?? []).map((m, mIndex) => (
                  <Fragment key={mIndex}>
                    <button onClick={m.onClick} style={sx(m.style)}>
                      {m.label}
                    </button>
                  </Fragment>
                ))}
              </div>
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "600", fontSize: "13px", letterSpacing: "0.04em", color: "rgba(250,244,226,0.55)" }}>
                {skyHint}
              </span>
            </div>
            <div style={{ position: "relative", width: "100%", height: "clamp(440px, 58vw, 620px)" }}>
              {(labels ?? []).map((lb, lbIndex) => (
                <Fragment key={lbIndex}>
                  <div className="ct-label" style={sx(lb.style)}>
                    {lb.text}
                  </div>
                </Fragment>
              ))}
              {(dots ?? []).map((d, dIndex) => (
                <Fragment key={dIndex}>
                  <button className="ct-dot" onClick={d.onClick} onMouseEnter={d.enter} onMouseLeave={d.leave} aria-label={d.title} style={sx(d.style)}>
                    <span style={sx(d.inner)} />
                  </button>
                </Fragment>
              ))}
              {/* DOT POPUP */}
              {hasSel ? (
                <>
                <div onMouseEnter={cancelClose} onMouseLeave={closeSoon} style={sx(popStyle)}>
                  <button onClick={closeSel} aria-label={t("004_aria-label")} style={{ position: "absolute", right: "6px", top: "6px", width: "44px", height: "44px", border: "none", background: "transparent", color: "rgba(46,59,64,0.6)", fontFamily: "var(--font-sans)", fontSize: "22px", lineHeight: "1", cursor: "pointer" }}>
                    ×
                  </button>
                  <div style={{ position: "relative", display: "flex", flexDirection: "column", padding: "22px 24px 22px 50px" }}>
                    <span style={sx(selDot)} />
                    <span style={{ position: "absolute", left: "15px", top: "40px", writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)" }}>
                      {selFormat}
                    </span>
                    <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-ink)", margin: "0 30px 8px 0" }}>
                      {selMeta}
                    </div>
                    <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "30px", lineHeight: "var(--in-constellation-1)", margin: "0 0 10px", textWrap: "balance" }}>
                      {selTitle}
                    </h3>
                    <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.4", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                      {selCaption}
                    </p>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginTop: "16px" }}>
                      {hasRead ? (
                        <>
                        <a href={selRead} style={{ textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "12px 24px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                          {t("005_a")}
                        </a>
                        </>
                      ) : null}
                      {hasMedia ? (
                        <>
                        <a href={selMedia} target="_blank" rel="noopener" style={{ textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "12px 24px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                          {mediaLabel}{" →"}
                        </a>
                        </>
                      ) : null}
                      {hasView ? (
                        <>
                        <a href={selView} target="_blank" rel="noopener" style={{ textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "12px 24px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                          {t("006_a")}
                        </a>
                        </>
                      ) : null}
                    </div>
                  </div>
                </div>
                </>
              ) : null}
            </div>
            {/* LEGEND */}
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px 18px", marginTop: "10px", borderTop: "1px solid rgba(250,244,226,0.14)", paddingTop: "16px" }}>
              {(legend ?? []).map((lg, lgIndex) => (
                <Fragment key={lgIndex}>
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "7px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)" }}>
                    <span style={sx(lg.swatch)} />
                    {lg.label}
                  </span>
                </Fragment>
              ))}
            </div>
          </div>
        </section>
        {/* DRAFT NOTE */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "26px 28px 0" }}>
          <div style={{ borderLeft: "3px solid var(--color-yellow)", background: "rgba(240,210,60,0.16)", padding: "16px 22px", fontFamily: "var(--font-sans)", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.72)" }}>
            {t("007_div")}
          </div>
        </section>
        {/* HOW IT WORKS */}
        <section data-screen-label="How it works" style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 20px" }}>
          <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "var(--in-constellation-2)", letterSpacing: "-0.01em", margin: "0 0 26px" }}>
            {t("008_h2")}
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "18px", alignItems: "stretch", maxWidth: "1100px" }}>
            <div style={{ background: "var(--color-paper-dim)", color: "var(--color-ink)", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-yellow)", clipPath: "polygon(50% 14%, 76% 100%, 24% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(76% 100%, 82% 100%, 54% 14%, 50% 14%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  1
                </div>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  {t("009_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)", color: "var(--color-ink)", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-yellow)", clipPath: "polygon(4% 0, 26% 0, 60% 100%, 38% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-amber)", clipPath: "polygon(24% 0, 34% 0, 68% 100%, 56% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#35C0B4", clipPath: "polygon(74% 0, 96% 0, 62% 100%, 40% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(66% 0, 76% 0, 44% 100%, 30% 100%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  2
                </div>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  {t("010_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)", color: "var(--color-ink)", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-yellow)", clipPath: "polygon(38% 8%, 72% 46%, 38% 84%, 4% 46%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(72% 46%, 76% 46%, 42% 8%, 38% 8%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#35C0B4", clipPath: "polygon(66% 44%, 96% 78%, 66% 112%, 36% 78%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#CDE3CF", clipPath: "polygon(96% 78%, 100% 78%, 70% 44%, 66% 44%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  3
                </div>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  {t("011_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)", color: "var(--color-ink)", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-yellow)", clipPath: "polygon(22% 28%, 38% 46%, 22% 64%, 6% 46%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(38% 46%, 41% 46%, 25% 28%, 22% 28%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#35C0B4", clipPath: "polygon(56% 8%, 72% 26%, 56% 44%, 40% 26%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#CDE3CF", clipPath: "polygon(72% 26%, 75% 26%, 59% 8%, 56% 8%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(76% 50%, 94% 70%, 76% 90%, 58% 70%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-yellow)", clipPath: "polygon(94% 70%, 97% 70%, 79% 50%, 76% 50%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  4
                </div>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  {t("012_p")}
                </p>
              </div>
            </div>
          </div>
          <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-constellation-3)", fontSize: "19px", lineHeight: "1.5", margin: "30px 0 0", color: "rgba(46,59,64,0.72)", maxWidth: "62ch" }}>
            {t("013_p")}
          </p>
          <div style={{ marginTop: "26px" }}>
            <Link to={localize("/story/submit", locale)} style={{ textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.06em", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
              {t("014_a")}
            </Link>
          </div>
        </section>
        {/* CTA (unchanged) */}
        <section data-screen-label="CTA" style={{ background: "var(--color-yellow)", color: "var(--color-ink)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", margin: "0 0 18px" }}>
              {t("015_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "var(--in-constellation-4)", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("016_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/story/submit", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("017_a")}
              </Link>
              <Link to={localize("/mewe", locale)} style={{ textDecoration: "none", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("018_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
