import { Fragment } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { sx } from '../lib/sx';
import useLogic from '../logic/ConstellationEN';
import './ConstellationEN.css';

/** Constellation.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ConstellationEN() {
  const { cancelClose, closeSel, closeSoon, dots, hasMedia, hasRead, hasSel, hasView, labels, legend, mediaLabel, modeButtons, popStyle, selCaption, selDot, selFormat, selMedia, selMeta, selRead, selTitle, selView, skyHint } = useLogic();

  return (
    <SiteLayout page="Constellation.EN.dc.html" className="page-constellation-en" footer={{ loop: "0.897", cta: "#F0D23C" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (unchanged) */}
        <section data-screen-label="Hero" style={{ background: "#F0D23C", color: "#1A1A1A" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#1A1A1A", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#1A1A1A" }}>
                Constellation
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "16ch", textWrap: "balance" }}>
              Separate points of light. One shape.
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "720px", margin: "0", color: "rgba(26,26,26,0.82)" }}>
              The living collection of neighbor expressions — every MEWE story, act, and creation. Alone, a single point. Together, a shape none of us makes on our own.
            </p>
          </div>
        </section>
        {/* THE SKY */}
        <section data-screen-label="The Sky" style={{ background: "#16242E", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 44px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "14px", alignItems: "center", justifyContent: "space-between", marginBottom: "8px" }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", alignItems: "center" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.6)" }}>
                  Arrange by
                </span>
                {(modeButtons ?? []).map((m, mIndex) => (
                  <Fragment key={mIndex}>
                    <button onClick={m.onClick} style={sx(m.style)}>
                      {m.label}
                    </button>
                  </Fragment>
                ))}
              </div>
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.04em", color: "rgba(250,244,226,0.55)" }}>
                {skyHint}
              </span>
            </div>
            <div style={{ position: "relative", width: "100%", height: "clamp(440px, 58vw, 620px)" }}>
              {(labels ?? []).map((lb, lbIndex) => (
                <Fragment key={lbIndex}>
                  <div className="ct-label" style={sx(lb.style)}>
                    {lb.text}
                  </div>
                </Fragment>
              ))}
              {(dots ?? []).map((d, dIndex) => (
                <Fragment key={dIndex}>
                  <button className="ct-dot" onClick={d.onClick} onMouseEnter={d.enter} onMouseLeave={d.leave} aria-label={d.title} style={sx(d.style)}>
                    <span style={sx(d.inner)} />
                  </button>
                </Fragment>
              ))}
              {/* DOT POPUP */}
              {hasSel ? (
                <>
                <div onMouseEnter={cancelClose} onMouseLeave={closeSoon} style={sx(popStyle)}>
                  <button onClick={closeSel} aria-label="Close" style={{ position: "absolute", right: "6px", top: "6px", width: "44px", height: "44px", border: "none", background: "transparent", color: "rgba(46,59,64,0.6)", fontFamily: "'Archivo', sans-serif", fontSize: "22px", lineHeight: "1", cursor: "pointer" }}>
                    ×
                  </button>
                  <div style={{ position: "relative", display: "flex", flexDirection: "column", padding: "22px 24px 22px 50px" }}>
                    <span style={sx(selDot)} />
                    <span style={{ position: "absolute", left: "15px", top: "40px", writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)" }}>
                      {selFormat}
                    </span>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 30px 8px 0" }}>
                      {selMeta}
                    </div>
                    <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "700", fontSize: "30px", lineHeight: "1.05", margin: "0 0 10px", textWrap: "balance" }}>
                      {selTitle}
                    </h3>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.4", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                      {selCaption}
                    </p>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginTop: "16px" }}>
                      {hasRead ? (
                        <>
                        <a href={selRead} style={{ textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "12px 24px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                          READ →
                        </a>
                        </>
                      ) : null}
                      {hasMedia ? (
                        <>
                        <a href={selMedia} target="_blank" rel="noopener" style={{ textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", color: "#2E3B40", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "12px 24px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                          {mediaLabel}{" →"}
                        </a>
                        </>
                      ) : null}
                      {hasView ? (
                        <>
                        <a href={selView} target="_blank" rel="noopener" style={{ textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", color: "#2E3B40", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "12px 24px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                          VIEW →
                        </a>
                        </>
                      ) : null}
                    </div>
                  </div>
                </div>
                </>
              ) : null}
            </div>
            {/* LEGEND */}
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px 18px", marginTop: "10px", borderTop: "1px solid rgba(250,244,226,0.14)", paddingTop: "16px" }}>
              {(legend ?? []).map((lg, lgIndex) => (
                <Fragment key={lgIndex}>
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "7px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)" }}>
                    <span style={sx(lg.swatch)} />
                    {lg.label}
                  </span>
                </Fragment>
              ))}
            </div>
          </div>
        </section>
        {/* DRAFT NOTE */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "26px 28px 0" }}>
          <div style={{ borderLeft: "3px solid #F0D23C", background: "rgba(240,210,60,0.16)", padding: "16px 22px", fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.72)" }}>
            Prototype v1 — all copy is draft; seed entries are placeholders. Arrange by Time and by ME=WE Arc, contributor filter, and inline playback come in v2.
          </div>
        </section>
        {/* HOW IT WORKS */}
        <section data-screen-label="How it works" style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 20px" }}>
          <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.02", letterSpacing: "-0.01em", margin: "0 0 26px" }}>
            How a light gets here
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "18px", alignItems: "stretch", maxWidth: "1100px" }}>
            <div style={{ background: "#F3EAD0", color: "#2E3B40", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(50% 14%, 76% 100%, 24% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(76% 100%, 82% 100%, 54% 14%, 50% 14%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  1
                </div>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  Make something, or notice something. A few honest sentences, a drawing, a photo, a film, a song.
                </p>
              </div>
            </div>
            <div style={{ background: "#F3EAD0", color: "#2E3B40", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(4% 0, 26% 0, 60% 100%, 38% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#FAB414", clipPath: "polygon(24% 0, 34% 0, 68% 100%, 56% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#35C0B4", clipPath: "polygon(74% 0, 96% 0, 62% 100%, 40% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(66% 0, 76% 0, 44% 100%, 30% 100%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  2
                </div>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  Share it through the Story form. One thing, one caption. Fifteen minutes is enough.
                </p>
              </div>
            </div>
            <div style={{ background: "#F3EAD0", color: "#2E3B40", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(38% 8%, 72% 46%, 38% 84%, 4% 46%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(72% 46%, 76% 46%, 42% 8%, 38% 8%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#35C0B4", clipPath: "polygon(66% 44%, 96% 78%, 66% 112%, 36% 78%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#CDE3CF", clipPath: "polygon(96% 78%, 100% 78%, 70% 44%, 66% 44%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  3
                </div>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  It appears here as a new light. Everything you add appears in the Constellation we are creating together. Some stories are also chosen for the Story page.
                </p>
              </div>
            </div>
            <div style={{ background: "#F3EAD0", color: "#2E3B40", display: "flex", flexDirection: "column" }}>
              <div style={{ position: "relative", height: "96px", overflow: "hidden", background: "#16242E" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "184px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(22% 28%, 38% 46%, 22% 64%, 6% 46%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(38% 46%, 41% 46%, 25% 28%, 22% 28%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#35C0B4", clipPath: "polygon(56% 8%, 72% 26%, 56% 44%, 40% 26%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#CDE3CF", clipPath: "polygon(72% 26%, 75% 26%, 59% 8%, 56% 8%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#7BC4F0", clipPath: "polygon(76% 50%, 94% 70%, 76% 90%, 58% 70%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(94% 70%, 97% 70%, 79% 50%, 76% 50%)" }} />
                </div>
              </div>
              <div style={{ padding: "22px 24px 26px", display: "flex", flexDirection: "column", flex: "1", gap: "10px" }}>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "15px", color: "#B87A00" }}>
                  4
                </div>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  Add as many as you like. Each one joins your name's own small constellation.
                </p>
              </div>
            </div>
          </div>
          <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontSize: "19px", lineHeight: "1.5", margin: "30px 0 0", color: "rgba(46,59,64,0.72)", maxWidth: "62ch" }}>
            Anyone can add — no workshop needed. And IN keeps adding too: every workshop ends with participants placing their pieces here. Many pieces begin in the Möbius Making workshop.
          </p>
          <div style={{ marginTop: "26px" }}>
            <Link to="/story/submit" style={{ textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.06em", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
              ADD YOURS
            </Link>
          </div>
        </section>
        {/* CTA (unchanged) */}
        <section data-screen-label="CTA" style={{ background: "#F0D23C", color: "#2E3B40", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              Add your light to the collection.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/story/submit" style={{ textDecoration: "none", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                Share your story
              </Link>
              <Link to="/mewe" style={{ textDecoration: "none", color: "#2E3B40", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                What is MEWE?
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
