import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/home.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/home.json';
import wordsko from '../i18n/resources/ko/pages/home.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import HomeNewsCard from '../components/cards/HomeNewsCard';
import { localize, useLocale } from '../lib/lang';
import './Home.css';

/** Home — one component for every language, generated by
 *  scripts/convert-pages.mjs from Home.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/home.json; the
 *  line-heights that differ by language are custom properties in Home.css.
 *  Edit the legacy pages, not this file. */
export default function Home() {
  const t = usePageWords("home", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Home.EN.dc.html" className="page-home" footer={{ loop: "0.14" }}>
      <main id="top" style={{ maxWidth: "1320px", margin: "0 auto", padding: "0 40px" }}>
        <section style={{ padding: "84px 0 72px 120px", minHeight: "300px", height: "200px" }}>
          <div style={{ maxWidth: "1000px", position: "relative" }}>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "var(--in-home-0)", lineHeight: "var(--in-home-1)", color: "var(--in-home-2)", marginBottom: "12px" }}>
              {t("000_h1")}
            </h1>
            <div style={{ fontFamily: "var(--font-serif)", fontWeight: "100", fontSize: "60px", lineHeight: "var(--in-home-3)", color: "var(--in-home-4)", width: "800px", height: "300px" }}>
              {t("001_div")}
              <em>
                {t("002_em")}
              </em>
              {t("003_div")}
            </div>
            <span style={{ position: "absolute", fontSize: "300px", lineHeight: "0.6", opacity: "1", pointerEvents: "none", left: "565px", top: "326px", color: "var(--in-home-5)", fontFamily: "var(--font-serif)", height: "100px" }} aria-hidden="true">
              ”
            </span>
          </div>
        </section>
        <section style={{ padding: "var(--space-9) 40px 100px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "22px" }}>
            {/* 1 · ME=WE (slate) */}
            <Link to={localize("/mewe", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-deepblue)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-teal)", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-deepblue)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".8" }}>
                    {t("004_span")}
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "46px", lineHeight: "1", marginBottom: "18px" }}>
                  {t("005_div")}
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".9" }}>
                  {t("006_p")}
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 2 · Workshop / Möbius (magenta) */}
            <Link to={localize("/workshop/mobius-making", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-magenta)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-plum)", clipPath: "polygon(0 0, 100% 0, 50% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-magenta)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".8" }}>
                    {t("007_span")}
                  </span>
                </div>
                <div style={{ font: "var(--text-eyebrow)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-eyebrow)", textTransform: "uppercase", opacity: ".85", marginBottom: "16px" }}>
                  {t("008_div")}
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "32px", lineHeight: "1.12", marginBottom: "16px" }}>
                  {t("009_div")}
                  <em>
                    {t("010_em")}
                  </em>
                  {t("011_div")}
                  <br />
                  {t("012_div")}
                  <em>
                    {t("013_em")}
                  </em>
                  {t("014_div")}
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".9" }}>
                  {t("015_p")}
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 3 · Pathway (orange) */}
            <Link to={localize("/pathway", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-orange)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-red)", clipPath: "polygon(0 100%, 0 40%, 54% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-red)", clipPath: "polygon(100% 100%, 100% 18%, 58% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-orange)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".7" }}>
                    {t("016_span")}
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "27px", lineHeight: "1.14", marginBottom: "16px" }}>
                  {t("017_div")}
                  <br />
                  {t("018_div")}
                </div>
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    {t("019_div")}
                  </div>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    {t("020_div")}
                  </div>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    {t("021_div")}
                  </div>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    {t("022_div")}
                  </div>
                </div>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 4 · Story (yellow · quote / pass it on) */}
            <Link to={localize("/story", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-amber)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-orange)", clipPath: "polygon(18% 100%, 30% 12%, 46% 100%)" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-amber)", boxShadow: "0 0 0 1px var(--color-ink)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".6" }}>
                    {t("023_span")}
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-home-6)", fontWeight: "500", fontSize: "27px", lineHeight: "1.28", marginBottom: "24px" }}>
                  {t("024_div")}
                </div>
                <div style={{ font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", color: "var(--color-ink)", opacity: ".7", marginRight: "56px" }}>
                  {t("025_div")}
                </div>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 5 · Community (red) */}
            <Link to={localize("/community", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-red)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-amber)", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-red)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".6" }}>
                    {t("026_span")}
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "29px", lineHeight: "1.14", marginBottom: "12px" }}>
                  {t("027_div")}
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", color: "var(--color-ink-40)" }}>
                  {t("028_p")}
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 6 · Constellation / Voices (yellow · quote) */}
            <Link to={localize("/constellation", locale)} style={{ textDecoration: "none", position: "relative", display: "flex", flexDirection: "column", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-yellow)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-green)", clipPath: "polygon(0 0, 100% 0, 50% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-yellow)", boxShadow: "0 0 0 1px var(--color-ink)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".55" }}>
                    {t("029_span")}
                  </span>
                </div>
                <p style={{ margin: "0 0 20px", fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "23px", lineHeight: "1.4" }}>
                  {t("030_p")}
                  <em>
                    {t("031_em")}
                  </em>
                  {t("032_p")}
                  <em>
                    {t("033_em")}
                  </em>
                  {t("034_p")}
                </p>
                <div style={{ font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", color: "var(--color-ink-40)" }}>
                  {t("035_div")}
                </div>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 7 · News (tan) */}
            <HomeNewsCard />
            {/* 7b · Insight (full card image) */}
            <Link to={localize("/news", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", gridRow: "span 2", overflow: "hidden", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", aspectRatio: "3/4", overflow: "hidden" }}>
                <img src="/community-img/news-fuller-quote-card.jpg" alt={t("036_alt")} style={{ position: "absolute", inset: "0", width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
              </div>
              <div style={{ position: "relative", display: "flex", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-tan)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", color: "var(--color-paper)" }}>
                    {t("037_span")}
                  </span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", flex: "1" }}>
                  <div style={{ font: "var(--text-eyebrow)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-eyebrow)", textTransform: "uppercase", color: "var(--color-tan)", marginBottom: "12px" }}>
                    {t("038_div")}
                  </div>
                  <div style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "27px", lineHeight: "1.14", marginBottom: "12px" }}>
                    {t("039_div")}
                  </div>
                  <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".9" }}>
                    {t("040_p")}
                  </p>
                  <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                    →
                  </span>
                </div>
              </div>
            </Link>
            {/* 8 · Projects (slate) */}
            <Link to={localize("/project", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-slate)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-teal)", clipPath: "polygon(18% 100%, 30% 12%, 46% 100%)" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-slate)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".6" }}>
                    {t("041_span")}
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "29px", lineHeight: "1.14", marginBottom: "12px" }}>
                  {t("042_div")}
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", color: "var(--color-ink-40)" }}>
                  {t("043_p")}
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 9 · Manifesto (teal) */}
            <Link to={localize("/manifesto", locale)} style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-teal)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-yellow)", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-teal)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".7" }}>
                    {t("044_span")}
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", lineHeight: "1.12", marginBottom: "14px" }}>
                  {t("045_div")}
                  <em>
                    {t("046_em")}
                  </em>
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".82" }}>
                  {t("047_p")}
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
          </div>
        </section>
      </main>
      <section style={{ padding: "0 40px 100px", display: "flex", flexWrap: "wrap", gap: "14px", justifyContent: "center" }}>
        <Link to={localize("/mewe", locale)} style={{ display: "inline-flex", alignItems: "center", lineHeight: "1.2", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-paper)", background: "var(--color-ink)", border: "1.5px solid var(--color-ink)", borderRadius: "999px", padding: "15px 32px" }} className="in-plain">
          {t("048_a")}
        </Link>
        <Link to={localize("/workshop", locale)} style={{ display: "inline-flex", alignItems: "center", lineHeight: "1.2", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(26,22,19,0.35)", borderRadius: "999px", padding: "15px 32px" }} className="in-plain">
          {t("049_a")}
        </Link>
        <Link to={localize("/connect", locale)} style={{ display: "inline-flex", alignItems: "center", lineHeight: "1.2", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(26,22,19,0.35)", borderRadius: "999px", padding: "15px 32px" }} className="in-plain">
          {t("050_a")}
        </Link>
      </section>
    </SiteLayout>
  );
}
