import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import HomeNewsCard from '../components/cards/HomeNewsCard';
import './HomeKO.css';

/** Home.KO.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function HomeKO() {
  return (
    <SiteLayout page="Home.KO.dc.html" className="page-home-ko" footer={{ loop: "0.14" }}>
      <main id="top" style={{ maxWidth: "1320px", margin: "0 auto", padding: "0 40px" }}>
        <section style={{ padding: "84px 0 72px 120px" }}>
          <div style={{ maxWidth: "1000px", position: "relative", minHeight: "426px" }}>
            <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "80px", lineHeight: "1.12", color: "#1E8A86", marginBottom: "12px" }}>
              IN은 스튜디오입니다
            </div>
            <div style={{ fontFamily: "var(--font-serif)", fontWeight: "100", fontSize: "60px", lineHeight: "1", color: "#1E8A86", maxWidth: "800px" }}>
              {"정직한 대화와 예술적 표현으로 MEWE를 "}
              <em>
                실천
              </em>
              하는 곳.
            </div>
            <span style={{ position: "absolute", fontSize: "300px", lineHeight: "0.6", opacity: "1", pointerEvents: "none", left: "565px", top: "326px", color: "#1E8A86", fontFamily: "Newsreader", height: "100px" }} aria-hidden="true">
              ”
            </span>
          </div>
        </section>
        <section style={{ padding: "var(--space-9) 40px 100px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "22px" }}>
            {/* 1 · MEWE (slate) */}
            <Link to="/ko/mewe" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-deepblue)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#1E8A86", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-deepblue)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".8" }}>
                    MEWE
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "46px", lineHeight: "1", marginBottom: "18px" }}>
                  MEWE
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".9" }}>
                  분리는 느낌일 뿐, 관계는 구조입니다. 우리는 패턴 밖에 있지 않습니다 — 우리가 곧 그 패턴의 표현입니다.
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 2 · Workshop / Möbius (magenta) */}
            <Link to="/ko/workshop/mobius-making" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-magenta)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#46325A", clipPath: "polygon(0 0, 100% 0, 50% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-magenta)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".8" }}>
                    워크숍 · 모두에게
                  </span>
                </div>
                <div style={{ font: "var(--text-eyebrow)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-eyebrow)", textTransform: "uppercase", opacity: ".85", marginBottom: "16px" }}>
                  여기서 시작 · 3시간 · 손으로 직접
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "32px", lineHeight: "1.12", marginBottom: "16px" }}>
                  {"MEWE는 "}
                  <em>
                    가르치지
                  </em>
                  {" 않습니다."}
                  <br />
                  {"함께 "}
                  <em>
                    연습
                  </em>
                  합니다.
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".9" }}>
                  뫼비우스 만들기 — 대표 워크숍. 종이 띠를 접다 보면 두 면이 처음부터 하나의 면이었음을 발견하게 됩니다.
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 3 · Protagonist (orange) */}
            <Link to="/ko/protagonist" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-orange)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#D21E28", clipPath: "polygon(0 100%, 0 40%, 54% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "#D21E28", clipPath: "polygon(100% 100%, 100% 18%, 58% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-orange)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".7" }}>
                    주역
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "27px", lineHeight: "1.14", marginBottom: "16px" }}>
                  하나의 실천,
                  <br />
                  네 가지 깊이
                </div>
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    이웃
                  </div>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    브리지 빌더
                  </div>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    퍼실리테이터
                  </div>
                  <div style={{ font: "var(--text-body)", fontFamily: "var(--font-serif)", padding: "10px 0", borderTop: "1px solid rgba(46,59,64,.22)", marginRight: "56px" }}>
                    IN-콜렉티브
                  </div>
                </div>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 4 · Story (yellow · quote / pass it on) */}
            <Link to="/ko/story" style={{ position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-amber)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#F05A28", clipPath: "polygon(18% 100%, 30% 12%, 46% 100%)" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-amber)", boxShadow: "0 0 0 1px var(--color-ink)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".6" }}>
                    스토리
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontStyle: "normal", fontWeight: "500", fontSize: "27px", lineHeight: "1.28", marginBottom: "24px" }}>
                  “어쩌면 우리는 이미 연결되어 있었는지도.”
                </div>
                <div style={{ font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", color: "var(--color-ink)", opacity: ".7", marginRight: "56px" }}>
                  스토리를 건네주세요 →
                </div>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 5 · Community (red) */}
            <Link to="/ko/community" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-red)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#FAB414", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-red)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".6" }}>
                    커뮤니티
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "29px", lineHeight: "1.14", marginBottom: "12px" }}>
                  멈추지 않고 여행한 실천
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", color: "var(--color-ink-40)" }}>
                  커뮤니티
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 6 · Constellation / Voices (yellow · quote) */}
            <Link to="/ko/constellation" style={{ textDecoration: "none", position: "relative", display: "flex", flexDirection: "column", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-yellow)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#3C8246", clipPath: "polygon(0 0, 100% 0, 50% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-yellow)", boxShadow: "0 0 0 1px var(--color-ink)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".55" }}>
                    목소리
                  </span>
                </div>
                <p style={{ margin: "0 0 20px", fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "23px", lineHeight: "1.4" }}>
                  {"“우리는 "}
                  <em>
                    에고 시스템
                  </em>
                  {"에서 전체를 품는 "}
                  <em>
                    생태계
                  </em>
                  의 감각으로 옮겨가야 합니다.”
                </p>
                <div style={{ font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", color: "var(--color-ink-40)" }}>
                  — 오토 샤머
                </div>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 7 · News (tan) */}
            <HomeNewsCard />
            {/* 7b · Insight (full card image) */}
            <Link to="/ko/news" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", gridRow: "span 2", overflow: "hidden", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", aspectRatio: "3/4", overflow: "hidden" }}>
                <img src="/community-img/news-fuller-quote-card.jpg" alt="“The world changes when we change how we see and move within it — alone, we tilt, but together, we turn.” — Buckminster Fuller" style={{ position: "absolute", inset: "0", width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
              </div>
              <div style={{ position: "relative", display: "flex", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-tan)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", color: "var(--color-paper)" }}>
                    인사이트
                  </span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", flex: "1" }}>
                  <div style={{ font: "var(--text-eyebrow)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-eyebrow)", textTransform: "uppercase", color: "var(--color-tan)", marginBottom: "12px" }}>
                    카드 시리즈
                  </div>
                  <div style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "27px", lineHeight: "1.14", marginBottom: "12px" }}>
                    자꾸 돌아오게 되는 한 문장
                  </div>
                  <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".9" }}>
                    MEWE 네트워크에서 건네지는 카드 — 예술, 과학, 사회적 실천, 영성이 하나의 대화가 됩니다.
                  </p>
                  <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                    →
                  </span>
                </div>
              </div>
            </Link>
            {/* 8 · Projects (slate) */}
            <Link to="/ko/project" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-slate)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#1E8A86", clipPath: "polygon(18% 100%, 30% 12%, 46% 100%)" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-slate)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".6" }}>
                    프로젝트
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "29px", lineHeight: "1.14", marginBottom: "12px" }}>
                  실천이 형태를 갖추는 곳
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", color: "var(--color-ink-40)" }}>
                  프로젝트
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
            {/* 9 · Manifesto (teal) */}
            <Link to="/ko/manifesto" style={{ position: "relative", display: "flex", flexDirection: "column", textDecoration: "none", background: "var(--color-paper)", border: "1px solid rgba(26,22,19,0.14)", color: "var(--color-ink)", minHeight: "340px", transition: "transform .16s var(--ease-standard), box-shadow .16s var(--ease-standard)" }} className="in-card in-plain">
              <div style={{ position: "relative", width: "100%", height: "14px", overflow: "hidden", flex: "0 0 auto", background: "var(--color-teal)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "46px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", padding: "20px 22px 20px 44px" }}>
                <div style={{ position: "absolute", left: "13px", top: "21px", zIndex: "2", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                  <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-teal)" }} />
                  <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", textOrientation: "mixed", font: "var(--text-label)", fontFamily: "var(--font-sans)", letterSpacing: "var(--tracking-label)", textTransform: "uppercase", opacity: ".7" }}>
                    읽기
                  </span>
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", lineHeight: "1.12", marginBottom: "14px" }}>
                  {"가능성을 "}
                  <em>
                    현실로
                  </em>
                </div>
                <p style={{ margin: "0 56px 0 0", font: "var(--text-body)", fontFamily: "var(--font-serif)", opacity: ".82" }}>
                  IN 매니페스토 — 지금 우리가 참이라 여기는 아홉 가지.
                </p>
                <span style={{ position: "absolute", right: "24px", bottom: "24px", width: "46px", height: "46px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "20px" }}>
                  →
                </span>
              </div>
            </Link>
          </div>
        </section>
      </main>
      <section style={{ padding: "0 40px 100px", display: "flex", flexWrap: "wrap", gap: "14px", justifyContent: "center" }}>
        <Link to="/ko/mewe" style={{ display: "inline-flex", alignItems: "center", lineHeight: "1.2", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-paper)", background: "var(--color-ink)", border: "1.5px solid var(--color-ink)", borderRadius: "999px", padding: "15px 32px" }} className="in-plain">
          MEWE 알아보기
        </Link>
        <Link to="/ko/workshop" style={{ display: "inline-flex", alignItems: "center", lineHeight: "1.2", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(26,22,19,0.35)", borderRadius: "999px", padding: "15px 32px" }} className="in-plain">
          스튜디오 참여하기
        </Link>
        <Link to="/ko/connect" style={{ display: "inline-flex", alignItems: "center", lineHeight: "1.2", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(26,22,19,0.35)", borderRadius: "999px", padding: "15px 32px" }} className="in-plain">
          연결하기
        </Link>
      </section>
    </SiteLayout>
  );
}
