import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/manifesto.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/manifesto.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import './ManifestoEN.css';

/** Manifesto.EN.dc.html — generated by scripts/convert-pages.mjs. Serves /manifesto and
 *  /zh-tw/manifesto: this page's KO twin did not collapse into it, but
 *  zh-TW has no edition in site/ and reads this one. Its words are in
 *  src/i18n/resources/<locale>/pages/manifesto.json.
 *  Edit the legacy page, or take this file over by hand and remove it from
 *  the converter's input. */
export default function ManifestoEN() {
  const t = usePageWords("manifesto", { "en": wordsen, "zh-TW": wordszhTW });
  const locale = useLocale();

  return (
    <SiteLayout page="Manifesto.EN.dc.html" className="page-manifesto-en" footer={{ loop: "0.080", cta: "#1E8A86" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO ===================== */}
        <section style={{ color: "var(--color-paper)", backgroundColor: "var(--color-teal)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 26px", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", margin: "0", color: "rgba(250,244,226,0.94)", maxWidth: "56ch", textAlign: "left" }}>
              <em style={{ fontSize: "50px" }}>
                {t("002_em")}
              </em>
              <br />
              {t("003_p")}
            </p>
          </div>
        </section>
        {/* ===================== §1 · WHO WE ARE ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "80px 28px 0" }}>
          <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "26px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal)", marginBottom: "24px" }}>
            {t("004_div")}
          </div>
          <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(28px, 3.4vw, 50px)", lineHeight: "1.15", margin: "0 0 20px", letterSpacing: "-0.01em", maxWidth: "22ch", fontWeight: "600", height: "330px", width: "800px" }}>
            {t("005_p")}
            <span style={{ color: "var(--color-teal)", fontStyle: "normal", fontWeight: "700" }}>
              {t("006_span")}
            </span>
            .
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "18px", alignItems: "stretch" }}>
            <div style={{ background: "var(--color-paper-dim)" }}>
              <div style={{ position: "relative", height: "56px", overflow: "hidden", background: "var(--color-red)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "102px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-amber)", clipPath: "polygon(0 100%, 0 40%, 54% 100%)" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-orange)", clipPath: "polygon(100% 100%, 100% 18%, 58% 100%)" }} />
                </div>
              </div>
              <div style={{ padding: "28px 28px 32px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#A81820", marginBottom: "14px" }}>
                  {t("007_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("008_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("009_p")}
                  <b>
                    {t("010_b")}
                  </b>
                  {t("011_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)" }}>
              <div style={{ position: "relative", height: "56px", overflow: "hidden", background: "var(--color-deepblue)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "102px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-teal)", clipPath: "polygon(100% 100%, 100% 34%, 30% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ padding: "28px 28px 32px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "14px" }}>
                  {t("012_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("013_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("014_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)" }}>
              <div style={{ position: "relative", height: "56px", overflow: "hidden", background: "var(--color-magenta-hot)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "102px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-plum)", clipPath: "polygon(34% 100%, 50% 22%, 66% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ padding: "28px 28px 32px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#8E2166", marginBottom: "14px" }}>
                  {t("015_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("016_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("017_p")}
                  <Link to={localize("/people", locale)} style={{ color: "#8E2166" }} className="in-plain">
                    {t("018_a")}
                  </Link>
                  {t("019_p")}
                </p>
              </div>
            </div>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "18px", alignItems: "stretch" }}>
            <div style={{ border: "1px solid rgba(26,22,19,0.14)", backgroundColor: "var(--color-paper)" }}>
              <div style={{ padding: "28px 28px 24px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#B4321A", marginBottom: "14px" }}>
                  {t("020_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("021_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("022_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)", border: "1px solid rgba(26,22,19,0.14)" }}>
              <div style={{ padding: "28px 28px 24px", backgroundColor: "var(--color-paper)" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "14px" }}>
                  {t("023_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("024_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("025_p")}
                </p>
              </div>
            </div>
            <div style={{ border: "1px solid rgba(26,22,19,0.14)", backgroundColor: "var(--color-paper)" }}>
              <div style={{ padding: "28px 28px 24px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "14px" }}>
                  {t("026_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("027_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("028_p")}
                </p>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== THE MANIFESTO ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(30px, 3.4vw, 50px)", lineHeight: "1.2", margin: "0", color: "#1A1613", maxWidth: "900px" }}>
            <b style={{ color: "rgb(30, 138, 134)", fontWeight: "500" }}>
              {t("029_b")}
              <br />
            </b>
            {t("030_p")}
          </p>
        </section>
        <section style={{ position: "relative", width: "100%", margin: "80px 0 0", padding: "0", overflow: "hidden", background: "var(--color-paper-dim)" }}>
          <div aria-hidden="true" style={{ position: "absolute", left: "0", top: "0", bottom: "0", width: "47px", overflow: "hidden", background: "#E52D84", transform: "rotate(180deg)" }}>
            <div style={{ position: "absolute", inset: "0", background: "#433370", clipPath: "polygon(0 0, 100% 0, 100% 12.05%)" }} />
            <div style={{ position: "absolute", inset: "0", background: "#D4232B", clipPath: "polygon(100% 87.95%, 100% 100%, 0 100%)" }} />
          </div>
          <div style={{ position: "relative", maxWidth: "1320px", margin: "0 auto", padding: "76px 28px 80px 82px" }}>
            <div style={{ maxWidth: "900px" }}>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "18px", whiteSpace: "nowrap" }}>
                {t("031_div")}
              </div>
              <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(26px, 2.8vw, 40px)", lineHeight: "1.18", letterSpacing: "-0.01em", margin: "0", color: "#1A1613", fontStyle: "italic", textWrap: "pretty" }}>
                {t("032_p")}
              </p>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "80px 28px 0" }}>
          <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "26px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal)", marginBottom: "14px" }}>
            {t("033_div")}
          </div>
          <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 4vw, 52px)", lineHeight: "1.0", letterSpacing: "-0.02em", margin: "0 0 28px", textWrap: "balance" }}>
            {t("034_h2")}
          </h2>
          <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 1.7vw, 24px)", lineHeight: "1.35", margin: "0", color: "#1A1613", maxWidth: "62ch", textAlign: "left" }}>
            {t("035_p")}
          </p>
        </section>
        {/* ===================== PRINCIPLES ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px 0" }}>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-teal)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "14px" }}>
              {t("036_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("037_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("038_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-magenta-hot)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "14px" }}>
              {t("039_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("040_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("041_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-deepblue)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "14px" }}>
              {t("042_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("043_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("044_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-plum)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-plum)", marginBottom: "14px" }}>
              {t("045_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("046_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("047_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-green)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#2E6B33", marginBottom: "14px" }}>
              {t("048_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("049_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("050_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-amber)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#7A5200", marginBottom: "14px" }}>
              {t("051_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("052_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("053_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-teal)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "14px" }}>
              {t("054_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("055_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("056_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-magenta-hot)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "14px" }}>
              {t("057_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("058_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("059_p")}
            </p>
          </div>
          <div style={{ borderTop: "1px solid rgba(38,42,56,0.16)", borderBottom: "1px solid rgba(38,42,56,0.16)", borderLeft: "7px solid var(--color-deepblue)", padding: "44px 0 44px 30px", maxWidth: "1000px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-deepblue)", marginBottom: "14px" }}>
              {t("060_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 50px)", lineHeight: "1.18", margin: "0 0 18px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("061_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.2vw, 30px)", lineHeight: "1.3", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("062_p")}
            </p>
          </div>
        </section>
        <section style={{ position: "relative", width: "100%", margin: "80px 0 0", padding: "0", overflow: "hidden", background: "var(--color-paper-dim)" }}>
          <div aria-hidden="true" style={{ position: "absolute", left: "0", top: "0", bottom: "0", width: "47px", overflow: "hidden", background: "#E52D84", transform: "rotate(180deg)" }}>
            <div style={{ position: "absolute", inset: "0", background: "#433370", clipPath: "polygon(0 0, 100% 0, 100% 12.05%)" }} />
            <div style={{ position: "absolute", inset: "0", background: "#D4232B", clipPath: "polygon(100% 87.95%, 100% 100%, 0 100%)" }} />
          </div>
          <div style={{ position: "relative", maxWidth: "1320px", margin: "0 auto", padding: "76px 28px 80px 82px" }}>
            <div style={{ maxWidth: "900px" }}>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "18px", whiteSpace: "nowrap" }}>
                {t("063_div")}
              </div>
              <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 2.8vw, 40px)", lineHeight: "1.1", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "12px" }}>
                {t("064_div")}
              </div>
              <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(26px, 2.8vw, 40px)", lineHeight: "1.1", letterSpacing: "-0.01em", color: "#1A1613" }}>
                {t("065_div")}
                <em>
                  {t("066_em")}
                </em>
                {t("067_div")}
              </div>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ paddingTop: "40px", position: "relative" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "26px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-teal)", marginBottom: "16px", height: "60px" }}>
              {t("068_div")}
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 4vw, 52px)", lineHeight: "1.0", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "20ch", textWrap: "balance", width: "800px" }}>
              {t("069_h2")}
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 26px)", lineHeight: "1.35", maxWidth: "46ch", margin: "0", color: "rgba(38,42,56,0.82)" }}>
              {t("070_p")}
            </p>
          </div>
        </section>
        {/* ===================== IN STORY · the journey ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "36px 28px 24px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "18px", alignItems: "stretch" }}>
            <div style={{ background: "var(--color-paper-dim)", border: "1px solid rgba(26,22,19,0.14)" }}>
              <div style={{ position: "relative", height: "56px", overflow: "hidden", background: "var(--color-paper)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "102px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-amber)", clipPath: "polygon(0 0, 28% 0, 100% 100%, 72% 100%)", mixBlendMode: "multiply" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-deepblue)", clipPath: "polygon(72% 0, 100% 0, 28% 100%, 0 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ padding: "28px 28px 32px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#7A5200", marginBottom: "14px" }}>
                  {t("071_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("072_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("073_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)", border: "1px solid rgba(26,22,19,0.14)" }}>
              <div style={{ position: "relative", height: "56px", overflow: "hidden", background: "var(--color-paper)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "102px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-magenta-hot)", clipPath: "polygon(0 0, 26% 0, 62% 100%, 38% 100%)", mixBlendMode: "multiply" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-teal)", clipPath: "polygon(74% 0, 100% 0, 62% 100%, 38% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ padding: "28px 28px 32px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-teal-dark)", marginBottom: "14px" }}>
                  {t("074_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("075_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("076_p")}
                </p>
              </div>
            </div>
            <div style={{ background: "var(--color-paper-dim)", border: "1px solid rgba(26,22,19,0.14)" }}>
              <div style={{ position: "relative", height: "56px", overflow: "hidden", background: "var(--color-paper)" }}>
                <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "102px" }}>
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-orange)", clipPath: "polygon(0 100%, 48% 0, 96% 100%)", mixBlendMode: "multiply" }} />
                  <div style={{ position: "absolute", inset: "0", background: "var(--color-plum)", clipPath: "polygon(24% 100%, 100% 0, 100% 100%)", mixBlendMode: "multiply" }} />
                </div>
              </div>
              <div style={{ padding: "28px 28px 32px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#B4321A", marginBottom: "14px" }}>
                  {t("077_div")}
                </div>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", lineHeight: "1.05", letterSpacing: "-0.01em", color: "#1A1613", marginBottom: "14px", textWrap: "balance" }}>
                  {t("078_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(26,22,19,0.78)" }}>
                  {t("079_p")}
                </p>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== THE PATH, IN BRIEF ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "56px 28px 20px" }}>
          <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.5", margin: "0 0 28px", color: "#262A38" }}>
            {t("080_p")}
            <Link to={localize("/community", locale)} style={{ color: "rgb(30, 138, 134)" }} className="in-plain">
              {t("081_a")}
            </Link>
            {t("082_p")}
            <Link to={localize("/project", locale)} style={{ color: "rgb(30, 138, 134)" }} className="in-plain">
              {t("083_a")}
            </Link>
            {t("084_p")}
            <br />
          </p>
          <p style={{ margin: "0", fontSize: "22px", lineHeight: "1.3" }}>
            {t("085_p")}
          </p>
          <div style={{ display: "flex", flexDirection: "column", maxWidth: "1000px" }} />
          <div style={{ maxWidth: "1000px", margin: "48px 0 0", borderTop: "1.5px solid rgba(38,42,56,0.16)", paddingTop: "32px" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-slate)", margin: "0 0 12px" }}>
              {t("086_p")}
            </p>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "22px", lineHeight: "1.3", margin: "0", color: "#262A38" }}>
              {t("087_p")}
            </p>
          </div>
        </section>
        <section style={{ background: "var(--color-teal)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("088_p")}
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 26px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("089_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/mewe", locale)} style={{ textDecoration: "none", color: "var(--color-teal)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("090_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("091_a")}
              </Link>
            </div>
          </div>
        </section>
        {/* ===================== FOOTER ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
