import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/mewe.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/mewe.json';
import wordsko from '../i18n/resources/ko/pages/mewe.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import { localize, useLocale } from '../lib/lang';
import './MEWE.css';

/** MEWE — one component for every language, generated by
 *  scripts/convert-pages.mjs from MEWE.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/mewe.json; the
 *  line-heights that differ by language are custom properties in MEWE.css.
 *  Edit the legacy pages, not this file. */
export default function MEWE() {
  const t = usePageWords("mewe", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="MEWE.EN.dc.html" className="page-mewe" footer={{ loop: "0.126", cta: "#1E648C" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (locked) */}
        <section data-screen-label="Hero" style={{ background: "#1E648C", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#FAF4E2", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#FAF4E2" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "var(--in-mewe-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "18ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(30px, 3.6vw, 50px)", lineHeight: "var(--in-mewe-1)", margin: "0", letterSpacing: "-0.01em", color: "#F0D23C" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* INTRO STATEMENT */}
        <section data-screen-label="The pattern" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.3", margin: "0", maxWidth: "900px", color: "#1A1613" }}>
            {t("003_p")}
          </p>
        </section>
        {/* 1 · MEWE RELATIONSHIP */}
        <section data-screen-label="1 MEWE Relationship" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              {t("004_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontStyle: "var(--in-mewe-2)", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.1", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "pretty", color: "#1C6E92" }}>
              {t("005_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 18px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("006_p")}
            </p>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("007_p")}
            </p>
          </div>
        </section>
        {/* 2 · NATURE ALREADY KNOWS */}
        <section data-screen-label="2 Nature already knows" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              {t("008_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-mewe-3)", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              {t("009_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 40px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("010_p")}
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "26px" }}>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  {t("011_div")}
                </div>
                <ImageSlot id="mewe-dna" shape="rect" placeholder="DNA — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  {t("012_p")}
                </p>
              </div>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  {t("013_div")}
                </div>
                <ImageSlot id="mewe-nervous" shape="rect" placeholder="Nervous systems — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  {t("014_p")}
                </p>
              </div>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  {t("015_div")}
                </div>
                <ImageSlot id="mewe-roots" shape="rect" placeholder="Forest roots — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  {t("016_p")}
                </p>
              </div>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  {t("017_div")}
                </div>
                <ImageSlot id="mewe-ecosystems" shape="rect" placeholder="Ecosystems — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  {t("018_p")}
                </p>
              </div>
            </div>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(22px, 2.4vw, 28px)", lineHeight: "1.32", margin: "40px 0 0", maxWidth: "760px", color: "#1E648C", textWrap: "pretty" }}>
              {t("019_p")}
              <span style={{ color: "#1C6E92" }}>
                {t("020_span")}
              </span>
            </p>
          </div>
        </section>
        {/* DIVIDER · THE MÖBIUS FLIP */}
        <section data-screen-label="The Möbius Flip" style={{ background: "#1C6E92", color: "#FFFFFF", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 48px", backgroundColor: "#1C6E92" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "#FFFFFF", marginBottom: "22px" }}>
              {t("021_div")}
            </div>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(28px, 3.4vw, 30px)", lineHeight: "1.2", margin: "0", maxWidth: "26ch", color: "#FFFFFF", fontStyle: "var(--in-mewe-4)", width: "800px" }}>
              {t("022_p")}
            </p>
          </div>
        </section>
        {/* 3 · MEWE LOOP */}
        <section data-screen-label="3 The MEWE Loop" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              {t("023_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-mewe-5)", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              {t("024_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", maxWidth: "720px", margin: "0 0 34px", color: "rgba(46,59,64,0.82)" }}>
              {t("025_p")}
            </p>
            <div style={{ overflow: "hidden", margin: "0 0 34px" }}>
              <img src="/team/mewe-arc-strip.png" alt={t("026_alt")} style={{ display: "block", width: "calc(100% + 8px)", height: "auto", marginTop: "-8px", marginLeft: "-8px" }} />
            </div>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  {t("027_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5" }}>
                  {t("028_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  {t("029_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5" }}>
                  {t("030_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  {t("031_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5" }}>
                  {t("032_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  {t("033_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5" }}>
                  {t("034_div")}
                  <span style={{ color: "#1C6E92", fontStyle: "var(--in-mewe-6)" }}>
                    {t("035_span")}
                  </span>
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  {t("036_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5" }}>
                  {t("037_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", borderBottom: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  {t("038_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5" }}>
                  {t("039_div")}
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* DIVIDER · WHY IT MATTERS */}
        <section data-screen-label="Why It Matters" style={{ background: "#1C6E92", color: "#FFFFFF", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 48px", backgroundColor: "#1C6E92" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "#FFFFFF", marginBottom: "24px" }}>
              {t("040_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.4vw, 44px)", lineHeight: "var(--in-mewe-7)", margin: "0 0 26px", maxWidth: "26ch", letterSpacing: "-0.01em", textWrap: "pretty", color: "#FFFFFF" }}>
              {t("041_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(20px, 2.2vw, 26px)", lineHeight: "1.35", margin: "0", maxWidth: "640px", color: "rgba(255,255,255,0.88)", fontWeight: "500", fontStyle: "var(--in-mewe-8)" }}>
              {t("042_p")}
            </p>
          </div>
        </section>
        {/* 5 · ACTION RESEARCH */}
        <section data-screen-label="5 Action Research" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              {t("043_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-mewe-9)", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              {t("044_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 40px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("045_p")}
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "18px", alignItems: "stretch" }}>
              <article style={{ display: "flex", flexDirection: "column", background: "#FAF4E2", border: "1px solid rgba(26,22,19,0.14)", color: "#2E3B40" }}>
                <div style={{ position: "relative", width: "100%", height: "132px", overflow: "hidden", background: "#1E8A86" }}>
                  <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "240px" }}>
                    <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(18% 100%, 30% 12%, 46% 100%)" }} />
                  </div>
                </div>
                <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", minHeight: "200px", padding: "22px 24px 20px 50px" }}>
                  <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1C6E92" }} />
                    <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "#1C6E92" }}>
                      {t("046_span")}
                    </span>
                  </div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 0 8px" }}>
                    {t("047_div")}
                  </div>
                  <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "30px", lineHeight: "var(--in-mewe-10)", margin: "0 0 10px" }}>
                    {t("048_h3")}
                  </h3>
                  <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                    {t("049_p")}
                  </p>
                  <div style={{ marginTop: "auto", display: "flex", justifyContent: "flex-end", paddingTop: "22px" }}>
                    <Link to={localize("/action-research", locale)} aria-label={t("050_aria-label")} style={{ flex: "0 0 auto", width: "44px", height: "44px", borderRadius: "50%", background: "#2E3B40", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontSize: "20px", color: "#FAF4E2", textDecoration: "none" }} className="in-plain">
                      →
                    </Link>
                  </div>
                </div>
              </article>
              <article style={{ display: "flex", flexDirection: "column", background: "#FAF4E2", border: "1px solid rgba(26,22,19,0.14)", color: "#2E3B40" }}>
                <div style={{ position: "relative", width: "100%", height: "132px", overflow: "hidden", background: "#1E648C" }}>
                  <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "240px" }}>
                    <div style={{ position: "absolute", inset: "0", background: "#1E8A86", clipPath: "polygon(100% 100%, 100% 34%, 30% 100%)", mixBlendMode: "multiply" }} />
                  </div>
                </div>
                <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", minHeight: "200px", padding: "22px 24px 20px 50px" }}>
                  <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1C6E92" }} />
                    <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "#1C6E92" }}>
                      {t("051_span")}
                    </span>
                  </div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 0 8px" }}>
                    {t("052_div")}
                  </div>
                  <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "30px", lineHeight: "var(--in-mewe-11)", margin: "0 0 10px" }}>
                    {t("053_h3")}
                  </h3>
                  <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                    {t("054_p")}
                  </p>
                  <div style={{ marginTop: "auto", display: "flex", justifyContent: "flex-end", paddingTop: "22px" }}>
                    <Link to={localize("/action-research", locale)} aria-label={t("055_aria-label")} style={{ flex: "0 0 auto", width: "44px", height: "44px", borderRadius: "50%", background: "#2E3B40", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontSize: "20px", color: "#FAF4E2", textDecoration: "none" }} className="in-plain">
                      →
                    </Link>
                  </div>
                </div>
              </article>
              <article style={{ display: "flex", flexDirection: "column", background: "#FAF4E2", border: "1px solid rgba(26,22,19,0.14)", color: "#2E3B40" }}>
                <div style={{ position: "relative", width: "100%", height: "132px", overflow: "hidden", background: "#D21E28" }}>
                  <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "240px" }}>
                    <div style={{ position: "absolute", inset: "0", background: "#FAB414", clipPath: "polygon(0 100%, 0 40%, 54% 100%)" }} />
                    <div style={{ position: "absolute", inset: "0", background: "#F05A28", clipPath: "polygon(100% 100%, 100% 18%, 58% 100%)" }} />
                  </div>
                </div>
                <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", minHeight: "200px", padding: "22px 24px 20px 50px" }}>
                  <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1C6E92" }} />
                    <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "#1C6E92" }}>
                      {t("056_span")}
                    </span>
                  </div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 0 8px" }}>
                    {t("057_div")}
                  </div>
                  <h3 style={{ fontFamily: "var(--font-serif)", fontWeight: "700", fontSize: "30px", lineHeight: "var(--in-mewe-12)", margin: "0 0 10px" }}>
                    {t("058_h3")}
                  </h3>
                  <p style={{ fontFamily: "var(--font-serif)", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                    {t("059_p")}
                  </p>
                  <div style={{ marginTop: "auto", display: "flex", justifyContent: "flex-end", paddingTop: "22px" }}>
                    <Link to={localize("/action-research", locale)} aria-label={t("060_aria-label")} style={{ flex: "0 0 auto", width: "44px", height: "44px", borderRadius: "50%", background: "#2E3B40", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontSize: "20px", color: "#FAF4E2", textDecoration: "none" }} className="in-plain">
                      →
                    </Link>
                  </div>
                </div>
              </article>
            </div>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "18px", lineHeight: "1.55", margin: "40px 0 0", maxWidth: "900px", color: "rgba(46,59,64,0.78)", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "28px" }}>
              {t("061_p")}
              <Link to={localize("/action-research", locale)}>
                {t("062_a")}
              </Link>
            </p>
          </div>
        </section>
        {/* 6 · MEWE PRACTICE */}
        <section data-screen-label="6 MEWE Practice" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              {t("063_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-mewe-13)", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              {t("064_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", maxWidth: "720px", margin: "0", color: "rgba(46,59,64,0.82)" }}>
              {t("065_p")}
              <Link to={localize("/story", locale)}>
                {t("066_a")}
              </Link>
              {t("067_p")}
            </p>
          </div>
        </section>
        {/* 7 · WHERE IT BEGAN */}
        <section data-screen-label="7 Where It Began" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              {t("068_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-mewe-14)", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              {t("069_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 18px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("070_p")}
            </p>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 44px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("071_p")}
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1.5px", background: "rgba(46,59,64,0.16)", border: "1.5px solid rgba(46,59,64,0.16)", maxWidth: "1000px" }}>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  2015
                </div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  {t("072_div")}
                </div>
              </div>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  5
                </div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  {t("073_div")}
                </div>
              </div>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  650+
                </div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  {t("074_div")}
                </div>
              </div>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  {t("075_div")}
                </div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  {t("076_div")}
                </div>
              </div>
            </div>
            <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-mewe-15)", fontSize: "18px", lineHeight: "1.5", margin: "16px 0 0", color: "rgba(46,59,64,0.62)" }}>
              {t("077_p")}
            </p>
          </div>
        </section>
        {/* CTA */}
        <section data-screen-label="CTA" style={{ background: "#1E648C", color: "#FAF4E2", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("078_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "var(--in-mewe-16)", margin: "0 0 30px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("079_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/workshop/mobius-making", locale)} style={{ textDecoration: "none", color: "#1E8A86", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("080_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("081_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
