import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import './MEWEEN.css';

/** MEWE.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function MEWEEN() {
  return (
    <SiteLayout lang="EN" page="MEWE.EN.dc.html" className="page-meween" footer={{ loop: "0.126", cta: "#1E648C" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (locked) */}
        <section data-screen-label="Hero" style={{ background: "#1E648C", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#FAF4E2", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#FAF4E2" }}>
                MEWE
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "18ch", textWrap: "balance" }}>
              What if ME and WE were never actually two things?
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(30px, 3.6vw, 50px)", lineHeight: "1.0", margin: "0", letterSpacing: "-0.01em", color: "#F0D23C" }}>
              They Never Were. One path. No sides.
            </p>
          </div>
        </section>
        {/* INTRO STATEMENT */}
        <section data-screen-label="The pattern" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.3", margin: "0", maxWidth: "900px", color: "#1A1613" }}>
            MEWE names a pattern already at work — between us, within us, through us. Not a belief to adopt. Something to notice, and then to live.
          </p>
        </section>
        {/* 1 · MEWE RELATIONSHIP */}
        <section data-screen-label="1 MEWE Relationship" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              MEWE Relationship
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontStyle: "italic", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.1", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "pretty", color: "#1C6E92" }}>
              Relationships are not something we create. They are something we are already inside.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 18px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              It is natural to feel separate at times. In teams, when collaboration feels strained. In families, when misunderstanding lingers. In communities, when alignment feels fragile. Even within ourselves. Given the complexity of modern life, this sense of separation makes sense.
            </p>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              And yet, something else is also quietly true — we are constantly influencing one another. A tone changes the atmosphere. A gesture softens tension. A single decision reshapes a conversation.
            </p>
          </div>
        </section>
        {/* 2 · NATURE ALREADY KNOWS */}
        <section data-screen-label="2 Nature already knows" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              Nature Already Knows
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              Life reflects the MEWE pattern.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 40px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              It draws attention to a pattern we have had blind spots for — one that living systems have been running all along.
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "26px" }}>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  DNA
                </div>
                <ImageSlot id="mewe-dna" shape="rect" placeholder="DNA — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  Strands appear separate, yet neither sustains life alone.
                </p>
              </div>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  Nervous systems
                </div>
                <ImageSlot id="mewe-nervous" shape="rect" placeholder="Nervous systems — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  Signals travel a shared network, not a solitary line.
                </p>
              </div>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  Forest roots
                </div>
                <ImageSlot id="mewe-roots" shape="rect" placeholder="Forest roots — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  Trees trade nutrients underground long before we noticed.
                </p>
              </div>
              <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px", display: "flex", flexDirection: "column", gap: "16px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#1C6E92" }}>
                  Ecosystems
                </div>
                <ImageSlot id="mewe-ecosystems" shape="rect" placeholder="Ecosystems — photo or illustration" style={{ display: "block", width: "100%", aspectRatio: "16 / 9" }} />
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.42", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                  Thrive through interdependence, not isolation.
                </p>
              </div>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(22px, 2.4vw, 28px)", lineHeight: "1.32", margin: "40px 0 0", maxWidth: "760px", color: "#1E648C", textWrap: "pretty" }}>
              {"This isn't a new idea. "}
              <span style={{ color: "#1C6E92" }}>
                Nature has always shown it to us.
              </span>
            </p>
          </div>
        </section>
        {/* DIVIDER · THE MÖBIUS FLIP */}
        <section data-screen-label="The Möbius Flip" style={{ background: "#1C6E92", color: "#FFFFFF", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 48px", backgroundColor: "#1C6E92" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "#FFFFFF", marginBottom: "22px" }}>
              The Möbius Flip
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(28px, 3.4vw, 30px)", lineHeight: "1.2", margin: "0", maxWidth: "26ch", color: "#FFFFFF", fontStyle: "italic", width: "800px" }}>
              We picture “self” and “society” as two sides, facing away from each other. MEWE is the flip — the moment you let go of the orientation you started with, and see they were never fully separate.
            </p>
          </div>
        </section>
        {/* 3 · MEWE LOOP */}
        <section data-screen-label="3 The MEWE Loop" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              The MEWE Loop
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              Six stages, lived rather than learned.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", maxWidth: "720px", margin: "0 0 34px", color: "rgba(46,59,64,0.82)" }}>
              If this pattern is already operating, what changes when we become conscious of it? MEWE unfolds through practice — not as a theory, but as something lived, across six stages.
            </p>
            <div style={{ overflow: "hidden", margin: "0 0 34px" }}>
              <img src="/team/mewe-arc-strip.png" alt="MEWE Loop — IGNITE, ME≠WE, ME+WE, (ME WE), ME=WE, GLOW" style={{ display: "block", width: "calc(100% + 8px)", height: "auto", marginTop: "-8px", marginLeft: "-8px" }} />
            </div>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  IGNITE
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5" }}>
                  Willing to turn toward my higher self, willing to look.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  ME ≠ WE
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5" }}>
                  Still inside my own story.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  ME + WE
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5" }}>
                  Beginning to notice the web that holds ME and WE.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  (ME WE)
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5" }}>
                  {"Flipping to connect, a door opens: we see together, and something new emerges. "}
                  <span style={{ color: "#1C6E92", fontStyle: "italic" }}>
                    This is the shift.
                  </span>
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  ME = WE
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5" }}>
                  Moving in the relational field, our thoughts, words, and actions ripple outward — shaping the collective flow.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", borderBottom: "1.5px solid rgba(46,59,64,0.18)", padding: "20px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "30px", color: "#1C6E92" }}>
                  GLOW
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5" }}>
                  Learning to keep moving, we co-create and co-evolve — toward the whole.
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* DIVIDER · WHY IT MATTERS */}
        <section data-screen-label="Why It Matters" style={{ background: "#1C6E92", color: "#FFFFFF", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 48px", backgroundColor: "#1C6E92" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "#FFFFFF", marginBottom: "24px" }}>
              Why It Matters
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(28px, 3.4vw, 44px)", lineHeight: "1.1", margin: "0 0 26px", maxWidth: "26ch", letterSpacing: "-0.01em", textWrap: "pretty", color: "#FFFFFF" }}>
              Individual action does not remain individual. It shapes relationships. Relationships shape shared patterns. Shared patterns shape communities.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "clamp(20px, 2.2vw, 26px)", lineHeight: "1.35", margin: "0", maxWidth: "640px", color: "rgba(255,255,255,0.88)", fontWeight: "500", fontStyle: "italic" }}>
              Community transformation is not manufactured — it unfolds through participation. Change is rarely sustained through force. It emerges through relational alignment.
            </p>
          </div>
        </section>
        {/* 5 · ACTION RESEARCH */}
        <section data-screen-label="5 Action Research" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              Action Research
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              We keep testing the framework in practice.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 40px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              MEWE is a working hypothesis, refined through every workshop, project, and neighbor story — evidence about what actually shifts between people, gathered as we practice.
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "18px", alignItems: "stretch" }}>
              <article style={{ display: "flex", flexDirection: "column", background: "#FAF4E2", border: "1px solid rgba(26,22,19,0.14)", color: "#2E3B40" }}>
                <div style={{ position: "relative", width: "100%", height: "132px", overflow: "hidden", background: "#1E8A86" }}>
                  <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "240px" }}>
                    <div style={{ position: "absolute", inset: "0", background: "#F0D23C", clipPath: "polygon(18% 100%, 30% 12%, 46% 100%)" }} />
                  </div>
                </div>
                <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", minHeight: "200px", padding: "22px 24px 20px 50px" }}>
                  <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1C6E92" }} />
                    <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "#1C6E92" }}>
                      Research
                    </span>
                  </div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 0 8px" }}>
                    In practice
                  </div>
                  <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "700", fontSize: "30px", lineHeight: "1", margin: "0 0 10px" }}>
                    Every studio is an experiment
                  </h3>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                    The six-stage Loop tested against real rooms, then adjusted from what we observe.
                  </p>
                  <div style={{ marginTop: "auto", display: "flex", justifyContent: "flex-end", paddingTop: "22px" }}>
                    <Link to="/action-research" aria-label="Read the research" style={{ flex: "0 0 auto", width: "44px", height: "44px", borderRadius: "50%", background: "#2E3B40", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontSize: "20px", color: "#FAF4E2", textDecoration: "none" }} className="in-plain">
                      →
                    </Link>
                  </div>
                </div>
              </article>
              <article style={{ display: "flex", flexDirection: "column", background: "#FAF4E2", border: "1px solid rgba(26,22,19,0.14)", color: "#2E3B40" }}>
                <div style={{ position: "relative", width: "100%", height: "132px", overflow: "hidden", background: "#1E648C" }}>
                  <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "240px" }}>
                    <div style={{ position: "absolute", inset: "0", background: "#1E8A86", clipPath: "polygon(100% 100%, 100% 34%, 30% 100%)", mixBlendMode: "multiply" }} />
                  </div>
                </div>
                <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", minHeight: "200px", padding: "22px 24px 20px 50px" }}>
                  <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1C6E92" }} />
                    <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "#1C6E92" }}>
                      Research
                    </span>
                  </div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 0 8px" }}>
                    Across fields
                  </div>
                  <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "700", fontSize: "30px", lineHeight: "1", margin: "0 0 10px" }}>
                    Kept honest by many disciplines
                  </h3>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                    Relational science, systems thinking, art, and ecology — not a single discipline's claim.
                  </p>
                  <div style={{ marginTop: "auto", display: "flex", justifyContent: "flex-end", paddingTop: "22px" }}>
                    <Link to="/action-research" aria-label="Read the research" style={{ flex: "0 0 auto", width: "44px", height: "44px", borderRadius: "50%", background: "#2E3B40", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontSize: "20px", color: "#FAF4E2", textDecoration: "none" }} className="in-plain">
                      →
                    </Link>
                  </div>
                </div>
              </article>
              <article style={{ display: "flex", flexDirection: "column", background: "#FAF4E2", border: "1px solid rgba(26,22,19,0.14)", color: "#2E3B40" }}>
                <div style={{ position: "relative", width: "100%", height: "132px", overflow: "hidden", background: "#D21E28" }}>
                  <div style={{ position: "absolute", left: "0", right: "0", bottom: "0", height: "240px" }}>
                    <div style={{ position: "absolute", inset: "0", background: "#FAB414", clipPath: "polygon(0 100%, 0 40%, 54% 100%)" }} />
                    <div style={{ position: "absolute", inset: "0", background: "#F05A28", clipPath: "polygon(100% 100%, 100% 18%, 58% 100%)" }} />
                  </div>
                </div>
                <div style={{ position: "relative", display: "flex", flexDirection: "column", flex: "1", minHeight: "200px", padding: "22px 24px 20px 50px" }}>
                  <div style={{ position: "absolute", left: "13px", top: "21px", display: "flex", flexDirection: "column", alignItems: "center", gap: "9px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#1C6E92" }} />
                    <span style={{ writingMode: "vertical-rl", whiteSpace: "nowrap", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "#1C6E92" }}>
                      Research
                    </span>
                  </div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#2E3B40", margin: "0 0 8px" }}>
                    Shared back
                  </div>
                  <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "700", fontSize: "30px", lineHeight: "1", margin: "0 0 10px" }}>
                    The network learns together
                  </h3>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.3", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                    What each IN-Collective learns returns to the network, so the framework grows through many hands.
                  </p>
                  <div style={{ marginTop: "auto", display: "flex", justifyContent: "flex-end", paddingTop: "22px" }}>
                    <Link to="/action-research" aria-label="Read the research" style={{ flex: "0 0 auto", width: "44px", height: "44px", borderRadius: "50%", background: "#2E3B40", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontSize: "20px", color: "#FAF4E2", textDecoration: "none" }} className="in-plain">
                      →
                    </Link>
                  </div>
                </div>
              </article>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.55", margin: "40px 0 0", maxWidth: "900px", color: "rgba(46,59,64,0.78)", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "28px" }}>
              {"Shared through peer-reviewed work and international forums: a Springer handbook chapter, “Self, Society, Service in MEWE” (2024); “Co-Designing a Pathway Through Food Revolution for Social Change” (2021); “Co-designing a social innovation model for changemakers” (2018); and a youth-empowerment case study (Banff / RSD, 2015). Presented at Dubai EXPO 2020 and the Parliament of the World's Religions 2022. "}
              <Link to="/action-research">
                Read the full research →
              </Link>
            </p>
          </div>
        </section>
        {/* 6 · MEWE PRACTICE */}
        <section data-screen-label="6 MEWE Practice" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              MEWE Practice
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              MEWE is not a movement to join. It is a practice to live.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", maxWidth: "720px", margin: "0", color: "rgba(46,59,64,0.82)" }}>
              {"Something we've been testing since 2015 — our workshops exist to practice it together. We're also gathering a "}
              <Link to="/story">
                neighbor archive
              </Link>
              : how people express their own MEWE story, in whatever form it takes.
            </p>
          </div>
        </section>
        {/* 7 · WHERE IT BEGAN */}
        <section data-screen-label="7 Where It Began" style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1C6E92", marginBottom: "20px" }}>
              Where It Began
            </div>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.04", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              A personal need, folded into a strip of paper.
            </h2>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 18px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              MEWE emerged from a personal need — guiding design students through self-discovery, and connecting their practice to a larger purpose.
            </p>
            <p style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 44px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              The Möbius strip became its symbol: individual (ME) and community (WE) as one continuous surface. From that starting point, the framework opens an exploration of our relationships with the self, with others, and with the forces of energy that bind us all.
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1.5px", background: "rgba(46,59,64,0.16)", border: "1.5px solid rgba(46,59,64,0.16)", maxWidth: "1000px" }}>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  2015
                </div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  In practice since
                </div>
              </div>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  5
                </div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  Countries
                </div>
              </div>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  650+
                </div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  People engaged
                </div>
              </div>
              <div style={{ background: "#FAF4E2", padding: "22px 24px" }}>
                <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "40px", lineHeight: "1", color: "#1C6E92", marginBottom: "8px" }}>
                  All ages
                </div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)" }}>
                  Classrooms · communities · organizations
                </div>
              </div>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontSize: "18px", lineHeight: "1.5", margin: "16px 0 0", color: "rgba(46,59,64,0.62)" }}>
              Its simplicity and adaptability keep it accessible across age groups and cultural backgrounds.
            </p>
          </div>
        </section>
        {/* CTA */}
        <section data-screen-label="CTA" style={{ background: "#1E648C", color: "#FAF4E2", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.08", margin: "0 0 30px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              One path. No sides. Step into the work.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/workshop/mobius-making" style={{ textDecoration: "none", color: "#1E8A86", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                Start with Möbius Making
              </Link>
              <Link to="/connect" style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                Get involved
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
