import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/news.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/news.json';
import wordsko from '../i18n/resources/ko/pages/news.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import NewsGrid from '../components/cards/NewsGrid';
import { localize, useLocale } from '../lib/lang';
import './News.css';

/** News — one component for every language, generated by
 *  scripts/convert-pages.mjs from News.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/news.json; the
 *  line-heights that differ by language are custom properties in News.css.
 *  Edit the legacy pages, not this file. */
export default function News() {
  const t = usePageWords("news", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="News.EN.dc.html" className="page-news" footer={{ loop: "0.36", cta: "#966432" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        <span id="top" />
        {/* HERO */}
        <section style={{ background: "var(--color-tan)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.2em", textTransform: "uppercase" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "var(--in-news-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "15ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "720px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* INSIGHT */}
        <section style={{ maxWidth: "1320px", margin: "64px auto 0", padding: "0 28px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: "34px", alignItems: "center" }}>
            <img src="/community-img/news-fuller-quote-card.jpg" alt={t("003_alt")} style={{ display: "block", width: "100%", maxWidth: "420px", height: "auto" }} />
            <div>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "18px" }}>
                <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "var(--color-tan)" }} />
                <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.2em", textTransform: "uppercase", color: "var(--color-tan)" }}>
                  {t("004_span")}
                </span>
              </div>
              <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(24px, 2.8vw, 34px)", lineHeight: "1.24", margin: "0 0 18px", textWrap: "pretty" }}>
                {t("005_p")}
              </p>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)" }}>
                {t("006_div")}
              </div>
            </div>
          </div>
        </section>
        {/* NEWS GRID */}
        <section id="news" style={{ maxWidth: "1320px", margin: "64px auto 0", padding: "0 28px 12px" }}>
          <div style={{ marginBottom: "28px", borderTop: "2px solid var(--color-ink)", paddingTop: "24px" }}>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.4vw, 44px)", lineHeight: "var(--in-news-1)", margin: "0", letterSpacing: "-0.01em" }}>
              {t("007_h2")}
            </h2>
          </div>
          <NewsGrid feed="news" />
        </section>
        {/* BACK TO TOP */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 0" }}>
          <a href="#top" style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "14px 26px" }} className="in-plain">
            {t("008_a")}
          </a>
        </section>
        {/* CTA */}
        <section style={{ background: "var(--color-tan)", color: "var(--color-paper)", marginTop: "60px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("009_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "var(--in-news-2)", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("010_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-tan)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("011_a")}
              </Link>
              <Link to={localize("/community", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("012_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
