import { Fragment } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ProjectIndexRail from '../components/ProjectIndexRail';
import { sx } from '../lib/sx';
import useLogic from '../logic/ProjectUNCDocumentaryEN';
import './ProjectUNCDocumentaryEN.css';

/** Project-UNC-Documentary.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ProjectUNCDocumentaryEN() {
  const { gallery, lbCap, lbCount, lbImgStyle, lbSrc, nextLb, prevLb, ready } = useLogic();

  return (
    <SiteLayout page="Project-UNC-Documentary.EN.dc.html" className="page-project-uncdocumentary-en" footer={{ loop: "0.557", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===== HERO ===== */}
        <section style={{ background: "#1E5A64", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 52px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "22px", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                Documentary film
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                Nepal
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                2017–2018
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "1.0", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              UNC Documentary
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              A camera followed Nepali youth for two years — not to record the program, but to see what held after it ended.
            </p>
          </div>
        </section>
        {/* ===== 3-COLUMN BODY ===== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 90px" }}>
          <div className="pj-grid" style={{ display: "grid", gridTemplateColumns: "226px 1fr 288px", gap: "40px", alignItems: "start" }}>
            {/* LEFT · about */}
            <aside className="pj-left col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderRight: "1px solid rgba(46,59,64,0.14)", paddingRight: "22px" }}>
              <Link to="/project" style={{ display: "inline-flex", alignItems: "center", gap: "8px", textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.13em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "26px" }} className="in-plain">
                &larr; All projects
              </Link>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                Format
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "22px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Documentary film
                </span>
              </div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                Topic
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "24px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Resilience
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Youth
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Social innovation
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "18px" }}>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Place
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    Kathmandu, Nepal
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Filmed
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    2017–2018
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Led by
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    Yunsun Chung, with Joanne Renaux &amp; Michael Ogden
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Part of
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    &ldquo;Designing for Social Innovation,&rdquo; Zayed University
                  </div>
                </div>
              </div>
            </aside>
            {/* MIDDLE · the story */}
            <div className="pj-mid">
              <figure style={{ margin: "0 0 40px" }}>
                <div style={{ width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#F3EAD0" }}>
                  <img src="/project-img/unc-documentary.jpg" alt="A young Nepali man being interviewed in a brick courtyard — the film crew seated behind the camera" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                </div>
                <figcaption style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)", marginTop: "12px" }}>
                  Filming began during the 2017 bootcamp and continued through the 2018 return to Kathmandu.
                </figcaption>
              </figure>
              <div style={{ maxWidth: "680px" }}>
                <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(26px, 3vw, 32px)", lineHeight: "1.32", letterSpacing: "-0.01em", margin: "0 0 34px", color: "#2E3B40", textWrap: "pretty" }}>
                  Filming began in 2017, while the bootcamp was still running. The idea was simple: rather than write up what happened, follow the young people and find out what lasted.
                </p>
                <div className="story-body">
                  <p>
                    It was one strand of a wider action research project, &ldquo;Designing for Social Innovation,&rdquo; based at Zayed University in Dubai &mdash; led by Yunsun Chung with Joanne Renaux and Michael Ogden.
                  </p>
                  <p>
                    A year later the team returned to Kathmandu. Some of the projects pitched at the bootcamp had become real. Some had stalled. Some had turned into something their founders never planned. The film follows those paths rather than the program that started them, because resilience is only visible over time &mdash; never on a closing day.
                  </p>
                </div>
                <blockquote style={{ margin: "40px 0", padding: "0 0 0 26px", borderLeft: "3px solid #1E5A64" }}>
                  <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontStyle: "italic", fontSize: "clamp(24px, 3vw, 30px)", lineHeight: "1.32", margin: "0", color: "#2E3B40", textWrap: "pretty" }}>
                    Resilience is only visible over time &mdash; never on a closing day.
                  </p>
                </blockquote>
                <div className="story-body">
                  <p>
                    That August 2018 return also brought everyone back together for a one-day reunion at The Inn Patan in Kathmandu: youth from every UNC year, saying where they&rsquo;d got to and what they still needed.
                  </p>
                </div>
                {/* GALLERY · embedded lightbox */}
                <div style={{ marginTop: "44px" }}>
                  <div style={{ position: "relative", aspectRatio: "16/9", background: "#16242E" }}>
                    {ready ? (
                      <>
                      <img src={lbSrc} alt={lbCap} style={sx(lbImgStyle)} />
                      </>
                    ) : null}
                    <button onClick={prevLb} aria-label="Previous photo" style={{ position: "absolute", left: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "'Archivo', sans-serif", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                      ‹
                    </button>
                    <button onClick={nextLb} aria-label="Next photo" style={{ position: "absolute", right: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "'Archivo', sans-serif", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                      ›
                    </button>
                  </div>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "14px", marginTop: "10px" }}>
                    <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)" }}>
                      {lbCap}
                    </span>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", color: "rgba(46,59,64,0.55)" }}>
                      {lbCount}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "8px", marginTop: "12px", overflowX: "auto", paddingBottom: "4px" }}>
                    {(gallery ?? []).map((g, gIndex) => (
                      <Fragment key={gIndex}>
                        <button onClick={g.open} aria-label={g.alt} style={sx(g.style)}>
                          <img src={g.src} alt="" loading="lazy" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                        </button>
                      </Fragment>
                    ))}
                  </div>
                </div>
                <div style={{ borderTop: "1.5px solid rgba(30,90,100,0.45)", marginTop: "44px", paddingTop: "30px" }}>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "20px" }}>
                    Watch
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "18px" }}>
                    <a href="https://youtu.be/d1J4AECO_9g" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "#2E3B40", display: "block" }} className="in-plain">
                      <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#1E5A64" }}>
                        <img src="https://img.youtube.com/vi/d1J4AECO_9g/hqdefault.jpg" alt="UNC documentary" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                        <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                            <span style={{ borderLeft: "15px solid #1E5A64", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                          </span>
                        </span>
                      </div>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                        The Documentary
                      </div>
                    </a>
                  </div>
                </div>
                <div style={{ marginTop: "40px" }}>
                  <Link to="/project/unc" style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                    Read the UNC project &rarr;
                  </Link>
                </div>
              </div>
            </div>
            {/* RIGHT · index */}
            <aside className="pj-right col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderLeft: "1px solid rgba(46,59,64,0.14)", paddingLeft: "22px" }}>
              <ProjectIndexRail current="unc-documentary" />
            </aside>
          </div>
        </section>
        {/* ===== CTA ===== */}
        <section style={{ background: "#1E5A64", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              What holds is only visible over time.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/connect" style={{ textDecoration: "none", color: "#1E5A64", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                Get involved
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
