import { Fragment } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ProjectIndexRail from '../components/ProjectIndexRail';
import { sx } from '../lib/sx';
import useLogic from '../logic/ProjectShadowShifterEN';
import './ProjectShadowShifterEN.css';

/** Project-Shadow-Shifter.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ProjectShadowShifterEN() {
  const { gallery, lbCap, lbCount, lbImgStyle, nextLb, prevLb, ready } = useLogic();

  return (
    <SiteLayout page="Project-Shadow-Shifter.EN.dc.html" className="page-project-shadow-shifter-en" footer={{ loop: "0.531", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===== HERO ===== */}
        <section style={{ background: "#1E5A64", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 52px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "22px", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                Nanzhi Center, Taiwan
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                Residential
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                June 2023
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "1.0", letterSpacing: "-0.02em", margin: "0 0 10px", textWrap: "balance" }}>
              Shadow Shifter
            </h1>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.8)", marginBottom: "22px" }}>
              Jungle Jam’s Taiwan chapter
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              Eighteen young people, two days, and one discovery: the shape of your own shadow can be changed by what you do.
            </p>
          </div>
        </section>
        {/* ===== 3-COLUMN BODY ===== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 90px" }}>
          <div className="pj-grid" style={{ display: "grid", gridTemplateColumns: "226px 1fr 288px", gap: "40px", alignItems: "start" }}>
            {/* LEFT · about */}
            <aside className="pj-left col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderRight: "1px solid rgba(46,59,64,0.14)", paddingRight: "22px" }}>
              <Link to="/project" style={{ display: "inline-flex", alignItems: "center", gap: "8px", textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.13em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "26px" }} className="in-plain">
                ← All projects
              </Link>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                Audience
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "22px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Youth (18–26)
                </span>
              </div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                Topic
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "24px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Retreat
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Transformation
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Facilitation
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "18px" }}>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Place
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    Nanzhi Center, Taiwan
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Dates
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    24–25 June 2023
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Participants
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)", lineHeight: "1.3" }}>
                    18 young people from across Taiwan
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Team
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)", lineHeight: "1.3" }}>
                    Lua Lo, Lin Zheng (Bibi), WanChi Zhao, with Taejin Kim &amp; Vahid Buehrer
                  </div>
                </div>
              </div>
            </aside>
            {/* MIDDLE · the story */}
            <div className="pj-mid">
              <figure style={{ margin: "0 0 40px" }}>
                <div style={{ width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#F3EAD0" }}>
                  <img src="/project-img/shadow-shifter.jpg" alt="Three young people holding hand-written cards and a LEGO model in front of the hand-drawn Shadow Shifter wall" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                </div>
                <figcaption style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)", marginTop: "12px" }}>
                  “Shadow Shifter — how might we become protagonists?” Nanzhi Center, June 2023.
                </figcaption>
              </figure>
              <div style={{ maxWidth: "680px" }}>
                <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 32px)", lineHeight: "1.32", letterSpacing: "-0.01em", margin: "0 0 34px", color: "#2E3B40", textWrap: "pretty" }}>
                  When an object finds light, it creates a shadow — and we can change the shape of our own shadow through our actions.
                </p>
                <div className="story-body">
                  <p>
                    Shadow Shifter began as a question asked in Taiwan: after a few workshops for young people and parents, could there be something longer — two days, residential, where youth had room to look honestly at themselves?
                  </p>
                  <p>
                    {"A temporary team formed to design it: three young people from Chiayi — Lua Lo, Lin Zheng (Bibi), and WanChi Zhao — working with Taejin Kim and Vahid Buehrer, adapting the "}
                    <Link to="/project/jungle-jam">
                      Jungle Jam
                    </Link>
                    {" workshop first run in Dubai the year before. Eighteen young people aged 18 to 26 came from across Taiwan and gathered at the Nanzhi Center on 24–25 June 2023."}
                  </p>
                  <p>
                    The frame was four words: light, shadow, shift, capacity. Nine challenges across two days, all of them hands-on. Meditative drawing, to notice the light and shadow qualities in other people. A mindful walk in the morning. Murals drawn straight onto the wall. A case clinic circle, where one person’s real challenge was listened to by everyone in the room. A role model built out of LEGO. And a letter each participant wrote to themselves.
                  </p>
                </div>
                <blockquote style={{ margin: "40px 0", padding: "0 0 0 26px", borderLeft: "3px solid #1E5A64" }}>
                  <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontStyle: "italic", fontSize: "clamp(24px, 3vw, 30px)", lineHeight: "1.32", margin: "0", color: "#2E3B40", textWrap: "pretty" }}>
                    “When an object finds light, it creates a shadow. And we can change the shape of our own shadow through our actions.”
                  </p>
                  <cite style={{ display: "block", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontStyle: "normal", fontSize: "13px", letterSpacing: "0.06em", textTransform: "uppercase", color: "rgba(46,59,64,0.6)", marginTop: "16px" }}>
                    A participant
                  </cite>
                </blockquote>
                <div className="story-body">
                  <p>
                    Some activities were deliberately handed to the youngest people on the team to co-facilitate — because facilitation is a capacity too, and it is learned by doing it.
                  </p>
                  <p>
                    What shifted afterwards was small and specific. One participant’s parents noticed he had started listening to them. Another wrote about failure, and about wanting to look at service without fear. One said: “In the past I could never be that leader. But in the atmosphere of that activity, I wanted to show myself, and become the person who leads.” Nearly everyone asked about helping to facilitate the next one.
                  </p>
                  <p>
                    They also said two days wasn’t enough.
                  </p>
                </div>
              </div>
              {/* GALLERY · embedded viewer */}
              <div style={{ marginTop: "44px" }}>
                <div style={{ position: "relative", aspectRatio: "16/9", background: "#16242E" }}>
                  {ready ? (
                    <>
                    <div role="img" aria-label={lbCap} style={sx(lbImgStyle)} />
                    </>
                  ) : null}
                  <button onClick={prevLb} aria-label="Previous photo" style={{ position: "absolute", left: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "'Archivo', sans-serif", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                    ‹
                  </button>
                  <button onClick={nextLb} aria-label="Next photo" style={{ position: "absolute", right: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "'Archivo', sans-serif", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                    ›
                  </button>
                </div>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "14px", marginTop: "10px" }}>
                  <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)" }}>
                    {lbCap}
                  </span>
                  <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", color: "rgba(46,59,64,0.55)" }}>
                    {lbCount}
                  </span>
                </div>
                <div style={{ display: "flex", gap: "8px", marginTop: "12px", overflowX: "auto", paddingBottom: "4px" }}>
                  {(gallery ?? []).map((g, gIndex) => (
                    <Fragment key={gIndex}>
                      <button onClick={g.open} aria-label={g.alt} style={sx(g.style)} />
                    </Fragment>
                  ))}
                </div>
              </div>
              <div style={{ maxWidth: "680px", borderTop: "1.5px solid rgba(30,90,100,0.45)", marginTop: "44px", paddingTop: "30px" }}>
                <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(24px, 2.8vw, 30px)", lineHeight: "1.3", margin: "0 0 26px", color: "#2E3B40", textWrap: "pretty" }}>
                  {"Shadow Shifter is Jungle Jam’s Taiwan chapter — "}
                  <span style={{ color: "#1E5A64" }}>
                    the same pattern, re-made by a different team, in a different place.
                  </span>
                </p>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "12px" }}>
                  One pattern, many forms
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px" }}>
                  <Link to="/project/shadow-shifter" style={{ textDecoration: "none", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "10px 18px" }} className="in-plain">
                    Shadow Shifter — Taiwan youth
                  </Link>
                  <Link to="/project/jungle-jam" style={{ textDecoration: "none", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.35)", borderRadius: "999px", padding: "10px 18px" }} className="in-plain">
                    Jungle Jam — UAE youth
                  </Link>
                  <Link to="/project/light-shadow-shift-womens-retreat" style={{ textDecoration: "none", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.35)", borderRadius: "999px", padding: "10px 18px" }} className="in-plain">
                    Women’s Retreat — UAE
                  </Link>
                </div>
              </div>
            </div>
            {/* RIGHT · index */}
            <aside className="pj-right col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderLeft: "1px solid rgba(46,59,64,0.14)", paddingLeft: "22px" }}>
              <ProjectIndexRail current="shadow-shifter" />
            </aside>
          </div>
        </section>
        {/* ===== CTA ===== */}
        <section style={{ background: "#1E5A64", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              A different team, in a different place — could be yours.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/connect" style={{ textDecoration: "none", color: "#1E5A64", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                Start a conversation
              </Link>
              <Link to="/protagonist" style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                See the Protagonist path
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
