import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/project.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/project.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import ProjectWall from '../components/cards/ProjectWall';
import { localize, useLocale } from '../lib/lang';
import './ProjectEN.css';

/** Project.EN.dc.html — generated by scripts/convert-pages.mjs. Serves /project and
 *  /zh-tw/project: this page's KO twin did not collapse into it, but
 *  zh-TW has no edition in site/ and reads this one. Its words are in
 *  src/i18n/resources/<locale>/pages/project.json.
 *  Edit the legacy page, or take this file over by hand and remove it from
 *  the converter's input. */
export default function ProjectEN() {
  const t = usePageWords("project", { "en": wordsen, "zh-TW": wordszhTW });
  const locale = useLocale();

  return (
    <SiteLayout page="Project.EN.dc.html" className="page-project-en" footer={{ loop: "0.489", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "15ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "720px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* FEATURED — ASIA EXCHANGE / BRIDGEBUILDER */}
        <section id="bridgebuilder" style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px 22px", scrollMarginTop: "80px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "1.05fr 1fr", alignItems: "stretch", background: "var(--color-magenta-hot)", color: "var(--color-paper)", overflow: "hidden", minHeight: "340px" }}>
            <div style={{ position: "relative", minHeight: "280px" }}>
              <ImageSlot id="project-asia-hero" shape="rect" placeholder="Young BridgeBuilders across a neighborhood, five-country feel" style={{ position: "absolute", inset: "0", width: "100%", height: "100%" }} src="https://images.unsplash.com/photo-1526976668912-1a811878dd37?auto=format&fit=crop&w=1100&q=80" credit="Photo by Hannah Busing on Unsplash" credit-href="https://unsplash.com/@hannahbusing" />
              <div style={{ position: "absolute", left: "16px", top: "16px", background: "var(--color-paper)", color: "var(--color-ink)", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", padding: "6px 12px" }}>
                {t("003_div")}
              </div>
            </div>
            <div style={{ padding: "40px 44px", display: "flex", flexDirection: "column", justifyContent: "space-between", gap: "24px" }}>
              <div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.8)", marginBottom: "16px" }}>
                  {t("004_div")}
                </div>
                <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(30px, 3.2vw, 46px)", lineHeight: "1.02", margin: "0 0 14px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {t("005_h2")}
                </h2>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.44", margin: "0 0 14px", color: "rgba(250,244,226,0.92)", maxWidth: "50ch" }}>
                  {t("006_p")}
                  <strong>
                    {t("007_strong")}
                  </strong>
                  {t("008_p")}
                </p>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.44", margin: "0", color: "rgba(250,244,226,0.8)", maxWidth: "50ch" }}>
                  {t("009_p")}
                  <Link to={localize("/pathway", locale)} style={{ color: "var(--color-paper)", textDecoration: "underline" }} className="in-plain">
                    {t("010_a")}
                  </Link>
                </p>
              </div>
              <Link to={localize("/project/asia-exchange", locale)} style={{ textDecoration: "none", alignSelf: "flex-start", display: "inline-flex", alignItems: "center", gap: "10px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", letterSpacing: "0.04em", color: "var(--color-magenta-hot)", background: "var(--color-paper)", borderRadius: "999px", padding: "13px 26px", lineHeight: "1.2" }} className="in-plain">
                {t("011_a")}
              </Link>
            </div>
          </div>
        </section>
        {/* PROJECT BRIEFS */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "20px 28px 20px" }}>
          <div style={{ borderTop: "1px solid rgba(46,59,64,0.14)", paddingTop: "26px", marginBottom: "20px" }}>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.0", margin: "0", letterSpacing: "-0.01em" }}>
              {t("012_h2")}
            </h2>
          </div>
          <ProjectWall />
          <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13.5px", color: "rgba(46,59,64,0.6)", margin: "22px 0 0", maxWidth: "60ch" }}>
            {t("013_p")}
            <Link to={localize("/community", locale)}>
              {t("014_a")}
            </Link>
            .
          </p>
        </section>
        {/* CTA */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("015_p")}
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("016_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-deepblue)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("017_a")}
              </Link>
              <Link to={localize("/pathway", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("018_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
