import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/project-asia-exchange.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/project-asia-exchange.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ProjectIndexRail from '../components/ProjectIndexRail';
import { localize, useLocale } from '../lib/lang';
import './ProjectAsiaExchangeEN.css';

/** Project-Asia-Exchange.EN.dc.html — generated by scripts/convert-pages.mjs. Serves /project/asia-exchange and
 *  /zh-tw/project/asia-exchange: this page's KO twin did not collapse into it, but
 *  zh-TW has no edition in site/ and reads this one. Its words are in
 *  src/i18n/resources/<locale>/pages/project-asia-exchange.json.
 *  Edit the legacy page, or take this file over by hand and remove it from
 *  the converter's input. */
export default function ProjectAsiaExchangeEN() {
  const t = usePageWords("project-asia-exchange", { "en": wordsen, "zh-TW": wordszhTW });
  const locale = useLocale();

  return (
    <SiteLayout page="Project-Asia-Exchange.EN.dc.html" className="page-project-asia-exchange-en" footer={{ loop: "0.478", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===== HERO ===== */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 52px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "22px", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "1.0", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* ===== 3-COLUMN BODY ===== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 90px" }}>
          <div className="pj-grid" style={{ display: "grid", gridTemplateColumns: "226px 1fr 288px", gap: "40px", alignItems: "start" }}>
            {/* LEFT · about */}
            <aside className="pj-left col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderRight: "1px solid rgba(46,59,64,0.14)", paddingRight: "22px" }}>
              <Link to={localize("/project", locale)} style={{ display: "inline-flex", alignItems: "center", gap: "8px", textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.13em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "26px" }} className="in-plain">
                {t("003_a")}
              </Link>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                {t("004_div")}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "22px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("005_span")}
                </span>
              </div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                {t("006_div")}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "24px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("007_span")}
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("008_span")}
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("009_span")}
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "18px" }}>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("010_div")}
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    {t("011_div")}
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("012_div")}
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    {t("013_div")}
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("014_div")}
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    {t("015_div")}
                  </div>
                </div>
              </div>
            </aside>
            {/* MIDDLE · the story */}
            <div className="pj-mid">
              <figure style={{ margin: "0 0 40px" }}>
                <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "var(--color-paper-dim)" }}>
                  <img src="/project-img/asia-exchange-key.png" alt={t("016_alt")} style={{ display: "block", width: "100%", height: "100%", objectFit: "cover", objectPosition: "50% 45%" }} />
                </div>
                <figcaption style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)", marginTop: "12px" }}>
                  {t("017_figcaption")}
                </figcaption>
              </figure>
              <div style={{ maxWidth: "680px" }}>
                <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(26px, 3vw, 32px)", lineHeight: "1.32", letterSpacing: "-0.01em", margin: "0 0 34px", color: "var(--color-ink)", textWrap: "pretty" }}>
                  {t("018_p")}
                </p>
                <div className="story-body">
                  <p>
                    {t("019_p")}
                  </p>
                  <p>
                    {t("020_p")}
                  </p>
                </div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-slate)", margin: "40px 0 18px" }}>
                  {t("021_div")}
                </div>
                <div className="story-body">
                  <p>
                    {t("022_p")}
                    <strong>
                      {t("023_strong")}
                    </strong>
                    {t("024_p")}
                  </p>
                </div>
              </div>
              {/* GLOBAL LABS */}
              <div style={{ marginTop: "44px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "22px", letterSpacing: "0.12em", lineHeight: "1.1", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                  {t("025_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5", margin: "0 0 26px", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  {t("026_p")}
                </p>
                <div className="pj-labs" style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "2px", background: "rgba(46,59,64,0.14)" }}>
                  <div style={{ background: "var(--color-slate)", padding: "22px 20px" }}>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "baseline", justifyContent: "space-between", marginBottom: "10px" }}>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-paper)" }}>
                        {t("027_div")}
                      </div>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(250,244,226,0.7)" }}>
                        {t("028_div")}
                      </div>
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "21px", lineHeight: "1.25", margin: "0 0 8px", color: "var(--color-paper)" }}>
                      {t("029_p")}
                    </p>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(250,244,226,0.88)" }}>
                      {t("030_p")}
                    </p>
                  </div>
                  <Link to={localize("/", locale)} target="_blank" rel="noopener" style={{ textDecoration: "none", background: "var(--color-paper)", padding: "22px 20px", display: "block" }}>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "baseline", justifyContent: "space-between", marginBottom: "10px" }}>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)" }}>
                        {t("031_div")}
                      </div>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)" }}>
                        {t("032_div")}
                      </div>
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "21px", lineHeight: "1.25", margin: "0 0 8px", color: "var(--color-ink)" }}>
                      {t("033_p")}
                    </p>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("034_p")}
                    </p>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", color: "var(--color-orange)", marginTop: "10px" }}>
                      {t("035_div")}
                    </div>
                  </Link>
                  <Link to={localize("/", locale)} target="_blank" rel="noopener" style={{ textDecoration: "none", background: "var(--color-paper)", padding: "22px 20px", display: "block" }}>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "baseline", justifyContent: "space-between", marginBottom: "10px" }}>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)" }}>
                        {t("036_div")}
                      </div>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)" }}>
                        {t("037_div")}
                      </div>
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "21px", lineHeight: "1.25", margin: "0 0 8px", color: "var(--color-ink)" }}>
                      {t("038_p")}
                    </p>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("039_p")}
                    </p>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", color: "var(--color-orange)", marginTop: "10px" }}>
                      {t("040_div")}
                    </div>
                  </Link>
                  <Link to={localize("/", locale)} target="_blank" rel="noopener" style={{ textDecoration: "none", background: "var(--color-paper)", padding: "22px 20px", display: "block" }}>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "baseline", justifyContent: "space-between", marginBottom: "10px" }}>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)" }}>
                        {t("041_div")}
                      </div>
                      <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)" }}>
                        {t("042_div")}
                      </div>
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "21px", lineHeight: "1.25", margin: "0 0 8px", color: "var(--color-ink)" }}>
                      {t("043_p")}
                    </p>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("044_p")}
                    </p>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", color: "var(--color-orange)", marginTop: "10px" }}>
                      {t("045_div")}
                    </div>
                  </Link>
                </div>
                <Link to={localize("/bridge-builder", locale)} style={{ marginTop: "22px", textDecoration: "none", display: "flex", flexWrap: "wrap", gap: "14px 20px", alignItems: "center", justifyContent: "space-between", background: "var(--color-orange)", color: "var(--color-paper)", padding: "26px 28px" }} className="in-plain">
                  <div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.8)", marginBottom: "8px" }}>
                      {t("046_div")}
                    </div>
                    <div style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.8vw, 32px)", lineHeight: "1.1", letterSpacing: "-0.015em" }}>
                      {t("047_div")}
                    </div>
                  </div>
                  <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", whiteSpace: "nowrap" }}>
                    {t("048_span")}
                    <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-paper)", color: "var(--color-orange)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                      {t("049_span")}
                    </span>
                  </span>
                </Link>
              </div>
              {/* POP-UP LABS */}
              <div style={{ marginTop: "44px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "22px", letterSpacing: "0.12em", lineHeight: "1.1", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                  {t("050_div")}
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5", margin: "0 0 26px", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  {t("051_p")}
                  <b>
                    {t("052_b")}
                  </b>
                </p>
                <div className="pj-labs" style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "2px", background: "rgba(46,59,64,0.14)" }}>
                  <div style={{ background: "var(--color-paper)", padding: "22px 20px" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                      {t("053_div")}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("054_p")}
                    </p>
                  </div>
                  <div style={{ background: "var(--color-paper)", padding: "22px 20px" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                      {t("055_div")}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("056_p")}
                    </p>
                  </div>
                  <div style={{ background: "var(--color-paper)", padding: "22px 20px" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                      {t("057_div")}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("058_p")}
                    </p>
                  </div>
                  <div style={{ background: "var(--color-paper)", padding: "22px 20px" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                      {t("059_div")}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("060_p")}
                    </p>
                  </div>
                  <div style={{ background: "var(--color-paper)", padding: "22px 20px" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "10px" }}>
                      {t("061_div")}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                      {t("062_p")}
                    </p>
                  </div>
                  <div style={{ background: "var(--color-slate)", padding: "22px 20px", display: "flex", flexDirection: "column", justifyContent: "center" }}>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(250,244,226,0.7)", marginBottom: "10px" }}>
                      {t("063_div")}
                    </div>
                    <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "20px", lineHeight: "1.3", margin: "0", color: "var(--color-paper)" }}>
                      {t("064_p")}
                    </p>
                  </div>
                </div>
              </div>
              <div style={{ maxWidth: "680px", marginTop: "44px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "18px" }}>
                  {t("065_div")}
                </div>
                <div className="story-body">
                  <p>
                    {t("066_p")}
                  </p>
                </div>
                <div style={{ borderTop: "1.5px solid rgba(30,90,100,0.45)", marginTop: "30px", paddingTop: "30px" }}>
                  <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(26px, 3.4vw, 34px)", lineHeight: "1.24", letterSpacing: "-0.015em", margin: "0", color: "var(--color-ink)", textWrap: "balance" }}>
                    {t("067_p")}
                    <span style={{ color: "var(--color-slate)" }}>
                      {t("068_span")}
                    </span>
                  </p>
                </div>
                <div style={{ marginTop: "34px" }}>
                  <Link to={localize("/pathway", locale)} style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "10px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "14px 28px", justifyContent: "center", lineHeight: "1.2" }} className="in-plain">
                    {t("069_a")}
                  </Link>
                </div>
              </div>
            </div>
            {/* RIGHT · index */}
            <aside className="pj-right col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderLeft: "1px solid rgba(46,59,64,0.14)", paddingLeft: "22px" }}>
              <ProjectIndexRail current="asia-exchange" />
            </aside>
          </div>
        </section>
        {/* ===== CTA ===== */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("070_p")}
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("071_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-slate)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("072_a")}
              </Link>
              <Link to={localize("/pathway", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("073_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
