import { Fragment } from 'react';
import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/project-unc-documentary.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/project-unc-documentary.json';
import wordsko from '../i18n/resources/ko/pages/project-unc-documentary.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ProjectIndexRail from '../components/ProjectIndexRail';
import { localize, useLocale } from '../lib/lang';
import { sx } from '../lib/sx';
import useLogic from '../logic/ProjectUNCDocumentary';
import './ProjectUNCDocumentary.css';

/** Project-UNC-Documentary — one component for every language, generated by
 *  scripts/convert-pages.mjs from Project-UNC-Documentary.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/project-unc-documentary.json; the
 *  line-heights that differ by language are custom properties in ProjectUNCDocumentary.css.
 *  Edit the legacy pages, not this file. */
export default function ProjectUNCDocumentary() {
  const t = usePageWords("project-unc-documentary", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();
  const { gallery, lbCap, lbCount, lbImgStyle, nextLb, prevLb, ready } = useLogic();

  return (
    <SiteLayout page="Project-UNC-Documentary.EN.dc.html" className="page-project-uncdocumentary" footer={{ loop: "0.557", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===== HERO ===== */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 52px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "22px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "12px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                {t("000_span")}
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                {t("001_span")}
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                2017–2018
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "var(--in-project-unc-documentary-0)", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              {t("002_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("003_p")}
            </p>
          </div>
        </section>
        {/* ===== 3-COLUMN BODY ===== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 90px" }}>
          <div className="pj-grid" style={{ display: "grid", gridTemplateColumns: "226px 1fr 288px", gap: "40px", alignItems: "start" }}>
            {/* LEFT · about */}
            <aside className="pj-left col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderRight: "1px solid rgba(46,59,64,0.14)", paddingRight: "22px" }}>
              <Link to={localize("/project", locale)} style={{ display: "inline-flex", alignItems: "center", gap: "8px", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.13em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "26px" }} className="in-plain">
                {t("004_a")}
              </Link>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                {t("005_div")}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "22px" }}>
                <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("006_span")}
                </span>
              </div>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                {t("007_div")}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "24px" }}>
                <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("008_span")}
                </span>
                <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("009_span")}
                </span>
                <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  {t("010_span")}
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "18px" }}>
                <div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("011_div")}
                  </div>
                  <div style={{ fontFamily: "var(--font-serif)", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    {t("012_div")}
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("013_div")}
                  </div>
                  <div style={{ fontFamily: "var(--font-serif)", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    2017–2018
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("014_div")}
                  </div>
                  <div style={{ fontFamily: "var(--font-serif)", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    {t("015_div")}
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "3px" }}>
                    {t("016_div")}
                  </div>
                  <div style={{ fontFamily: "var(--font-serif)", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    {t("017_div")}
                  </div>
                </div>
              </div>
            </aside>
            {/* MIDDLE · the story */}
            <div className="pj-mid">
              <figure style={{ margin: "0 0 40px" }}>
                <div style={{ width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "var(--color-paper-dim)" }}>
                  <img src="/project-img/unc-documentary.jpg" alt={t("018_alt")} style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                </div>
                <figcaption style={{ fontFamily: "var(--font-sans)", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)", marginTop: "12px" }}>
                  {t("019_figcaption")}
                </figcaption>
              </figure>
              <div style={{ maxWidth: "680px" }}>
                <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(26px, 3vw, 32px)", lineHeight: "1.32", letterSpacing: "-0.01em", margin: "0 0 34px", color: "var(--color-ink)", textWrap: "pretty" }}>
                  {t("020_p")}
                </p>
                <div className="story-body">
                  <p>
                    {t("021_p")}
                  </p>
                  <p>
                    {t("022_p")}
                  </p>
                </div>
                <blockquote style={{ margin: "40px 0", padding: "0 0 0 26px", borderLeft: "3px solid var(--color-slate)" }}>
                  <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontStyle: "italic", fontSize: "clamp(24px, 3vw, 30px)", lineHeight: "1.32", margin: "0", color: "var(--color-ink)", textWrap: "pretty" }}>
                    {t("023_p")}
                  </p>
                </blockquote>
                <div className="story-body">
                  <p>
                    {t("024_p")}
                  </p>
                </div>
                {/* GALLERY · embedded lightbox */}
                <div style={{ marginTop: "44px" }}>
                  <div style={{ position: "relative", aspectRatio: "16/9", background: "#16242E" }}>
                    {ready ? (
                      <>
                      <div role="img" aria-label={lbCap} style={sx(lbImgStyle)} />
                      </>
                    ) : null}
                    <button onClick={prevLb} aria-label={t("025_aria-label")} style={{ position: "absolute", left: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "var(--font-sans)", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                      ‹
                    </button>
                    <button onClick={nextLb} aria-label={t("026_aria-label")} style={{ position: "absolute", right: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "var(--font-sans)", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                      ›
                    </button>
                  </div>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "14px", marginTop: "10px" }}>
                    <span style={{ fontFamily: "var(--font-sans)", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)" }}>
                      {lbCap}
                    </span>
                    <span style={{ flex: "0 0 auto", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", color: "rgba(46,59,64,0.55)" }}>
                      {lbCount}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "8px", marginTop: "12px", overflowX: "auto", paddingBottom: "4px" }}>
                    {(gallery ?? []).map((g, gIndex) => (
                      <Fragment key={gIndex}>
                        <button onClick={g.open} aria-label={g.alt} style={sx(g.style)} />
                      </Fragment>
                    ))}
                  </div>
                </div>
                <div style={{ borderTop: "1.5px solid rgba(30,90,100,0.45)", marginTop: "44px", paddingTop: "30px" }}>
                  <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-slate)", marginBottom: "20px" }}>
                    {t("027_div")}
                  </div>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "18px" }}>
                    <a href="https://youtu.be/d1J4AECO_9g" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "var(--color-ink)", display: "block" }} className="in-plain">
                      <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "var(--color-slate)" }}>
                        <img src="https://img.youtube.com/vi/d1J4AECO_9g/hqdefault.jpg" alt={t("028_alt")} style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                        <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                            <span style={{ borderLeft: "15px solid var(--color-slate)", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                          </span>
                        </span>
                      </div>
                      <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                        {t("029_div")}
                      </div>
                    </a>
                  </div>
                </div>
                <div style={{ marginTop: "40px" }}>
                  <Link to={localize("/project/unc", locale)} style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "15px 32px", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                    {t("030_a")}
                  </Link>
                </div>
              </div>
            </div>
            {/* RIGHT · index */}
            <aside className="pj-right col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderLeft: "1px solid rgba(46,59,64,0.14)", paddingLeft: "22px" }}>
              <ProjectIndexRail current="unc-documentary" />
            </aside>
          </div>
        </section>
        {/* ===== CTA ===== */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("031_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("032_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-slate)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("033_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
