import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import ProjectWall from '../components/cards/ProjectWall';
import './ProjectKO.css';

/** Project.KO.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ProjectKO() {
  return (
    <SiteLayout page="Project.KO.dc.html" className="page-project-ko" footer={{ loop: "0.489", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                프로젝트
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "1.14", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "15ch", textWrap: "balance" }}>
              세상 밖으로 나간 실천.
            </h1>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "720px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              진짜 이웃과 함께하는 진짜 일 — 정원, 청년 캠프, 나라를 넘는 교류. MEWE가 아이디어이기를 멈추고 공동체가 가리킬 수 있는 무언가가 되는 곳.
            </p>
          </div>
        </section>
        {/* FEATURED — ASIA EXCHANGE / BRIDGEBUILDER */}
        <section id="bridgebuilder" style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px 22px", scrollMarginTop: "80px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "1.05fr 1fr", alignItems: "stretch", background: "var(--color-magenta)", color: "var(--color-paper)", overflow: "hidden", minHeight: "340px" }}>
            <div style={{ position: "relative", minHeight: "280px" }}>
              <ImageSlot id="project-asia-hero" shape="rect" placeholder="Young BridgeBuilders across a neighborhood, five-country feel" style={{ position: "absolute", inset: "0", width: "100%", height: "100%" }} src="https://images.unsplash.com/photo-1526976668912-1a811878dd37?auto=format&fit=crop&w=1100&q=80" credit="Photo by Hannah Busing on Unsplash" credit-href="https://unsplash.com/@hannahbusing" />
              <div style={{ position: "absolute", left: "16px", top: "16px", background: "var(--color-paper)", color: "var(--color-ink)", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", padding: "6px 12px" }}>
                대표 프로젝트 · 2026–2027
              </div>
            </div>
            <div style={{ padding: "40px 44px", display: "flex", flexDirection: "column", justifyContent: "space-between", gap: "24px" }}>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.8)", marginBottom: "16px" }}>
                  중국 · 일본 · 한국 · 네팔 · 대만
                </div>
                <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(30px, 3.2vw, 46px)", lineHeight: "1.16", margin: "0 0 14px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  MEWE 아시아 익스체인지
                </h2>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.44", margin: "0 0 14px", color: "rgba(250,244,226,0.92)", maxWidth: "50ch" }}>
                  <strong>
                    브리지빌더
                  </strong>
                  라 불리는 청년들이 자신의 동네에서 조화로운 공동체의 삶을 연습하는 국경을 넘는 프로그램 — 다섯 나라, 하나의 공유된 질문.
                </p>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "17px", lineHeight: "1.44", margin: "0", color: "rgba(250,244,226,0.8)", maxWidth: "50ch" }}>
                  {"브리지빌더는 실천의 길 위의 한 단계이기도 합니다 — "}
                  <Link to="/ko/protagonist" style={{ color: "var(--color-paper)", textDecoration: "underline" }} className="in-plain">
                    주역의 길에서 보기 →
                  </Link>
                </p>
              </div>
              <Link to="/project/asia-exchange" style={{ textDecoration: "none", alignSelf: "flex-start", display: "inline-flex", alignItems: "center", gap: "10px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", letterSpacing: "0.04em", color: "var(--color-magenta)", background: "var(--color-paper)", borderRadius: "999px", padding: "13px 26px", lineHeight: "1.2" }} className="in-plain">
                프로젝트 전체 읽기 →
              </Link>
            </div>
          </div>
        </section>
        {/* PROJECT BRIEFS */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "20px 28px 20px" }}>
          <div style={{ borderTop: "1px solid rgba(46,59,64,0.14)", paddingTop: "26px", marginBottom: "20px" }}>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.16", margin: "0", letterSpacing: "-0.01em" }}>
              프로젝트 브리프
            </h2>
          </div>
          <ProjectWall />
          <p style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "600", fontSize: "13.5px", color: "rgba(46,59,64,0.6)", margin: "22px 0 0", maxWidth: "60ch" }}>
            {"프로젝트와 그것이 만든 공동체는 같은 항목이 아닙니다 — 프로젝트는 개입이고, 공동체는 남는 것입니다. 둘 다 "}
            <Link to="/ko/community">
              커뮤니티
            </Link>
            에서 보실 수 있습니다.
          </p>
        </section>
        {/* CTA */}
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.18", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              당신의 공동체에 프로젝트를 가져오세요.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/ko/connect" style={{ textDecoration: "none", color: "var(--color-deepblue)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                대화 시작하기
              </Link>
              <Link to="/ko/protagonist" style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                주역의 길 보기
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
