import { Fragment } from 'react';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ProjectIndexRail from '../components/ProjectIndexRail';
import { sx } from '../lib/sx';
import useLogic from '../logic/ProjectUAEYouthSocialInnovationEN';
import './ProjectUAEYouthSocialInnovationEN.css';

/** Project-UAE-Youth-Social-Innovation.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ProjectUAEYouthSocialInnovationEN() {
  const { gallery, lbCap, lbCount, lbImgStyle, nextLb, prevLb, ready } = useLogic();

  return (
    <SiteLayout lang="EN" page="Project-UAE-Youth-Social-Innovation.EN.dc.html" className="page-project-uaeyouth-social-innovation-en" footer={{ loop: "0.534", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===== HERO ===== */}
        <section style={{ background: "#1E5A64", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 52px" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "22px", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                Workshop series
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                Sharjah, UAE
              </span>
              <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                2017
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "1.0", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              UAE Youth Social Innovation Workshop Series
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              Six months in which young people turned something they cared about into a social enterprise prototype — through seriously playful investigation.
            </p>
          </div>
        </section>
        {/* ===== 3-COLUMN BODY ===== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 90px" }}>
          <div className="pj-grid" style={{ display: "grid", gridTemplateColumns: "226px 1fr 288px", gap: "40px", alignItems: "start" }}>
            {/* LEFT · about */}
            <aside className="pj-left col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderRight: "1px solid rgba(46,59,64,0.14)", paddingRight: "22px" }}>
              <Link to="/project" style={{ display: "inline-flex", alignItems: "center", gap: "8px", textDecoration: "none", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12.5px", letterSpacing: "0.13em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "26px" }} className="in-plain">
                &larr; All projects
              </Link>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                Audience
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "22px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Youth
                </span>
              </div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(46,59,64,0.5)", marginBottom: "10px" }}>
                Topic
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginBottom: "24px" }}>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Social innovation
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Entrepreneurship
                </span>
                <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "6px 12px" }}>
                  Need-finding
                </span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "14px", borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "18px" }}>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Place
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    Sharjah, UAE · with Sheraa
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Year
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    2017 · six months
                  </div>
                </div>
                <div>
                  <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "3px" }}>
                    Participants
                  </div>
                  <div style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", color: "rgba(46,59,64,0.85)" }}>
                    38 registered · ~20 saw it through
                  </div>
                </div>
              </div>
            </aside>
            {/* MIDDLE · the story */}
            <div className="pj-mid" style={{ minWidth: "0" }}>
              <figure style={{ margin: "0 0 40px" }}>
                <div style={{ width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#F3EAD0" }}>
                  <img src="/project-img/UAE-Youth-Social-Innovation.jpg" alt="The full cohort of 38 young participants and facilitators at Sheraa, Sharjah" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                </div>
                <figcaption style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)", marginTop: "12px" }}>
                  The cohort at Sheraa, Sharjah &mdash; young people from across the UAE.
                </figcaption>
              </figure>
              <div style={{ maxWidth: "680px" }}>
                <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(26px, 3vw, 32px)", lineHeight: "1.32", letterSpacing: "-0.01em", margin: "0 0 34px", color: "#2E3B40", textWrap: "pretty" }}>
                  Over six months, in partnership with Sheraa, 38 young people across the UAE registered to turn something they cared about into a real social enterprise. About twenty saw it through to the end.
                </p>
                <div className="story-body">
                  <p>
                    Not by lecture. They worked through a series of workshops rooted in the MEWE framework and supported by systems thinking, design thinking, and appreciative inquiry &mdash; exploring their own identity, their relationships with self, society, and service, and where passion meets purpose.
                  </p>
                  <p>
                    Then they went out. Deep listening and conversations in their own communities came first &mdash; need-finding before ideas &mdash; then shaping what they heard into something, then testing it again and again with the people they hoped to serve. Most ideas changed several times before they held.
                  </p>
                  <p>
                    The support around them was its own lesson. INNOCO facilitators, like-minded individuals, and organizations gave their knowledge, expertise, and in-kind services freely, with no expectation of return.
                  </p>
                  <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(24px, 2.8vw, 30px)", lineHeight: "1.3", margin: "40px 0 0", color: "#2E3B40", textWrap: "pretty" }}>
                    {"What came out of it wasn&rsquo;t a set of assignments. "}
                    <span style={{ color: "#1E5A64" }}>
                      It was real prototypes, real pitches, and a group of young people who discovered they could build something.
                    </span>
                  </p>
                </div>
              </div>
              {/* GALLERY · embedded viewer */}
              <div style={{ marginTop: "44px" }}>
                <div style={{ position: "relative", aspectRatio: "16/9", background: "#16242E" }}>
                  {ready ? (
                    <>
                    <div role="img" aria-label={lbCap} style={sx(lbImgStyle)} />
                    </>
                  ) : null}
                  <button onClick={prevLb} aria-label="Previous photo" style={{ position: "absolute", left: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "'Archivo', sans-serif", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                    ‹
                  </button>
                  <button onClick={nextLb} aria-label="Next photo" style={{ position: "absolute", right: "12px", top: "50%", marginTop: "-22px", width: "44px", height: "44px", border: "none", borderRadius: "50%", background: "rgba(250,244,226,0.85)", color: "#16242E", fontFamily: "'Archivo', sans-serif", fontSize: "24px", lineHeight: "1", cursor: "pointer" }}>
                    ›
                  </button>
                </div>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: "14px", marginTop: "10px" }}>
                  <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", letterSpacing: "0.02em", color: "rgba(46,59,64,0.6)" }}>
                    {lbCap}
                  </span>
                  <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", color: "rgba(46,59,64,0.55)" }}>
                    {lbCount}
                  </span>
                </div>
                <div style={{ display: "flex", gap: "8px", marginTop: "12px", overflowX: "auto", paddingBottom: "4px" }}>
                  {(gallery ?? []).map((g, gIndex) => (
                    <Fragment key={gIndex}>
                      <button onClick={g.open} aria-label={g.alt} style={sx(g.style)} />
                    </Fragment>
                  ))}
                </div>
              </div>
              {/* WATCH */}
              <div style={{ maxWidth: "680px", borderTop: "1.5px solid rgba(30,90,100,0.45)", marginTop: "44px", paddingTop: "30px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "20px" }}>
                  Watch &mdash; the videos are their own
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }}>
                  <a href="https://youtu.be/Pl1IBR7fnTU" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "#2E3B40", display: "block" }} className="in-plain">
                    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#1E5A64" }}>
                      <img src="https://img.youtube.com/vi/Pl1IBR7fnTU/hqdefault.jpg" alt="Hasaad — a participant venture in organic food and farming, Dubai" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                      <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ borderLeft: "15px solid #1E5A64", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                        </span>
                      </span>
                    </div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                      Hasaad &mdash; a participant venture in organic food and farming, Dubai
                    </div>
                  </a>
                  <a href="https://youtu.be/Qwv9_7UkjAo" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "#2E3B40", display: "block" }} className="in-plain">
                    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#1E5A64" }}>
                      <img src="https://img.youtube.com/vi/Qwv9_7UkjAo/hqdefault.jpg" alt="Collect, Convert, Contribute — a circular-economy answer to food waste in the UAE" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                      <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ borderLeft: "15px solid #1E5A64", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                        </span>
                      </span>
                    </div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                      Collect, Convert, Contribute &mdash; a circular-economy answer to food waste in the UAE
                    </div>
                  </a>
                  <a href="https://youtu.be/C7yOhZdsoCI" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "#2E3B40", display: "block" }} className="in-plain">
                    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#1E5A64" }}>
                      <img src="https://img.youtube.com/vi/C7yOhZdsoCI/hqdefault.jpg" alt="Sustainable tech at home — saving water and energy without drastic lifestyle changes" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                      <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ borderLeft: "15px solid #1E5A64", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                        </span>
                      </span>
                    </div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                      Sustainable tech at home &mdash; saving water and energy without drastic lifestyle changes
                    </div>
                  </a>
                  <a href="https://youtu.be/HwG7iL8wGAA" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "#2E3B40", display: "block" }} className="in-plain">
                    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#1E5A64" }}>
                      <img src="https://img.youtube.com/vi/HwG7iL8wGAA/hqdefault.jpg" alt="Test before you build — validating business assumptions before investing resources" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                      <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ borderLeft: "15px solid #1E5A64", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                        </span>
                      </span>
                    </div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                      Test before you build &mdash; validating business assumptions before investing resources
                    </div>
                  </a>
                  <a href="https://youtu.be/CCCkqa3mOi4" target="_blank" rel="noopener" style={{ textDecoration: "none", color: "#2E3B40", display: "block" }} className="in-plain">
                    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9", overflow: "hidden", background: "#1E5A64" }}>
                      <img src="https://img.youtube.com/vi/CCCkqa3mOi4/hqdefault.jpg" alt="After the workshop series — participants reflect on the journey" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block", opacity: "0.9" }} />
                      <span style={{ position: "absolute", inset: "0", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ width: "52px", height: "52px", borderRadius: "50%", background: "rgba(250,244,226,0.94)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                          <span style={{ borderLeft: "15px solid #1E5A64", borderTop: "9px solid transparent", borderBottom: "9px solid transparent", marginLeft: "4px" }} />
                        </span>
                      </span>
                    </div>
                    <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", marginTop: "12px", lineHeight: "1.3" }}>
                      After the workshop series &mdash; participants reflect on the journey
                    </div>
                  </a>
                </div>
              </div>
              {/* CREDITS */}
              <div style={{ maxWidth: "680px", background: "#F3EAD0", padding: "34px 36px", marginTop: "44px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#1E5A64", marginBottom: "16px" }}>
                  With thanks
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.55", margin: "0 0 14px", color: "rgba(46,59,64,0.85)" }}>
                  Joanne Renaux, Aisha Khalid, Shirin Mehri, Sara Shedid, and Amina Al Marooei.
                </p>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.85)" }}>
                  {"And to invited social innovation and entrepreneurship experts "}
                  <strong>
                    Amin Matni
                  </strong>
                  {" and "}
                  <strong>
                    Petar Stojanov
                  </strong>
                  .
                </p>
              </div>
              <div style={{ maxWidth: "680px", marginTop: "40px" }}>
                <Link to="/community/uae-youth-cluster" style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                  See the UAE Youth Cluster &rarr;
                </Link>
              </div>
            </div>
            {/* RIGHT · index */}
            <aside className="pj-right col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderLeft: "1px solid rgba(46,59,64,0.14)", paddingLeft: "22px" }}>
              <ProjectIndexRail current="uae-youth" />
            </aside>
          </div>
        </section>
        {/* ===== CTA ===== */}
        <section style={{ background: "#1E5A64", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              Every practice began as one conversation.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/connect" style={{ textDecoration: "none", color: "#1E5A64", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                Get involved
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
