import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import './ProjectCTNKO.css';

/** Project-CTN.KO.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ProjectCTNKO() {
  return (
    <SiteLayout page="Project-CTN.KO.dc.html" className="page-project-ctnko" footer={{ loop: "0.648", cta: "#1E5A64" }}>
      <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        <section style={{ background: "var(--color-gold)", color: "var(--color-ink)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <Link to="/ko/project" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", textDecoration: "none", display: "inline-block", marginBottom: "28px" }} className="in-plain">
              ← 프로젝트 전체
            </Link>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "22px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12px", letterSpacing: "0.06em", textTransform: "uppercase" }}>
              <span style={{ background: "rgba(46,59,64,0.14)", borderRadius: "999px", padding: "8px 15px" }}>
                액션 리서치
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 76px)", lineHeight: "1.06", letterSpacing: "-0.02em", margin: "0 0 22px", textWrap: "balance" }}>
              체인지 더 나우(CTN)
            </h1>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(46,59,64,0.85)" }}>
              조지언 칼리지, 캐나다, 2021–23. ME=WE를 고등교육 현장으로 가져왔습니다 — 학생들이 언젠가가 아니라 지금을 바꾸는 일.
            </p>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "26px", letterSpacing: "0.14em", lineHeight: "1.1", textTransform: "uppercase", color: "var(--color-gold)", marginBottom: "24px" }}>
            프로젝트 브리프
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "22px", maxWidth: "1000px" }}>
            <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px" }}>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-gold)", marginBottom: "12px" }}>
                캠퍼스
              </div>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                대학의 교과와 학생 생활 안에 자리 잡았습니다.
              </p>
            </div>
            <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px" }}>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-gold)", marginBottom: "12px" }}>
                지금
              </div>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                변화를 미루지 않고 현재에서 실행합니다.
              </p>
            </div>
            <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", paddingTop: "16px" }}>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-gold)", marginBottom: "12px" }}>
                코호트
              </div>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                2년에 걸친 여러 학생 그룹.
              </p>
            </div>
          </div>
        </section>
        <section style={{ background: "var(--color-slate)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              Are You IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              모든 실천은 하나의 대화에서 시작했습니다.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/ko/connect" style={{ textDecoration: "none", color: "var(--color-teal)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                함께하기
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
