import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/protagonist.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/protagonist.json';
import wordsko from '../i18n/resources/ko/pages/protagonist.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import './Protagonist.css';

/** Protagonist — one component for every language, generated by
 *  scripts/convert-pages.mjs from Protagonist.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/protagonist.json; the
 *  line-heights that differ by language are custom properties in Protagonist.css.
 *  Edit the legacy pages, not this file. */
export default function Protagonist() {
  const t = usePageWords("protagonist", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Protagonist.EN.dc.html" className="page-protagonist" footer={{ loop: "0.466", cta: "#F05A28" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO ===================== */}
        <section style={{ background: "var(--color-orange)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(48px, 6.4vw, 96px)", lineHeight: "var(--in-protagonist-0)", letterSpacing: "-0.025em", margin: "0 0 22px", maxWidth: "14ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.3", maxWidth: "720px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* ===================== OPENING FRAMING ===================== */}
        <section style={{ maxWidth: "1320px", margin: "84px auto 0", padding: "0 28px" }}>
          <div style={{ maxWidth: "940px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "22px" }}>
              {t("003_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-protagonist-1)", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("004_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 34px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("005_p")}
            </p>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.12", letterSpacing: "-0.01em", margin: "0 0 24px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("006_p")}
              <span style={{ color: "var(--color-orange)" }}>
                {t("007_span")}
              </span>
            </p>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("008_p")}
            </p>
          </div>
        </section>
        {/* ===================== DEFINITION ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "20px" }}>
              {t("009_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-protagonist-2)", letterSpacing: "-0.01em", margin: "0 0 20px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("010_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 32px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("011_p")}
            </p>
            <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(22px, 2.4vw, 28px)", lineHeight: "1.32", margin: "0", maxWidth: "760px", color: "var(--color-ink)", textWrap: "pretty" }}>
              {t("012_p")}
            </p>
          </div>
        </section>
        {/* ===================== THE FOUR PATHS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "46px auto 0", padding: "0 28px" }}>
          <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
            {/* Path 1 */}
            <Link to={localize("/workshop", locale)} className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "var(--in-protagonist-3)", color: "rgba(46,59,64,0.28)" }}>
                1
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                  {t("013_div")}
                </div>
                <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "var(--in-protagonist-4)", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {t("014_h2")}
                </h2>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  {t("015_p")}
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                {t("016_span")}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  {t("017_span")}
                </span>
              </span>
            </Link>
            {/* Path 2 */}
            <Link to={localize("/connect", locale)} className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "var(--in-protagonist-5)", color: "rgba(46,59,64,0.28)" }}>
                2
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                  {t("018_div")}
                </div>
                <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "var(--in-protagonist-6)", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {t("019_h2")}
                </h2>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  {t("020_p")}
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                {t("021_span")}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  {t("022_span")}
                </span>
              </span>
            </Link>
            {/* Path 3 */}
            <Link to={localize("/workshop/pathfinder", locale)} className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "var(--in-protagonist-7)", color: "rgba(46,59,64,0.28)" }}>
                3
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                  {t("023_div")}
                </div>
                <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "var(--in-protagonist-8)", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {t("024_h2")}
                  <span style={{ color: "rgba(46,59,64,0.5)" }}>
                    {t("025_span")}
                  </span>
                </h2>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  {t("026_p")}
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                {t("027_span")}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  {t("028_span")}
                </span>
              </span>
            </Link>
            {/* Path 4 */}
            <Link to={localize("/connect", locale)} className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "var(--color-ink)", padding: "38px 40px", backgroundColor: "var(--color-paper)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "var(--in-protagonist-9)", color: "rgba(46,59,64,0.28)" }}>
                4
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "10px" }}>
                  {t("029_div")}
                </div>
                <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "var(--in-protagonist-10)", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {t("030_h2")}
                </h2>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  {t("031_p")}
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "var(--color-ink)" }}>
                {t("032_span")}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  {t("033_span")}
                </span>
              </span>
            </Link>
          </div>
        </section>
        {/* ===================== OPEN STUDIO (thread) ===================== */}
        <section style={{ maxWidth: "1320px", margin: "46px auto 0", padding: "0 28px" }}>
          <div style={{ background: "var(--color-paper-dim)", padding: "56px 52px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "40px", alignItems: "center" }}>
            <div>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "16px" }}>
                {t("034_div")}
              </div>
              <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.4vw, 46px)", lineHeight: "var(--in-protagonist-11)", letterSpacing: "-0.01em", margin: "0", textWrap: "balance", color: "var(--color-ink)" }}>
                {t("035_h2")}
              </h2>
            </div>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.85)" }}>
              {t("036_p")}
            </p>
          </div>
        </section>
        {/* ===================== STORY ENDING ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ maxWidth: "940px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-orange)", marginBottom: "20px" }}>
              {t("037_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(34px, 4.4vw, 58px)", lineHeight: "var(--in-protagonist-12)", letterSpacing: "-0.015em", margin: "0 0 22px", textWrap: "balance", color: "var(--color-ink)" }}>
              {t("038_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.55", margin: "0 0 26px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              {t("039_p")}
            </p>
            <Link to={localize("/story", locale)} style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "14px", letterSpacing: "0.04em", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "14px 28px" }} className="in-plain">
              {t("040_a")}
            </Link>
          </div>
        </section>
        {/* ===================== CTA BAND ===================== */}
        <section style={{ background: "var(--color-orange)", color: "var(--color-paper)", marginTop: "84px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("041_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "var(--in-protagonist-13)", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("042_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/workshop", locale)} style={{ textDecoration: "none", color: "var(--color-orange)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("043_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("044_a")}
              </Link>
            </div>
          </div>
        </section>
        {/* ===================== FOOTER ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
