import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import './ProtagonistKO.css';

/** Protagonist.KO.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function ProtagonistKO() {
  return (
    <SiteLayout lang="KO" page="Protagonist.KO.dc.html" className="page-protagonist-ko" footer={{ loop: "0.466", cta: "#F05A28" }}>
      <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO ===================== */}
        <section style={{ background: "#F05A28", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "32px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#FAF4E2", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#FAF4E2" }}>
                주역
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(48px, 6.4vw, 96px)", lineHeight: "1.12", letterSpacing: "-0.025em", margin: "0 0 22px", maxWidth: "14ch", textWrap: "balance" }}>
              여기에 구경꾼은 없습니다.
            </h1>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "400", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.3", maxWidth: "720px", margin: "0", color: "rgba(250,244,226,0.94)" }}>
              새로운 능력을 평범한 연결의 행동으로 바꾸는 스튜디오 — 한 번의 대화, 한 명의 이웃, 하나의 스토리씩.
            </p>
          </div>
        </section>
        {/* ===================== OPENING FRAMING ===================== */}
        <section style={{ maxWidth: "1320px", margin: "84px auto 0", padding: "0 28px" }}>
          <div style={{ maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#F05A28", marginBottom: "22px" }}>
              지금 이 순간
            </div>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.12", letterSpacing: "-0.01em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              이렇게 많은 사람이 이렇게 많은 것을 할 수 있었던 적은 없습니다.
            </h2>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 34px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              한때 평생이 걸리던 지식이 이제 한나절이면 도착합니다. 기관의 것이던 도구들이 이제 우리 손안에 있습니다. 한 나라의 누군가가 지구 반대편의 누군가와 점심 전에 나란히 배울 수 있습니다.
            </p>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.12", letterSpacing: "-0.01em", margin: "0 0 24px", textWrap: "balance", color: "#2E3B40" }}>
              {"그러나 우리 시대의 질문은 우리가 무엇을 할 수 있게 되었는가가 아닙니다. "}
              <span style={{ color: "#F05A28" }}>
                그것으로 무엇을 할 것인가입니다.
              </span>
            </p>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              IN은 바로 이 순간을 위해 만들어졌습니다. 능력에 감탄하기 위해서가 아니라, 그것으로 연습하기 위해 — 커진 능력을 평범하고 일상적인 연결의 행동으로 바꾸기 위해. 시작된 대화 하나. 알아차린 이웃 하나. 누군가 더 멀리 볼 수 있도록 들려준 스토리 하나.
            </p>
          </div>
        </section>
        {/* ===================== DEFINITION ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.16)", paddingTop: "42px", maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#F05A28", marginBottom: "20px" }}>
              주역이라는 말의 뜻
            </div>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "1.12", letterSpacing: "-0.01em", margin: "0 0 20px", textWrap: "balance", color: "#2E3B40" }}>
              리더도 전문가도 아닌 — 그저 구경하지 않기로 결심한 사람.
            </h2>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 32px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              IN을 거쳐 가는 모두는 저마다의 길을, 저마다의 깊이로 걷습니다. 등급도 자격 요건도 아닙니다. 얼마나 멀리 걷고 싶은지가 전부입니다.
            </p>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "500", fontSize: "clamp(22px, 2.4vw, 28px)", lineHeight: "1.32", margin: "0", maxWidth: "760px", color: "#2E3B40", textWrap: "pretty" }}>
              무료 워크숍 하나로 시작됩니다. 그 후 네 갈래 길이 열리고 — 모든 길은 같은 곳으로 돌아옵니다: 우리 모두에게 건네지는 하나의 스토리.
            </p>
          </div>
        </section>
        {/* ===================== THE FOUR PATHS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "46px auto 0", padding: "0 28px" }}>
          <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
            {/* Path 1 */}
            <Link to="/ko/workshop" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "#2E3B40", padding: "38px 40px", backgroundColor: "#FAF4E2", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "1.12", color: "rgba(46,59,64,0.28)" }}>
                1
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#F05A28", marginBottom: "10px" }}>
                  MEWE 탐험하기
                </div>
                <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.16", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  참여자
                </h2>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  워크숍을 마쳤다면, 이제 세상에서 시도해 봅니다: 가족, 친구, 이웃과 MEWE 대화를 시작하고, 오픈 스튜디오로 돌아와 다른 이들과 함께 연습합니다. 천천히 그것은 연습이기를 멈추고 살아가는 방식이 됩니다. 준비가 되면, 자신의 스토리를 써서 건네주세요.
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "#2E3B40" }}>
                {"워크숍 찾기 "}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "#2E3B40", color: "#FAF4E2", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  &rarr;
                </span>
              </span>
            </Link>
            {/* Path 2 */}
            <Link to="/ko/connect" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "#2E3B40", padding: "38px 40px", backgroundColor: "#FAF4E2", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "1.12", color: "rgba(46,59,64,0.28)" }}>
                2
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#F05A28", marginBottom: "10px" }}>
                  기여하며 배우기
                </div>
                <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.16", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  브리지 빌더
                </h2>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  요청으로 열리는 견습의 길. 자신의 관심과 목적을 확인하는 데서 시작해, 실제 IN 활동을 가까이에서 함께합니다 — 멘토 곁에서 디자인, 기술, 스토리텔링, 퍼실리테이션을 돕는 것. 자라나는 스토리의 몸에 기여하고, 진짜 경험과 수료증, 다음을 위한 추천서를 가지고 떠납니다.
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "#2E3B40" }}>
                {"브리지 빌더 지원하기 "}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "#2E3B40", color: "#FAF4E2", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  &rarr;
                </span>
              </span>
            </Link>
            {/* Path 3 */}
            <Link to="/ko/workshop/pathfinder" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "#2E3B40", padding: "38px 40px", backgroundColor: "#FAF4E2", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "1.12", color: "rgba(46,59,64,0.28)" }}>
                3
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#F05A28", marginBottom: "10px" }}>
                  인증 과정
                </div>
                <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.16", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {"퍼실리테이터 "}
                  <span style={{ color: "rgba(46,59,64,0.5)" }}>
                    (패스파인더)
                  </span>
                </h2>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  IN의 유일한 인증 프로그램. 패스파인더 시리즈를 통해 워크숍을 안에서부터 배우고, 우리와 함께 연습하며, 실천이 깊어질수록 오픈 스튜디오로 계속 돌아옵니다. MEWE 퍼실리테이터 자격을 얻은 뒤에는 직접 공간을 엽니다 — 자신의 맥락에서 워크숍을 진행하고, 때로는 새 워크숍을 만들면서.
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "#2E3B40" }}>
                {"패스파인더 워크숍 보기 "}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "#2E3B40", color: "#FAF4E2", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  &rarr;
                </span>
              </span>
            </Link>
            {/* Path 4 */}
            <Link to="/ko/connect" className="stage in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "96px 1fr auto", alignItems: "center", gap: "28px", color: "#2E3B40", padding: "38px 40px", backgroundColor: "#FAF4E2", border: "1.5px solid rgba(46,59,64,0.16)" }}>
              <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(48px, 6vw, 88px)", lineHeight: "1.12", color: "rgba(46,59,64,0.28)" }}>
                4
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.12em", textTransform: "uppercase", color: "#F05A28", marginBottom: "10px" }}>
                  온전한 파트너
                </div>
                <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(28px, 3.2vw, 42px)", lineHeight: "1.16", margin: "0 0 12px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  IN-콜렉티브
                </h2>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "clamp(18px, 1.9vw, 21px)", lineHeight: "1.46", margin: "0", maxWidth: "62ch", color: "rgba(46,59,64,0.82)" }}>
                  이 길은 대화로 시작됩니다: 지원, 인터뷰, 합의. 그때부터 당신은 스튜디오 그 자체의 일부입니다 — 워크숍을 개발하고, 함께 진행하고, 네트워크를 가로질러 협력하며, 자신의 공동체와 언어와 문화 안에서 IN의 일을 엽니다. 지부가 아니라 독립체로. 그리고 여전히 우리와 함께 오픈 스튜디오에.
                </p>
              </div>
              <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap", color: "#2E3B40" }}>
                {"대화 시작하기 "}
                <span style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "#2E3B40", color: "#FAF4E2", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  &rarr;
                </span>
              </span>
            </Link>
          </div>
        </section>
        {/* ===================== OPEN STUDIO (thread) ===================== */}
        <section style={{ maxWidth: "1320px", margin: "46px auto 0", padding: "0 28px" }}>
          <div style={{ background: "#F3EAD0", padding: "56px 52px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "40px", alignItems: "center" }}>
            <div>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#F05A28", marginBottom: "16px" }}>
                네 갈래 길을 꿰는 하나
              </div>
              <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(30px, 3.4vw, 46px)", lineHeight: "1.1", letterSpacing: "-0.01em", margin: "0", textWrap: "balance", color: "#2E3B40" }}>
                오픈 스튜디오.
              </h2>
            </div>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.85)" }}>
              어떤 길 위에 있든, 오픈 스튜디오는 모두가 돌아오는 곳입니다 — 성찰하고, 연습하고, 서로에게 묻기 위해. 네 갈래 길이 공유하는 단 하나의 방입니다.
            </p>
          </div>
        </section>
        {/* ===================== STORY ENDING ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ maxWidth: "940px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#F05A28", marginBottom: "20px" }}>
              모든 길의 끝은 같습니다
            </div>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(34px, 4.4vw, 58px)", lineHeight: "1.1", letterSpacing: "-0.015em", margin: "0 0 22px", textWrap: "balance", color: "#2E3B40" }}>
              당신이 스토리를 들려줍니다.
            </h2>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.55", margin: "0 0 26px", maxWidth: "720px", color: "rgba(46,59,64,0.82)" }}>
              무엇을 시도하든, 어디서 일어나든, 그것은 스토리가 되어 돌아옵니다 — 그리고 그 스토리들로 우리 모두는 무엇이 가능한지 배웁니다. 그것이 함께 만든다는 것입니다. 중심에서 조직되지 않고, 한 번의 기여씩 스스로 조직됩니다.
            </p>
            <Link to="/ko/story" style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", letterSpacing: "0.04em", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "14px 28px" }} className="in-plain">
              스토리 읽기 &rarr;
            </Link>
          </div>
        </section>
        {/* ===================== CTA BAND ===================== */}
        <section style={{ background: "#F05A28", color: "#FAF4E2", marginTop: "84px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              길 위 어디에 있든
            </p>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.18", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              다음 걸음은 언제나 대화 하나만큼 가까이 있습니다.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/ko/workshop" style={{ textDecoration: "none", color: "#F05A28", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                워크숍 찾기
              </Link>
              <Link to="/ko/connect" style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                대화 시작하기
              </Link>
            </div>
          </div>
        </section>
        {/* ===================== FOOTER ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
