import { Fragment } from 'react';
import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/story-index.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/story-index.json';
import wordsko from '../i18n/resources/ko/pages/story-index.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import { localize, useLocale } from '../lib/lang';
import { sx } from '../lib/sx';
import useLogic from '../logic/StoryIndex';
import './StoryIndex.css';

/** Story-Index — one component for every language, generated by
 *  scripts/convert-pages.mjs from Story-Index.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/story-index.json; the
 *  line-heights that differ by language are custom properties in StoryIndex.css.
 *  Edit the legacy pages, not this file. */
export default function StoryIndex() {
  const t = usePageWords("story-index", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();
  const { byFormatStyle, byTopicStyle, current, filterHeading, filters, groups, hasMore, indexHeading, isEmpty, loadMore, loadMoreLabel, onSearch, query, setByFormat, setByTopic, toTop, totalLine } = useLogic();

  return (
    <SiteLayout page="Story-Index.EN.dc.html" className="page-story-index" footer={{ loop: "0.421", cta: "#FAB414" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        <section style={{ background: "#FAB414", color: "#1A1A1A" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 48px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "22px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#1A1A1A" }} />
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", textTransform: "uppercase" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(36px, 5vw, 68px)", lineHeight: "var(--in-story-index-0)", letterSpacing: "-0.02em", margin: "0 0 14px", maxWidth: "16ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4", margin: "0", maxWidth: "60ch", color: "rgba(26,26,26,0.82)" }}>
              {totalLine}
            </p>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "22px 28px 90px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "18px 0 22px" }}>
            <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(26,22,19,0.5)" }}>
              {t("002_span")}
            </span>
            <button onClick={setByFormat} style={sx(byFormatStyle)}>
              {t("003_button")}
            </button>
            <button onClick={setByTopic} style={sx(byTopicStyle)}>
              {t("004_button")}
            </button>
          </div>
          <div className="si-grid" style={{ display: "grid", gridTemplateColumns: "232px 1fr 320px", gap: "30px", alignItems: "start" }}>
            {/* LEFT · filter with counts */}
            <div className="si-left col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderRight: "1px solid rgba(26,22,19,0.14)", paddingRight: "20px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(26,22,19,0.5)", marginBottom: "14px" }}>
                {filterHeading}
              </div>
              <div className="si-railscroll" style={{ display: "flex", flexDirection: "column", gap: "5px" }}>
                {(filters ?? []).map((f, fIndex) => (
                  <Fragment key={fIndex}>
                    <button onClick={f.pick} style={sx(f.style)}>
                      <span>
                        {f.label}
                      </span>
                      <span style={sx(f.countStyle)}>
                        {f.count}
                      </span>
                    </button>
                  </Fragment>
                ))}
              </div>
            </div>
            {/* MIDDLE · the story, read inline */}
            <div className="si-mid">
              <article style={{ maxWidth: "680px" }}>
                <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "14px", margin: "4px 0 20px" }}>
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "9px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#B87A00" }}>
                    <span style={{ width: "10px", height: "10px", borderRadius: "50%", background: "#C9962B" }} />
                    {"Story · "}{current.format}
                  </span>
                  <span style={{ width: "1px", height: "14px", background: "rgba(26,22,19,0.22)" }} />
                  <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.16em", textTransform: "uppercase", color: "rgba(26,22,19,0.5)" }}>
                    {current.topic}
                  </span>
                </div>
                <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(38px, 5.4vw, 66px)", lineHeight: "var(--in-story-index-1)", letterSpacing: "-0.022em", margin: "0 0 22px", textWrap: "balance" }}>
                  {current.title}
                </h2>
                <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontStyle: "var(--in-story-index-2)", fontSize: "clamp(22px, 2.6vw, 28px)", lineHeight: "1.34", letterSpacing: "-0.01em", margin: "0 0 26px", color: "rgba(26,22,19,0.72)", textWrap: "pretty" }}>
                  {current.body}
                </p>
                <div style={{ display: "flex", alignItems: "center", gap: "12px", paddingBottom: "28px", borderBottom: "1.5px solid rgba(26,22,19,0.16)" }}>
                  <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.06em", textTransform: "uppercase", color: "#1A1613" }}>
                    {current.eyebrow}
                  </span>
                  <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "rgba(26,22,19,0.4)" }} />
                  <span style={{ fontFamily: "var(--font-serif)", fontSize: "17px", color: "rgba(26,22,19,0.55)" }}>
                    {current.credit}
                  </span>
                  <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "rgba(26,22,19,0.4)" }} />
                  <span style={{ fontFamily: "var(--font-serif)", fontSize: "17px", color: "rgba(26,22,19,0.55)" }}>
                    {current.dateLabel}
                  </span>
                </div>
                {current.hasImage ? (
                  <>
                  <div role="img" aria-label={current.title} style={sx(current.imgStyle)} />
                  </>
                ) : null}
                <div className="story-body" style={{ paddingTop: "40px" }}>
                  {(current.paras ?? []).map((p, pIndex) => (
                    <Fragment key={pIndex}>
                      <p style={sx(p.style)}>
                        {p.t}
                      </p>
                    </Fragment>
                  ))}
                </div>
                {current.hasKicker ? (
                  <>
                  <div style={{ borderTop: "1.5px solid rgba(201,150,43,0.5)", marginTop: "48px", paddingTop: "34px" }}>
                    <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(26px, 3.4vw, 34px)", lineHeight: "1.24", letterSpacing: "-0.015em", margin: "0 0 10px", color: "#1A1613", textWrap: "balance" }}>
                      {current.kicker1}
                    </p>
                    <p style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(26px, 3.4vw, 34px)", lineHeight: "1.24", letterSpacing: "-0.015em", margin: "0", color: "#B87A00", textWrap: "balance" }}>
                      {current.kicker2}
                    </p>
                  </div>
                  </>
                ) : null}
                {current.isDraft ? (
                  <>
                  <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-story-index-3)", fontSize: "18px", lineHeight: "1.5", margin: "30px 0 0", padding: "16px 20px", background: "#F3EAD0", color: "rgba(26,22,19,0.7)" }}>
                    {t("005_p")}
                  </p>
                  </>
                ) : null}
                <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "14px", borderTop: "1.5px solid rgba(26,22,19,0.16)", marginTop: "52px", paddingTop: "26px" }}>
                  <button type="button" onClick={toTop} style={{ cursor: "pointer", display: "inline-flex", alignItems: "center", gap: "10px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#FAF4E2", background: "#1A1613", border: "none", borderRadius: "999px", padding: "14px 26px" }}>
                    {t("006_button")}
                  </button>
                  <span style={{ fontFamily: "var(--font-serif)", fontSize: "18px", lineHeight: "1.4", color: "rgba(26,22,19,0.6)" }}>
                    {t("007_span")}
                  </span>
                </div>
              </article>
            </div>
            {/* RIGHT · scalable index */}
            <div className="si-right col-scroll" style={{ position: "sticky", top: "78px", maxHeight: "calc(100vh - 100px)", overflowY: "auto", borderLeft: "1px solid rgba(26,22,19,0.14)", paddingLeft: "20px" }}>
              <div style={{ position: "sticky", top: "0", background: "#FAF4E2", paddingBottom: "12px", zIndex: "2" }}>
                <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "10px", marginBottom: "12px" }}>
                  <span style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(26,22,19,0.5)" }}>
                    {indexHeading}
                  </span>
                </div>
                <div style={{ position: "relative" }}>
                  <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="rgba(26,22,19,0.4)" strokeWidth="2" style={{ position: "absolute", left: "12px", top: "50%", transform: "translateY(-50%)" }}>
                    <circle cx="11" cy="11" r="7" />
                    <path d="M21 21l-4-4" strokeLinecap="round" />
                  </svg>
                  <input value={query} onChange={onSearch} placeholder="Search titles…" style={{ width: "100%", fontFamily: "var(--font-serif)", fontSize: "16px", color: "#1A1613", background: "#F3EAD0", border: "1.5px solid rgba(26,22,19,0.14)", borderRadius: "999px", padding: "11px 16px 11px 36px", outline: "none" }} />
                </div>
              </div>
              <div style={{ display: "flex", flexDirection: "column" }}>
                {(groups ?? []).map((g, gIndex) => (
                  <Fragment key={gIndex}>
                    <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11px", letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(26,22,19,0.4)", padding: "18px 2px 8px", borderBottom: "1.5px solid rgba(26,22,19,0.16)" }}>
                      {g.label}
                    </div>
                    {(g.items ?? []).map((s, sIndex) => (
                      <Fragment key={sIndex}>
                        <button onClick={s.open} style={sx(s.style)}>
                          <span style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "10px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#B87A00", marginBottom: "3px" }}>
                            {s.meta}
                          </span>
                          <span style={{ display: "block", fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "17px", lineHeight: "1.16", color: "#1A1613" }}>
                            {s.title}
                          </span>
                        </button>
                      </Fragment>
                    ))}
                  </Fragment>
                ))}
              </div>
              {hasMore ? (
                <>
                <button onClick={loadMore} style={{ width: "100%", marginTop: "16px", cursor: "pointer", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "12px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#1A1613", background: "transparent", border: "1.5px solid rgba(26,22,19,0.3)", borderRadius: "999px", padding: "12px" }}>
                  {loadMoreLabel}{" ↓"}
                </button>
                </>
              ) : null}
              {isEmpty ? (
                <>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "16px", color: "rgba(26,22,19,0.5)", padding: "20px 2px" }}>
                  {t("008_p")}
                </p>
                </>
              ) : null}
            </div>
          </div>
        </section>
        {/* ===================== CTA (matches Story page) ===================== */}
        <section style={{ background: "#FAB414", color: "#2E3B40", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", margin: "0 0 18px" }}>
              {t("009_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 16px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("010_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.5", maxWidth: "640px", margin: "0 auto 28px", color: "rgba(46,59,64,0.82)" }}>
              {t("011_p")}
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/story/submit", locale)} style={{ textDecoration: "none", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("012_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "#2E3B40", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("013_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
