import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import SupabaseForm from '../components/SupabaseForm';
import ChipGroup, { Chip } from '../components/ChipGroup';
import useLogic from '../logic/StorySubmissionKO';
import './StorySubmissionKO.css';

/** Story-Submission.KO.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function StorySubmissionKO() {
  const { onType, typed } = useLogic();

  return (
    <SiteLayout page="Story-Submission.KO.dc.html" className="page-story-submission-ko" footer={{ loop: "0.443", cta: "#FAB414" }}>
      <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (key color · amber) */}
        <section style={{ background: "var(--color-amber)", color: "var(--color-ink)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "24px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-ink)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-ink)" }}>
                스토리 보내기
              </span>
            </div>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(46,59,64,0.85)" }}>
              {"정직한 몇 문장이어도 좋고, 그림, 사진, 영상, 음악이어도 좋습니다. 그 순간에 대한 짧은 설명으로 시작하고 — 그다음에 그것을 가장 잘 담는 형식을 가져오세요. 1단계와 5단계만 필수입니다.\u00a0"}
              <span style={{ fontSize: "clamp(19px, 2.1vw, 25px)" }}>
                <b>
                  당신의 빛을 더해 주어 고맙습니다.
                </b>
              </span>
              <br />
            </p>
          </div>
        </section>
        {/* FORM */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <SupabaseForm table="stories" thanks="고맙습니다 — 잘 받았습니다. 읽은 뒤에 답장을 드리겠습니다." idle="읽은 뒤에 답장을 드리겠습니다. 당신의 작품은 게시되면 별자리에 나타납니다." style={{ maxWidth: "760px", display: "flex", flexDirection: "column", gap: "65px" }}>
            <div aria-hidden="true" style={{ position: "absolute", left: "-9999px", width: "1px", height: "1px", overflow: "hidden" }}>
              <label>
                Leave this field empty
                <input type="text" name="_hp" tabIndex={-1} autoComplete="off" />
              </label>
            </div>
            {/* STEP 1 (required) */}
            <div>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "8px" }}>
                {"1단계 — 당신의 이야기 "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · 필수
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(38px, 5.2vw, 68px)", lineHeight: "1.02", letterSpacing: "-0.02em", margin: "0 0 18px" }}>
                떠오르는 대로 들려주세요.
              </h2>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.5", margin: "0 0 22px", maxWidth: "660px", color: "rgba(46,59,64,0.8)" }}>
                직접 살아낸 일. 눈에 들어온 일. 전해 들은 일. 상상만 할 수 있는 일 — 그것도 포함됩니다.
              </p>
              <textarea className="in-field" name="body" rows={8} required={true} onInput={onType} placeholder="어디서든 시작하세요. 거친 첫 이야기가 바로 맞는 이야기입니다." />
              {typed ? (
                <>
                <div style={{ marginTop: "18px", paddingTop: "16px", borderTop: "1px solid rgba(46,59,64,0.15)" }}>
                  <p id="story-door-q" style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "18px", lineHeight: "1.4", margin: "0 0 12px", color: "rgba(46,59,64,0.7)" }}>
                    좋습니다. 잘 놓아 두기 위해서만 묻습니다 — 이 이야기는 당신이…
                  </p>
                  <ChipGroup name="door" selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" labelledBy="story-door-q" style={{ display: "flex", flexWrap: "wrap", gap: "9px" }}>
                    <Chip value="lived" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      살아낸 일
                    </Chip>
                    <Chip value="noticed" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      알아차린 일
                    </Chip>
                    <Chip value="imagined" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      상상한 일
                    </Chip>
                    <Chip value="were told" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      전해 들은 일
                    </Chip>
                    <Chip value="can't say" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      말하기 어려움
                    </Chip>
                  </ChipGroup>
                </div>
                </>
              ) : null}
              <div style={{ background: "rgba(46,59,64,0.05)", borderLeft: "3px solid #B87A00", padding: "16px 18px", marginTop: "12px" }}>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#B87A00", marginBottom: "14px" }}>
                  어디서 시작할지 모르겠다면 — 네 개의 부드러운 박자
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      1
                    </span>
                    <span style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        그 순간
                      </strong>
                      {" — 어디에 있었고, 언제였나요?"}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      2
                    </span>
                    <span style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        무슨 일이 있었나
                      </strong>
                      {" — 무엇을 했거나, 무엇을 알아차렸나요?"}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      3
                    </span>
                    <span style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        무엇이 움직였나
                      </strong>
                      {" — 당신 안에서, 혹은 사람들 사이에서?"}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      4
                    </span>
                    <span style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        왜
                      </strong>
                      {" — 이것이 당신에게 왜 ME=WE인가요?"}
                    </span>
                  </div>
                </div>
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontStyle: "italic", fontSize: "15px", lineHeight: "1.4", margin: "12px 0 0", color: "rgba(46,59,64,0.6)" }}>
                  정직한 세 문장이면 하나의 이야기입니다. 맞지 않는 박자는 건너뛰세요.
                </p>
              </div>
            </div>
            {/* STEP 2 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"2단계 — 형식 "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · 선택
                </span>
              </div>
              <h2 id="story-format-q" style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                먼저 설명하고, 그다음 형식을 고르세요.
              </h2>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.5", margin: "0 0 18px", color: "rgba(46,59,64,0.8)" }}>
                <b>
                  모든 이야기는 위의 당신의 말에서 시작합니다 — 1단계의 짧은 설명은 언제나 필요합니다.
                </b>
                {" 이야기가 다른 형식으로도 살아 있다면 — 그림, 사진, 영상, 노래 — 무엇인지 알려 주고 아래에 첨부해 주세요. 별자리에서 이 기준으로 묶어 보여 줍니다."}
              </p>
              <ChipGroup name="format" multi selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" labelledBy="story-format-q" style={{ display: "flex", flexWrap: "wrap", gap: "9px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13.5px" }}>
                <Chip value="Writing" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  글
                </Chip>
                <Chip value="Drawing" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  그림
                </Chip>
                <Chip value="Photo" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  사진
                </Chip>
                <Chip value="Video" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  영상
                </Chip>
                <Chip value="Music" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  음악
                </Chip>
                <Chip value="Dance" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  춤
                </Chip>
                <Chip value="Craft" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  손작업
                </Chip>
                <Chip value="Recipe" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  레시피
                </Chip>
                <Chip value="Symbol" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  상징
                </Chip>
                <Chip value="Yours" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  …당신의 것
                </Chip>
              </ChipGroup>
              <div style={{ marginTop: "14px" }}>
                <label className="in-lbl" htmlFor="story-file">
                  작품 첨부 (선택)
                </label>
                <input className="in-field" id="story-file" type="file" name="attachment_url" accept="image/*,video/*,audio/*,.pdf" style={{ padding: "13px 16px", cursor: "pointer" }} />
                <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "15px", lineHeight: "1.4", margin: "8px 0 0", color: "rgba(46,59,64,0.6)" }}>
                  사진, 그림, 스캔, 녹음 또는 PDF
                </p>
              </div>
            </div>
            {/* STEP 3 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"3단계 — ME=WE 아크의 어디쯤 "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · 선택, 건너뛸 수 있음
                </span>
              </div>
              <h2 id="story-arc-q" style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                루프의 어디에 놓이나요?
              </h2>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "17px", lineHeight: "1.45", margin: "0 0 14px", color: "rgba(46,59,64,0.8)" }}>
                루프의 어디에든 놓으세요 — 막힌 자리도 포함해서. 단계 이름을 몰라도 괜찮습니다. 놓는 일은 함께 하겠습니다.
              </p>
              <ChipGroup name="arc_stage" selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" labelledBy="story-arc-q" style={{ display: "flex", flexWrap: "wrap", gap: "9px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px" }}>
                <Chip value="IGNITE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  IGNITE
                </Chip>
                <Chip value="ME ≠ WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  ME ≠ WE
                </Chip>
                <Chip value="ME + WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  ME + WE
                </Chip>
                <Chip value="(ME WE)" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  (ME WE)
                </Chip>
                <Chip value="ME = WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  ME = WE
                </Chip>
                <Chip value="GLOW" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  GLOW
                </Chip>
                <Chip value="Let IN place it" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  IN이 놓아 주세요
                </Chip>
              </ChipGroup>
            </div>
            {/* STEP 4 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"4단계 — 이름 또는 익명 "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · 선택
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                어떻게 표기하면 좋을까요?
              </h2>
              <label className="in-lbl" htmlFor="story-credit">
                어떻게 표기하면 좋을까요?
              </label>
              <input className="in-field" id="story-credit" name="credit_name" type="text" placeholder="이름, 이니셜, 또는 익명으로 남고 싶다면 비워 두세요" />
            </div>
            {/* STEP 5 (required) */}
            <div>
              <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"5단계 — 이메일과 동의 "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · 필수
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                답장을 보낼 곳입니다.
              </h2>
              <label className="in-lbl" htmlFor="story-email">
                이메일
              </label>
              <input className="in-field" id="story-email" name="email" type="email" required={true} placeholder="연락할 수 있도록" />
              <label style={{ display: "flex", alignItems: "flex-start", gap: "10px", marginTop: "14px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "17px", lineHeight: "1.4", color: "rgba(46,59,64,0.8)" }}>
                <input type="checkbox" name="consent" required={true} style={{ marginTop: "5px" }} />
                {" 당신이 더해 주는 모든 것은 함께 만들어 가는 별자리에 나타납니다. 어떤 이야기는 스토리 페이지에도 실립니다. 저는 이 작품이 그곳에 공유될 것을 알고 보냅니다."}
              </label>
            </div>
            <div style={{ background: "rgba(46,59,64,0.05)", padding: "16px 18px" }}>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontStyle: "italic", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.8)" }}>
                길이를 위해 조심스럽게 다듬을 수 있습니다 — 뜻은 결코 바꾸지 않습니다.
              </p>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "center" }}>
              <button type="submit" style={{ textDecoration: "none", color: "var(--color-paper)", background: "var(--color-ink)", border: "none", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px", cursor: "pointer" }}>
                내 이야기 보내기
              </button>
              <span data-in-status="1" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "600", fontSize: "13px", color: "rgba(46,59,64,0.55)" }} />
            </div>
          </SupabaseForm>
        </section>
        {/* CTA (teal · constant) */}
        <section style={{ background: "var(--color-amber)", color: "var(--color-ink)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", margin: "0 0 18px" }}>
              Are You IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              다른 사람들이 나눈 것을 읽어 보세요.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/ko/story" style={{ textDecoration: "none", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                스토리로 돌아가기
              </Link>
              <Link to="/ko/constellation" style={{ textDecoration: "none", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                별자리 보기 →
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
