import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import SupabaseForm from '../components/SupabaseForm';
import ChipGroup, { Chip } from '../components/ChipGroup';
import useLogic from '../logic/StorySubmissionEN';
import './StorySubmissionEN.css';

/** Story-Submission.EN.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function StorySubmissionEN() {
  const { onType, typed } = useLogic();

  return (
    <SiteLayout page="Story-Submission.EN.dc.html" className="page-story-submission-en" footer={{ loop: "0.443", cta: "#FAB414" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (key color · amber) */}
        <section style={{ background: "#FAB414", color: "#2E3B40" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "24px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "#2E3B40", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "#2E3B40" }}>
                Story Submission
              </span>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(46,59,64,0.85)" }}>
              It can be a few honest sentences, or a drawing, a photo, a film, a piece of music. Start with a short description of the moment — then bring whatever form carries it best. Only steps 1 and 5 are required.&nbsp;
              <span style={{ fontSize: "clamp(19px, 2.1vw, 25px)" }}>
                <b>
                  Thank you for adding your light.
                </b>
              </span>
              <br />
            </p>
          </div>
        </section>
        {/* FORM */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <SupabaseForm table="stories" thanks="Thank you for adding your light. We've got your story — you'll get a note back once we've read it." style={{ maxWidth: "760px", display: "flex", flexDirection: "column", gap: "65px" }}>
            <div aria-hidden="true" style={{ position: "absolute", left: "-9999px", width: "1px", height: "1px", overflow: "hidden" }}>
              <label>
                Leave this field empty
                <input type="text" name="_hp" tabIndex={-1} autoComplete="off" />
              </label>
            </div>
            {/* STEP 1 (required) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "8px" }}>
                {"Step 1 — Your story "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · required
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(38px, 5.2vw, 68px)", lineHeight: "1.02", letterSpacing: "-0.02em", margin: "0 0 18px" }}>
                Tell it however it arrives.
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "21px", lineHeight: "1.5", margin: "0 0 22px", maxWidth: "660px", color: "rgba(46,59,64,0.8)" }}>
                Something you lived. Something you noticed. Something someone told you. Something you can only imagine — that counts too.
              </p>
              <textarea className="in-field" name="body" rows={8} required={true} onInput={onType} placeholder="Start anywhere. A rough first telling is exactly right." />
              {typed ? (
                <>
                <div style={{ marginTop: "18px", paddingTop: "16px", borderTop: "1px solid rgba(46,59,64,0.15)" }}>
                  <p style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.4", margin: "0 0 12px", color: "rgba(46,59,64,0.7)" }}>
                    Good. Only so we can place it well — this one is something you…
                  </p>
                  <ChipGroup name="door" selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" style={{ display: "flex", flexWrap: "wrap", gap: "9px" }}>
                    <Chip value="lived" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      lived
                    </Chip>
                    <Chip value="noticed" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      noticed
                    </Chip>
                    <Chip value="imagined" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      imagined
                    </Chip>
                    <Chip value="were told" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      were told
                    </Chip>
                    <Chip value="can't say" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      can't say
                    </Chip>
                  </ChipGroup>
                </div>
                </>
              ) : null}
              <div style={{ background: "rgba(46,59,64,0.05)", borderLeft: "3px solid #B87A00", padding: "16px 18px", marginTop: "12px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#B87A00", marginBottom: "14px" }}>
                  If you're not sure where to start — four gentle beats
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      1
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        The moment
                      </strong>
                      {" — where were you, and when?"}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      2
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        What happened
                      </strong>
                      {" — what you did, or what you noticed?"}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      3
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        What moved
                      </strong>
                      {" — in you, or between people?"}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      4
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        Why
                      </strong>
                      {" — why is this MEWE to you?"}
                    </span>
                  </div>
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontSize: "15px", lineHeight: "1.4", margin: "12px 0 0", color: "rgba(46,59,64,0.6)" }}>
                  Three honest sentences is a story. Skip any beat that doesn't fit.
                </p>
              </div>
            </div>
            {/* STEP 2 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"Step 2 — Format "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · optional
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                Describe it first, then choose a form.
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5", margin: "0 0 18px", color: "rgba(46,59,64,0.8)" }}>
                <b>
                  Every story starts with your words above — a short description in Step 1 is what we always need.
                </b>
                {" If your story also lives in another form — a drawing, a photo, a video, a song — tell us which, and attach it below. This is how we'll group and show it in the Constellation."}
              </p>
              <ChipGroup name="format" multi selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" style={{ display: "flex", flexWrap: "wrap", gap: "9px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13.5px" }}>
                <Chip value="Writing" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Writing
                </Chip>
                <Chip value="Drawing" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Drawing
                </Chip>
                <Chip value="Photo" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Photo
                </Chip>
                <Chip value="Video" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Video
                </Chip>
                <Chip value="Music" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Music
                </Chip>
                <Chip value="Dance" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Dance
                </Chip>
                <Chip value="Craft" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Craft
                </Chip>
                <Chip value="Recipe" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Recipe
                </Chip>
                <Chip value="Symbol" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Symbol
                </Chip>
                <Chip value="Yours" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  …Yours
                </Chip>
              </ChipGroup>
              <div style={{ marginTop: "14px" }}>
                <label className="in-lbl" htmlFor="story-file">
                  Attach your piece (optional)
                </label>
                <input className="in-field" id="story-file" type="file" name="attachment_url" accept="image/*,video/*,audio/*,.pdf" style={{ padding: "13px 16px", cursor: "pointer" }} />
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", lineHeight: "1.4", margin: "8px 0 0", color: "rgba(46,59,64,0.6)" }}>
                  A photo, drawing, scan, video, or audio file — up to 50 MB.
                </p>
              </div>
            </div>
            {/* STEP 3 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"Step 3 — Where on the ME=WE Arc "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · optional, skippable
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                Where does it sit on the Loop?
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.45", margin: "0 0 14px", color: "rgba(46,59,64,0.8)" }}>
                Place your story anywhere on the Loop — including the stuck places. You don't need to name the stage; we'll help place it.
              </p>
              <ChipGroup name="arc_stage" selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" style={{ display: "flex", flexWrap: "wrap", gap: "9px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px" }}>
                <Chip value="IGNITE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  IGNITE
                </Chip>
                <Chip value="ME ≠ WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  ME ≠ WE
                </Chip>
                <Chip value="ME + WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  ME + WE
                </Chip>
                <Chip value="(ME WE)" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  (ME WE)
                </Chip>
                <Chip value="ME = WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  ME = WE
                </Chip>
                <Chip value="GLOW" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  GLOW
                </Chip>
                <Chip value="Let IN place it" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "#2E3B40", background: "transparent" }}>
                  Let IN place it
                </Chip>
              </ChipGroup>
            </div>
            {/* STEP 4 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"Step 4 — Name or anonymous "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · optional
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                How should we credit you?
              </h2>
              <label className="in-lbl" htmlFor="story-credit">
                How should we credit you?
              </label>
              <input className="in-field" id="story-credit" type="text" name="credit_name" placeholder="A name, initials, or leave blank to stay anonymous" />
            </div>
            {/* STEP 5 (required) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {"Step 5 — Email &amp; consent "}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  · required
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                Where we send your note back.
              </h2>
              <label className="in-lbl" htmlFor="story-email">
                Email
              </label>
              <input className="in-field" id="story-email" type="email" name="email" required={true} placeholder="So we can reach you" />
              <label style={{ display: "flex", alignItems: "flex-start", gap: "10px", marginTop: "14px", fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.4", color: "rgba(46,59,64,0.8)" }}>
                <input type="checkbox" name="consent" required={true} style={{ marginTop: "5px" }} />
                {" Everything you add appears in the Constellation we are creating together. Some stories are also chosen for the Story page. I'm offering this piece knowing it will be shared there."}
              </label>
            </div>
            <div style={{ background: "rgba(46,59,64,0.05)", padding: "16px 18px" }}>
              <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.8)" }}>
                We may gently edit for length — never for meaning.
              </p>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "center" }}>
              <button type="submit" style={{ border: "none", cursor: "pointer", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
                Send my story
              </button>
              <span data-in-status="1" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", lineHeight: "1.4", color: "rgba(46,59,64,0.55)" }}>
                You'll get a note back once we've read it. Your piece will appear in the Constellation once published.
              </span>
            </div>
          </SupabaseForm>
        </section>
        {/* CTA (teal · constant) */}
        <section style={{ background: "#FAB414", color: "#2E3B40", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", margin: "0 0 18px" }}>
              Are you IN?
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              Read what others have shared.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/story" style={{ textDecoration: "none", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                Back to Story
              </Link>
              <Link to="/constellation" style={{ textDecoration: "none", color: "#2E3B40", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                See the Constellation →
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
