import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/story-submission.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/story-submission.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import SupabaseForm from '../components/SupabaseForm';
import ChipGroup, { Chip } from '../components/ChipGroup';
import { localize, useLocale } from '../lib/lang';
import useLogic from '../logic/StorySubmissionEN';
import './StorySubmissionEN.css';

/** Story-Submission.EN.dc.html — generated by scripts/convert-pages.mjs. Serves /story/submit and
 *  /zh-tw/story/submit: this page's KO twin did not collapse into it, but
 *  zh-TW has no edition in site/ and reads this one. Its words are in
 *  src/i18n/resources/<locale>/pages/story-submission.json.
 *  Edit the legacy page, or take this file over by hand and remove it from
 *  the converter's input. */
export default function StorySubmissionEN() {
  const t = usePageWords("story-submission", { "en": wordsen, "zh-TW": wordszhTW });
  const locale = useLocale();
  const { onType, typed } = useLogic();

  return (
    <SiteLayout page="Story-Submission.EN.dc.html" className="page-story-submission-en" footer={{ loop: "0.443", cta: "#FAB414" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* HERO (key color · amber) */}
        <section style={{ background: "var(--color-amber)", color: "var(--color-ink)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "24px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-ink)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-ink)" }}>
                {t("000_span")}
              </span>
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "clamp(19px, 2.1vw, 25px)", lineHeight: "1.46", maxWidth: "760px", margin: "0", color: "rgba(46,59,64,0.85)" }}>
              {t("001_p")}
              <span style={{ fontSize: "clamp(19px, 2.1vw, 25px)" }}>
                <strong>
                  {t("002_strong")}
                </strong>
              </span>
              <br />
            </p>
          </div>
        </section>
        {/* FORM */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <SupabaseForm table="stories" thanks={t("003_thanks")} idle={t("004_idle")} style={{ maxWidth: "760px", display: "flex", flexDirection: "column", gap: "65px" }}>
            <div aria-hidden="true" style={{ position: "absolute", left: "-9999px", width: "1px", height: "1px", overflow: "hidden" }}>
              <label>
                {t("005_label")}
                <input type="text" name="_hp" tabIndex={-1} autoComplete="off" />
              </label>
            </div>
            {/* STEP 1 (required) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "8px" }}>
                {t("006_div")}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  {t("007_span")}
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(38px, 5.2vw, 68px)", lineHeight: "1.02", letterSpacing: "-0.02em", margin: "0 0 18px" }}>
                {t("008_h2")}
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "21px", lineHeight: "1.5", margin: "0 0 22px", maxWidth: "660px", color: "rgba(46,59,64,0.8)" }}>
                {t("009_p")}
              </p>
              <textarea className="in-field" name="body" rows={8} required={true} onInput={onType} placeholder={t("010_placeholder")} />
              {typed ? (
                <>
                <div style={{ marginTop: "18px", paddingTop: "16px", borderTop: "1px solid rgba(46,59,64,0.15)" }}>
                  <p id="story-door-q" style={{ fontFamily: "'Newsreader', serif", fontSize: "18px", lineHeight: "1.4", margin: "0 0 12px", color: "rgba(46,59,64,0.7)" }}>
                    {t("011_p")}
                  </p>
                  <ChipGroup name="door" selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" labelledBy="story-door-q" style={{ display: "flex", flexWrap: "wrap", gap: "9px" }}>
                    <Chip value="lived" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      {t("012_span")}
                    </Chip>
                    <Chip value="noticed" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      {t("013_span")}
                    </Chip>
                    <Chip value="imagined" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      {t("014_span")}
                    </Chip>
                    <Chip value="were told" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      {t("015_span")}
                    </Chip>
                    <Chip value="can't say" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", padding: "10px 18px", borderRadius: "999px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", border: "1.5px solid rgba(46,59,64,0.3)", background: "transparent" }}>
                      {t("016_span")}
                    </Chip>
                  </ChipGroup>
                </div>
                </>
              ) : null}
              <div style={{ background: "rgba(46,59,64,0.05)", borderLeft: "3px solid #B87A00", padding: "16px 18px", marginTop: "12px" }}>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "12px", letterSpacing: "0.1em", textTransform: "uppercase", color: "#B87A00", marginBottom: "14px" }}>
                  {t("017_div")}
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      1
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        {t("018_strong")}
                      </strong>
                      {t("019_span")}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      2
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        {t("020_strong")}
                      </strong>
                      {t("021_span")}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      3
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        {t("022_strong")}
                      </strong>
                      {t("023_span")}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "12px", alignItems: "baseline" }}>
                    <span style={{ flex: "0 0 auto", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", color: "#B87A00", width: "18px" }}>
                      4
                    </span>
                    <span style={{ fontFamily: "'Newsreader', serif", fontSize: "20px", lineHeight: "1.45", color: "rgba(46,59,64,0.85)" }}>
                      <strong style={{ fontWeight: "600" }}>
                        {t("024_strong")}
                      </strong>
                      {t("025_span")}
                    </span>
                  </div>
                </div>
                <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontSize: "15px", lineHeight: "1.4", margin: "12px 0 0", color: "rgba(46,59,64,0.6)" }}>
                  {t("026_p")}
                </p>
              </div>
            </div>
            {/* STEP 2 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {t("027_div")}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  {t("028_span")}
                </span>
              </div>
              <h2 id="story-format-q" style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                {t("029_h2")}
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "19px", lineHeight: "1.5", margin: "0 0 18px", color: "rgba(46,59,64,0.8)" }}>
                <strong>
                  {t("030_strong")}
                </strong>
                {t("031_p")}
              </p>
              <ChipGroup name="format" multi selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" labelledBy="story-format-q" style={{ display: "flex", flexWrap: "wrap", gap: "9px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13.5px" }}>
                <Chip value="Writing" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("032_span")}
                </Chip>
                <Chip value="Drawing" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("033_span")}
                </Chip>
                <Chip value="Photo" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("034_span")}
                </Chip>
                <Chip value="Video" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("035_span")}
                </Chip>
                <Chip value="Music" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("036_span")}
                </Chip>
                <Chip value="Dance" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("037_span")}
                </Chip>
                <Chip value="Craft" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("038_span")}
                </Chip>
                <Chip value="Recipe" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("039_span")}
                </Chip>
                <Chip value="Symbol" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("040_span")}
                </Chip>
                <Chip value="Yours" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("041_span")}
                </Chip>
              </ChipGroup>
              <div style={{ marginTop: "14px" }}>
                <label className="in-lbl" htmlFor="story-file">
                  {t("042_label")}
                </label>
                <input className="in-field" id="story-file" type="file" name="attachment_url" accept="image/*,video/*,audio/*,.pdf" style={{ padding: "13px 16px", cursor: "pointer" }} />
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "15px", lineHeight: "1.4", margin: "8px 0 0", color: "rgba(46,59,64,0.6)" }}>
                  {t("043_p")}
                </p>
              </div>
            </div>
            {/* STEP 3 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {t("044_div")}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  {t("045_span")}
                </span>
              </div>
              <h2 id="story-arc-q" style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                {t("046_h2")}
              </h2>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.45", margin: "0 0 14px", color: "rgba(46,59,64,0.8)" }}>
                {t("047_p")}
              </p>
              <ChipGroup name="arc_stage" selBg="#FAB414" selFg="#2E3B40" selBorder="#2E3B40" labelledBy="story-arc-q" style={{ display: "flex", flexWrap: "wrap", gap: "9px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px" }}>
                <Chip value="IGNITE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("048_span")}
                </Chip>
                <Chip value="ME ≠ WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("049_span")}
                </Chip>
                <Chip value="ME + WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("050_span")}
                </Chip>
                <Chip value="(ME WE)" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("051_span")}
                </Chip>
                <Chip value="ME = WE" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("052_span")}
                </Chip>
                <Chip value="GLOW" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("053_span")}
                </Chip>
                <Chip value="Let IN place it" style={{ border: "1.5px solid rgba(46,59,64,0.3)", borderRadius: "999px", padding: "9px 16px", cursor: "pointer", transition: "all .15s", color: "var(--color-ink)", background: "transparent" }}>
                  {t("054_span")}
                </Chip>
              </ChipGroup>
            </div>
            {/* STEP 4 (optional) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {t("055_div")}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  {t("056_span")}
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                {t("057_h2")}
              </h2>
              <label className="in-lbl" htmlFor="story-credit">
                {t("058_label")}
              </label>
              <input className="in-field" id="story-credit" type="text" name="credit_name" placeholder={t("059_placeholder")} />
            </div>
            {/* STEP 5 (required) */}
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#B87A00", marginBottom: "12px" }}>
                {t("060_div")}
                <span style={{ color: "rgba(46,59,64,0.5)" }}>
                  {t("061_span")}
                </span>
              </div>
              <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.05", letterSpacing: "-0.01em", margin: "0 0 14px" }}>
                {t("062_h2")}
              </h2>
              <label className="in-lbl" htmlFor="story-email">
                {t("063_label")}
              </label>
              <input className="in-field" id="story-email" type="email" name="email" required={true} placeholder={t("064_placeholder")} />
              <label style={{ display: "flex", alignItems: "flex-start", gap: "10px", marginTop: "14px", fontFamily: "'Newsreader', serif", fontSize: "17px", lineHeight: "1.4", color: "rgba(46,59,64,0.8)" }}>
                <input type="checkbox" name="consent" required={true} style={{ marginTop: "5px" }} />
                {t("065_label")}
              </label>
            </div>
            <div style={{ background: "rgba(46,59,64,0.05)", padding: "16px 18px" }}>
              <p style={{ fontFamily: "'Newsreader', serif", fontStyle: "italic", fontSize: "18px", lineHeight: "1.45", margin: "0", color: "rgba(46,59,64,0.8)" }}>
                {t("066_p")}
              </p>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "center" }}>
              <button type="submit" style={{ border: "none", cursor: "pointer", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
                {t("067_button")}
              </button>
              <span data-in-status="1" style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "600", fontSize: "13px", lineHeight: "1.4", color: "rgba(46,59,64,0.55)" }} />
            </div>
          </SupabaseForm>
        </section>
        {/* CTA (teal · constant) */}
        <section style={{ background: "var(--color-amber)", color: "var(--color-ink)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.7)", margin: "0 0 18px" }}>
              {t("068_p")}
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("069_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/story", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("070_a")}
              </Link>
              <Link to={localize("/constellation", locale)} style={{ textDecoration: "none", color: "var(--color-ink)", background: "transparent", border: "1.5px solid rgba(46,59,64,0.5)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("071_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
