import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/workshop.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/workshop.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import WorkshopWall from '../components/cards/WorkshopWall';
import { localize, useLocale } from '../lib/lang';
import './WorkshopEN.css';

/** Workshop.EN.dc.html — generated by scripts/convert-pages.mjs. Serves /workshop and
 *  /zh-tw/workshop: this page's KO twin did not collapse into it, but
 *  zh-TW has no edition in site/ and reads this one. Its words are in
 *  src/i18n/resources/<locale>/pages/workshop.json.
 *  Edit the legacy page, or take this file over by hand and remove it from
 *  the converter's input. */
export default function WorkshopEN() {
  const t = usePageWords("workshop", { "en": wordsen, "zh-TW": wordszhTW });
  const locale = useLocale();

  return (
    <SiteLayout page="Workshop.EN.dc.html" className="page-workshop-en" footer={{ loop: "0.171", cta: "#E5188C" }}>
      <div style={{ fontFamily: "'Newsreader', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        {/* ===================== HERO (key color box · magenta) ===================== */}
        <section style={{ background: "var(--color-magenta-hot)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "52px 28px 60px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "22px" }}>
              <span style={{ width: "12px", height: "12px", borderRadius: "50%", background: "var(--color-paper)", flex: "0 0 auto" }} />
              <span style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "17px", letterSpacing: "0.14em", lineHeight: "1", textTransform: "uppercase", color: "var(--color-paper)" }}>
                {t("000_span")}
              </span>
            </div>
            <h1 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(40px, 5.6vw, 80px)", lineHeight: "0.98", letterSpacing: "-0.02em", margin: "0 0 24px", maxWidth: "20ch", textWrap: "balance" }}>
              {t("001_h1")}
            </h1>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(20px, 2.2vw, 28px)", lineHeight: "1.2", maxWidth: "760px", margin: "0", color: "rgba(250,244,226,0.94)", fontStyle: "normal" }}>
              {t("002_p")}
            </p>
          </div>
        </section>
        {/* ===================== FEATURED (Signature — Möbius Making, full-bleed) ===================== */}
        <section style={{ margin: "80px 0 22px" }}>
          <Link to={localize("/workshop/mobius-making", locale)} className="ws-card in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "1.05fr 1fr", alignItems: "stretch", color: "var(--color-paper)", overflow: "hidden", minHeight: "360px", maxWidth: "1320px", margin: "0 auto" }}>
            <div style={{ position: "relative", minHeight: "300px" }}>
              <ImageSlot id="workshop-mobius-hero" src="slot-img/workshop-mobius-hero.webp" shape="rect" placeholder="Someone holding a Möbius strip they made" style={{ position: "absolute", inset: "0", width: "100%", height: "100%", left: "-9px", top: "-1px" }} />
              <div style={{ position: "absolute", left: "16px", top: "16px", background: "var(--color-paper)", color: "var(--color-ink)", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", padding: "6px 12px" }}>
                {t("003_div")}
              </div>
            </div>
            <div style={{ padding: "40px 44px", display: "flex", flexDirection: "column", justifyContent: "space-between", gap: "26px", backgroundColor: "#EEAF05", minHeight: "360px", position: "static" }}>
              <div>
                <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.8)", marginBottom: "16px" }}>
                  {t("004_div")}
                </div>
                <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(34px, 3.6vw, 52px)", lineHeight: "1.0", margin: "0 0 16px", letterSpacing: "-0.01em", textWrap: "balance" }}>
                  {t("005_h2")}
                </h2>
                <p style={{ fontFamily: "'Newsreader', serif", fontSize: "24px", lineHeight: "1.44", margin: "0", color: "rgba(250,244,226,0.92)", maxWidth: "48ch" }}>
                  {t("006_p")}
                </p>
              </div>
              <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "16px" }}>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "8px", fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.03em" }}>
                  <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                    {t("007_span")}
                  </span>
                  <span style={{ background: "rgba(250,244,226,0.18)", borderRadius: "999px", padding: "8px 15px" }}>
                    {t("008_span")}
                  </span>
                </div>
                <span className="ws-arrow" style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-paper)", color: "var(--color-teal)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                  →
                </span>
              </div>
            </div>
          </Link>
        </section>
        {/* ===================== MADE BY MANY HANDS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "20px 28px 12px" }} />
        {/* ===================== MADE BY MANY HANDS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px" }}>
          <div style={{ borderTop: "1px solid rgba(46,59,64,0.14)", paddingTop: "26px" }}>
            <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)", marginBottom: "12px" }}>
              {t("009_div")}
            </div>
            <p style={{ fontFamily: "'Newsreader', serif", fontWeight: "400", fontSize: "38px", lineHeight: "1.5", maxWidth: "760px", margin: "0", color: "rgba(46,59,64,0.78)", width: "900px", height: "500px" }}>
              {t("010_p")}
            </p>
          </div>
        </section>
        {/* ===================== FILTER CHIPS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px 22px" }} />
        {/* ===================== WORKSHOP CARD WALL ===================== */}
        <section style={{ maxWidth: "1320px", margin: "80px auto 0", padding: "0 28px 20px" }}>
          <WorkshopWall />
        </section>
        {/* ===================== HOST A STUDIO ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 20px" }}>
          <Link to={localize("/people", locale)} className="ws-card in-plain" style={{ textDecoration: "none", display: "grid", gridTemplateColumns: "1fr auto", alignItems: "center", gap: "24px", background: "var(--color-paper)", border: "1.5px solid var(--color-ink)", color: "var(--color-ink)", padding: "34px 36px" }}>
            <div>
              <div style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)", marginBottom: "12px" }}>
                {t("011_div")}
              </div>
              <h3 style={{ fontFamily: "'Newsreader', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.04", margin: "0 0 10px", height: "80px" }}>
                {t("012_h3")}
              </h3>
              <p style={{ fontFamily: "'Newsreader', serif", fontSize: "30px", lineHeight: "1.42", margin: "0", color: "var(--color-magenta-hot)", maxWidth: "60ch", fontStyle: "italic", width: "700px", fontWeight: "500" }}>
                {t("013_p")}
              </p>
            </div>
            <span style={{ display: "flex", alignItems: "center", gap: "12px", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "14px", whiteSpace: "nowrap" }}>
              {t("014_span")}
              <span className="ws-arrow" style={{ flex: "0 0 auto", width: "48px", height: "48px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px" }}>
                →
              </span>
            </span>
          </Link>
        </section>
        {/* ===================== CTA BAND ===================== */}
        <section style={{ background: "var(--color-magenta-hot)", color: "var(--color-paper)", marginTop: "80px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("015_p")}
            </p>
            <h2 style={{ fontFamily: "'Newsreader', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("016_h2")}
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/workshop/mobius-making", locale)} style={{ textDecoration: "none", color: "var(--color-teal)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("017_a")}
              </Link>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("018_a")}
              </Link>
            </div>
          </div>
        </section>
        {/* ===================== FOOTER ===================== */}
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
