import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/workshop-bucket-list.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/workshop-bucket-list.json';
import wordsko from '../i18n/resources/ko/pages/workshop-bucket-list.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import WorkshopRegister from '../components/WorkshopRegister';
import { localize, useLocale } from '../lib/lang';
import './WorkshopBucketList.css';

/** Workshop-Bucket-List — one component for every language, generated by
 *  scripts/convert-pages.mjs from Workshop-Bucket-List.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/workshop-bucket-list.json; the
 *  line-heights that differ by language are custom properties in WorkshopBucketList.css.
 *  Edit the legacy pages, not this file. */
export default function WorkshopBucketList() {
  const t = usePageWords("workshop-bucket-list", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Workshop-Bucket-List.EN.dc.html" className="page-workshop-bucket-list" footer={{ loop: "0.63", cta: "#E5188C" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        <span id="top" />
        <section style={{ background: "#E5188C", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "22px 28px 0" }}>
            <Link to={localize("/workshop", locale)} style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "rgba(250,244,226,0.78)", textDecoration: "none" }} className="in-plain">
              {t("000_a")}
            </Link>
          </div>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(250,244,226,0.85)", marginBottom: "20px" }}>
              {t("001_div")}
            </div>
            <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(44px, 6.6vw, 92px)", lineHeight: "var(--in-workshop-bucket-list-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "12ch" }}>
              {t("002_h1")}
            </h1>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(21px, 2.4vw, 30px)", lineHeight: "1.32", maxWidth: "26ch", margin: "0 0 34px", color: "rgba(250,244,226,0.94)" }}>
              {t("003_p")}
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <a href="#register" style={{ textDecoration: "none", color: "#E5188C", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("004_a")}
              </a>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "64px 28px 0" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "baseline", borderTop: "2px solid #2E3B40", paddingTop: "24px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              {t("005_div")}
            </div>
            <div style={{ maxWidth: "760px" }}>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(23px, 2.5vw, 30px)", lineHeight: "1.32", margin: "0 0 22px", letterSpacing: "-0.01em", textWrap: "pretty" }}>
                {t("006_p")}
              </p>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("007_p")}
              </p>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 0" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "24px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              {t("008_div")}
            </div>
            <div style={{ maxWidth: "760px" }}>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(22px, 2.3vw, 28px)", lineHeight: "1.34", margin: "0 0 20px", textWrap: "pretty" }}>
                {t("009_p")}
              </p>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("010_p")}
              </p>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 8px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "start", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "24px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              {t("011_div")}
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "22px 40px", maxWidth: "900px" }}>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  {t("012_div")}
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontSize: "21px", lineHeight: "1.35" }}>
                  {t("013_div")}
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  {t("014_div")}
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontSize: "21px", lineHeight: "1.35" }}>
                  {t("015_div")}
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  {t("016_div")}
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontSize: "21px", lineHeight: "1.35" }}>
                  {t("017_div")}
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  {t("018_div")}
                </div>
                <div style={{ fontFamily: "var(--font-serif)", fontSize: "21px", lineHeight: "1.35" }}>
                  <Link to={localize("/workshop/mobius-making", locale)}>
                    {t("019_a")}
                  </Link>
                  {t("020_div")}
                </div>
              </div>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 0" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "start", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "24px", borderBottom: "2px solid #2E3B40", paddingBottom: "34px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              {t("021_div")}
            </div>
            <div style={{ maxWidth: "900px", display: "flex", flexDirection: "column" }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", padding: "0 0 18px" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  {t("022_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                  {t("023_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  {t("024_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                  {t("025_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  {t("026_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                  {t("027_div")}
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", borderBottom: "1.5px solid rgba(46,59,64,0.25)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  {t("028_div")}
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.4" }}>
                  {t("029_div")}
                </div>
              </div>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 10px" }}>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "16px", alignItems: "flex-start" }}>
            <ImageSlot id="ws-bucket-list-1" shape="rect" placeholder="Bucket List session photo" style={{ display: "block", flex: "0 0 auto", width: "300px", aspectRatio: "16/9" }} />
            <ImageSlot id="ws-bucket-list-2" shape="rect" placeholder="Bucket List session photo" style={{ display: "block", flex: "0 0 auto", width: "300px", aspectRatio: "16/9" }} />
            <div style={{ flex: "1 1 260px", fontFamily: "var(--font-sans)", fontWeight: "600", fontSize: "13px", lineHeight: "1.5", color: "rgba(46,59,64,0.6)", paddingTop: "4px" }}>
              {t("030_div")}
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px" }}>
          <div style={{ background: "#BDDAE7", padding: "44px 44px 40px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40", marginBottom: "16px" }}>
              {t("031_div")}
            </div>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.1", margin: "0 0 18px", maxWidth: "26ch", textWrap: "balance" }}>
              {t("032_h2")}
            </h2>
            <p style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.5", margin: "0 0 14px", maxWidth: "62ch" }}>
              {t("033_p")}
            </p>
            <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-workshop-bucket-list-1)", fontSize: "18px", lineHeight: "1.5", margin: "0", color: "rgba(46,59,64,0.7)" }}>
              {t("034_p")}
            </p>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "0 28px 44px" }}>
          <a href="#top" style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "14px 26px" }} className="in-plain">
            {t("035_a")}
          </a>
        </section>
        <section id="register" style={{ background: "#E5188C", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.7)", margin: "0 0 18px" }}>
              {t("036_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("037_h2")}
            </h2>
            {/* The hero's "Register now" scrolls here. The links below it are a question and the way back, not a sign-up. */}
            <WorkshopRegister slug="bucket-list" accent="#E5188C" />
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "#E5188C", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("038_a")}
              </Link>
              <Link to={localize("/workshop", locale)} style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                {t("039_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
