import { usePageWords } from '../i18n/page-words';
import wordsen from '../i18n/resources/en/pages/workshop-pathfinder.json';
import wordszhTW from '../i18n/resources/zh-TW/pages/workshop-pathfinder.json';
import wordsko from '../i18n/resources/ko/pages/workshop-pathfinder.json';
import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import ImageSlot from '../components/ImageSlot';
import WorkshopRegister from '../components/WorkshopRegister';
import { localize, useLocale } from '../lib/lang';
import './WorkshopPathfinder.css';

/** Workshop-Pathfinder — one component for every language, generated by
 *  scripts/convert-pages.mjs from Workshop-Pathfinder.EN.dc.html and its KO twin. The words live in
 *  src/i18n/resources/<locale>/pages/workshop-pathfinder.json; the
 *  line-heights that differ by language are custom properties in WorkshopPathfinder.css.
 *  Edit the legacy pages, not this file. */
export default function WorkshopPathfinder() {
  const t = usePageWords("workshop-pathfinder", { "en": wordsen, "zh-TW": wordszhTW, "ko": wordsko });
  const locale = useLocale();

  return (
    <SiteLayout page="Workshop-Pathfinder.EN.dc.html" className="page-workshop-pathfinder" footer={{ loop: "0.216", cta: "#E5188C" }}>
      <div style={{ fontFamily: "var(--font-serif)", minHeight: "100vh", overflowX: "hidden" }}>
        <span id="top" />
        {/* ===================== HERO ===================== */}
        <section style={{ background: "var(--color-magenta-hot)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "22px 28px 0" }}>
            <Link to={localize("/workshop", locale)} style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "rgba(250,244,226,0.78)", textDecoration: "none" }} className="in-plain">
              {t("000_a")}
            </Link>
          </div>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px", display: "flex", flexWrap: "wrap", gap: "48px", alignItems: "flex-start" }}>
            <div style={{ flex: "1 1 560px", minWidth: "300px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "26px", lineHeight: "1.1", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.85)", marginBottom: "24px" }}>
                {t("001_div")}
              </div>
              <h1 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(42px, 6vw, 82px)", lineHeight: "var(--in-workshop-pathfinder-0)", letterSpacing: "-0.02em", margin: "0 0 22px", maxWidth: "12ch", textWrap: "balance" }}>
                {t("002_h1")}
              </h1>
              <p style={{ fontFamily: "var(--font-serif)", fontWeight: "400", fontSize: "clamp(20px, 2.3vw, 27px)", lineHeight: "1.45", maxWidth: "660px", margin: "0 0 34px", color: "rgba(250,244,226,0.94)" }}>
                {t("003_p")}
              </p>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginBottom: "36px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13.5px" }}>
                <span style={{ border: "1.5px solid rgba(250,244,226,0.5)", borderRadius: "999px", padding: "9px 16px" }}>
                  {t("004_span")}
                </span>
                <span style={{ border: "1.5px solid rgba(250,244,226,0.5)", borderRadius: "999px", padding: "9px 16px" }}>
                  {t("005_span")}
                </span>
                <span style={{ border: "1.5px solid rgba(250,244,226,0.5)", borderRadius: "999px", padding: "9px 16px" }}>
                  {t("006_span")}
                </span>
                <span style={{ border: "1.5px solid rgba(250,244,226,0.5)", borderRadius: "999px", padding: "9px 16px" }}>
                  {t("007_span")}
                </span>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
                <a href="#register" style={{ textDecoration: "none", color: "var(--color-magenta-hot)", background: "var(--color-paper)", border: "1.5px solid var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                  {t("008_a")}
                </a>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== INVITATION + IMAGE ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "64px 28px 24px" }}>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "52px", alignItems: "flex-start" }}>
            <div style={{ flex: "1 1 460px", minWidth: "300px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)", marginBottom: "18px" }}>
                {t("009_div")}
              </div>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(21px, 2.2vw, 26px)", lineHeight: "1.5", margin: "0 0 20px", letterSpacing: "-0.005em" }}>
                {t("010_p")}
              </p>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0 0 18px", color: "rgba(46,59,64,0.82)" }}>
                {t("011_p")}
              </p>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0 0 18px", color: "rgba(46,59,64,0.82)" }}>
                {t("012_p")}
              </p>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("013_p")}
              </p>
            </div>
            <div style={{ flex: "1 1 380px", minWidth: "280px" }}>
              <ImageSlot id="ws-pathfinder-hero" shape="rect" placeholder="Drop Pathfinder cohort photo" style={{ display: "block", width: "100%", aspectRatio: "4 / 5" }} />
            </div>
          </div>
        </section>
        {/* ===================== DEFINITION ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px 16px" }}>
          <div style={{ borderTop: "1.5px solid rgba(46,59,64,0.2)", borderBottom: "1.5px solid rgba(46,59,64,0.2)", padding: "34px 0", maxWidth: "900px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)", marginBottom: "14px" }}>
              {t("014_div")}
              <span style={{ textTransform: "none", letterSpacing: "0.04em" }}>
                {t("015_span")}
              </span>
            </div>
            <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-workshop-pathfinder-1)", fontSize: "clamp(24px, 3vw, 38px)", lineHeight: "1.2", margin: "0", textWrap: "pretty" }}>
              {t("016_p")}
            </p>
          </div>
        </section>
        {/* ===================== THE ELIXIR ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px 8px" }}>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "52px", alignItems: "flex-start", maxWidth: "1100px" }}>
            <div style={{ flex: "0 1 300px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)", marginBottom: "14px" }}>
                {t("017_div")}
              </div>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(22px, 2.4vw, 30px)", lineHeight: "1.25", margin: "0", color: "var(--color-ink)" }}>
                {t("018_p")}
              </p>
            </div>
            <div style={{ flex: "1 1 420px", minWidth: "300px" }}>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0 0 16px", color: "rgba(46,59,64,0.82)" }}>
                {t("019_p")}
              </p>
              <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                {t("020_p")}
              </p>
            </div>
          </div>
        </section>
        {/* ===================== THE LOOP ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "56px 28px 24px" }}>
          <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(30px, 3.6vw, 46px)", lineHeight: "var(--in-workshop-pathfinder-2)", margin: "0 0 8px", letterSpacing: "-0.01em", textWrap: "balance" }}>
            {t("021_h2")}
          </h2>
          <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", maxWidth: "680px", margin: "0 0 30px", color: "rgba(46,59,64,0.78)" }}>
            {t("022_p")}
          </p>
          <img src="/workshop-img/pathfinder-program-overview.png" alt={t("023_alt")} style={{ display: "block", width: "100%", height: "auto", margin: "0 0 40px" }} />
          <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-workshop-pathfinder-3)", fontSize: "18px", lineHeight: "1.5", margin: "-28px 0 40px", color: "rgba(46,59,64,0.62)" }}>
            {t("024_p")}
          </p>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-teal)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px" }}>
                00
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)" }}>
                {t("025_div")}
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("026_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-teal)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                1
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)" }}>
                {t("027_div")}
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("028_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-teal)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                2
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "17px", letterSpacing: "0.04em", color: "var(--color-teal)" }}>
                {t("029_div")}
                <span style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "10.5px", letterSpacing: "0.16em", color: "rgba(46,59,64,0.55)", marginTop: "3px" }}>
                  {t("030_span")}
                </span>
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("031_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-teal)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                3
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "17px", letterSpacing: "0.04em", color: "var(--color-teal)" }}>
                {t("032_div")}
                <span style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "10.5px", letterSpacing: "0.16em", color: "rgba(46,59,64,0.55)", marginTop: "3px" }}>
                  {t("033_span")}
                </span>
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("034_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-ink)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                4
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "17px", letterSpacing: "0.04em", color: "var(--color-ink)" }}>
                {t("035_div")}
                <span style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "10.5px", letterSpacing: "0.16em", color: "var(--color-magenta-hot)", marginTop: "3px" }}>
                  {t("036_span")}
                </span>
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("037_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-teal)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                5
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "17px", letterSpacing: "0.04em", color: "var(--color-teal)" }}>
                {t("038_div")}
                <span style={{ display: "block", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "10.5px", letterSpacing: "0.16em", color: "rgba(46,59,64,0.55)", marginTop: "3px" }}>
                  {t("039_span")}
                </span>
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("040_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-magenta-hot)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                6
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)" }}>
                {t("041_div")}
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("042_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-amber)", color: "var(--color-ink)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "19px" }}>
                7
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-tan-warm)" }}>
                {t("043_div")}
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("044_div")}
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.18)", borderBottom: "1.5px solid rgba(46,59,64,0.18)", padding: "24px 0" }}>
              <span style={{ flex: "0 0 auto", width: "52px", height: "52px", borderRadius: "50%", background: "var(--color-teal)", color: "var(--color-paper)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px" }}>
                →
              </span>
              <div style={{ flex: "0 0 auto", width: "190px", fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)" }}>
                {t("045_div")}
              </div>
              <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "22px", lineHeight: "1.34" }}>
                {t("046_div")}
                <Link to={localize("/collectives", locale)}>
                  {t("047_a")}
                </Link>
                {t("048_div")}
              </div>
            </div>
          </div>
          <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", maxWidth: "720px", margin: "30px 0 0", color: "rgba(46,59,64,0.82)" }}>
            {t("049_p")}
            <span style={{ color: "var(--color-magenta-hot)" }}>
              {t("050_span")}
            </span>
            {t("051_p")}
          </p>
        </section>
        {/* ===================== THIS IS FOR YOU WHEN ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px" }}>
          <div style={{ background: "var(--color-blush)", padding: "44px 44px 40px" }}>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "var(--in-workshop-pathfinder-4)", margin: "0 0 28px", textWrap: "balance" }}>
              {t("052_h2")}
            </h2>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "18px 40px" }}>
              <div style={{ display: "flex", gap: "14px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "14px" }}>
                <span style={{ flex: "0 0 auto", color: "var(--color-ink)", fontWeight: "800", fontFamily: "var(--font-sans)" }}>
                  →
                </span>
                <span style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.35" }}>
                  {t("053_span")}
                </span>
              </div>
              <div style={{ display: "flex", gap: "14px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "14px" }}>
                <span style={{ flex: "0 0 auto", color: "var(--color-ink)", fontWeight: "800", fontFamily: "var(--font-sans)" }}>
                  →
                </span>
                <span style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.35" }}>
                  {t("054_span")}
                </span>
              </div>
              <div style={{ display: "flex", gap: "14px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "14px" }}>
                <span style={{ flex: "0 0 auto", color: "var(--color-ink)", fontWeight: "800", fontFamily: "var(--font-sans)" }}>
                  →
                </span>
                <span style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.35" }}>
                  {t("055_span")}
                </span>
              </div>
              <div style={{ display: "flex", gap: "14px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "14px" }}>
                <span style={{ flex: "0 0 auto", color: "var(--color-ink)", fontWeight: "800", fontFamily: "var(--font-sans)" }}>
                  →
                </span>
                <span style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.35" }}>
                  {t("056_span")}
                </span>
              </div>
              <div style={{ display: "flex", gap: "14px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "14px" }}>
                <span style={{ flex: "0 0 auto", color: "var(--color-ink)", fontWeight: "800", fontFamily: "var(--font-sans)" }}>
                  →
                </span>
                <span style={{ fontFamily: "var(--font-serif)", fontSize: "20px", lineHeight: "1.35" }}>
                  {t("057_span")}
                </span>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== A PATHFINDER STORY ===================== */}
        <section style={{ background: "var(--color-ink)", color: "var(--color-paper)" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "66px 28px" }}>
            <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-blush)", marginBottom: "22px" }}>
              {t("058_div")}
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "52px", alignItems: "flex-start" }}>
              <div style={{ flex: "1 1 520px", minWidth: "300px" }}>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(22px, 2.4vw, 30px)", lineHeight: "1.35", margin: "0 0 22px", maxWidth: "26ch", color: "var(--color-blush)" }}>
                  {t("059_p")}
                </p>
              </div>
              <div style={{ flex: "1 1 420px", minWidth: "300px" }}>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0 0 16px", color: "rgba(250,244,226,0.88)" }}>
                  {t("060_p")}
                </p>
                <p style={{ fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.55", margin: "0 0 16px", color: "rgba(250,244,226,0.88)" }}>
                  {t("061_p")}
                </p>
                <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-workshop-pathfinder-5)", fontSize: "17px", lineHeight: "1.5", margin: "0", color: "rgba(250,244,226,0.6)" }}>
                  {t("062_p")}
                </p>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== DETAILS ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "56px 28px 40px" }}>
          <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "600", fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: "1.1", margin: "0 0 26px", textWrap: "balance" }}>
            {t("063_h2")}
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1.5px", background: "rgba(46,59,64,0.16)", border: "1.5px solid rgba(46,59,64,0.16)" }}>
            <div style={{ background: "var(--color-paper)", padding: "22px 24px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "8px" }}>
                {t("064_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "22px" }}>
                {t("065_div")}
              </div>
            </div>
            <div style={{ background: "var(--color-paper)", padding: "22px 24px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "8px" }}>
                {t("066_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "22px" }}>
                {t("067_div")}
              </div>
            </div>
            <div style={{ background: "var(--color-paper)", padding: "22px 24px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "8px" }}>
                {t("068_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "22px" }}>
                {t("069_div")}
              </div>
            </div>
            <div style={{ background: "var(--color-paper)", padding: "22px 24px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "8px" }}>
                {t("070_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "22px" }}>
                {t("071_div")}
              </div>
            </div>
            <div style={{ background: "var(--color-paper)", padding: "22px 24px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "8px" }}>
                {t("072_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "22px" }}>
                {t("073_div")}
              </div>
            </div>
            <div style={{ background: "var(--color-paper)", padding: "22px 24px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "8px" }}>
                {t("074_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "22px" }}>
                {t("075_div")}
              </div>
            </div>
          </div>
          <p style={{ fontFamily: "var(--font-serif)", fontStyle: "var(--in-workshop-pathfinder-6)", fontSize: "18px", lineHeight: "1.5", margin: "16px 0 0", color: "rgba(46,59,64,0.62)" }}>
            {t("076_p")}
          </p>
        </section>
        {/* ===================== SIBLING ===================== */}
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "0 28px 40px" }}>
          <Link to={localize("/community/bridge-builders", locale)} style={{ display: "flex", flexWrap: "wrap", gap: "26px", alignItems: "baseline", justifyContent: "space-between", textDecoration: "none", color: "var(--color-ink)", borderTop: "1.5px solid rgba(46,59,64,0.2)", borderBottom: "1.5px solid rgba(46,59,64,0.2)", padding: "26px 0" }} className="in-plain">
            <div style={{ flex: "1 1 420px" }}>
              <div style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-magenta-hot)", marginBottom: "10px" }}>
                {t("077_div")}
              </div>
              <div style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(22px, 2.4vw, 30px)", lineHeight: "1.2" }}>
                {t("078_div")}
              </div>
            </div>
            <div style={{ flex: "1 1 320px", fontFamily: "var(--font-serif)", fontSize: "19px", lineHeight: "1.5", color: "rgba(46,59,64,0.8)" }}>
              {t("079_div")}
              <span style={{ fontFamily: "var(--font-sans)", fontWeight: "800", fontSize: "15px", color: "var(--color-magenta-hot)" }}>
                →
              </span>
            </div>
          </Link>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "0 28px 44px" }}>
          <a href="#top" style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-paper)", background: "var(--color-ink)", borderRadius: "999px", padding: "14px 26px" }} className="in-plain">
            {t("080_a")}
          </a>
        </section>
        {/* ===================== REGISTER CTA ===================== */}
        <section id="register" style={{ background: "var(--color-magenta-hot)", color: "var(--color-paper)", marginTop: "8px" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.75)", margin: "0 0 18px" }}>
              {t("081_p")}
            </p>
            <h2 style={{ fontFamily: "var(--font-serif)", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "var(--in-workshop-pathfinder-7)", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              {t("082_h2")}
            </h2>
            {/* The hero's "Register now" scrolls here. The links below it are a question and the way back, not a sign-up. */}
            <WorkshopRegister slug="pathfinder" accent="#E5188C" />
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "var(--font-sans)", fontWeight: "700", fontSize: "15px" }}>
              <Link to={localize("/connect", locale)} style={{ textDecoration: "none", color: "var(--color-magenta-hot)", background: "var(--color-paper)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("083_a")}
              </Link>
              <Link to={localize("/workshop", locale)} style={{ textDecoration: "none", color: "var(--color-paper)", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: "1.2", minHeight: "24px" }} className="in-plain">
                {t("084_a")}
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
