import { Link } from 'react-router-dom';
import SiteLayout from '../components/SiteLayout';
import './WorkshopShadowShifterKO.css';

/** Workshop-Shadow-Shifter.KO.dc.html — generated by scripts/convert-pages.mjs. Edit the legacy page, or
 *  take this file over by hand and remove it from the converter's input. */
export default function WorkshopShadowShifterKO() {
  return (
    <SiteLayout lang="KO" page="Workshop-Shadow-Shifter.KO.dc.html" className="page-workshop-shadow-shifter-ko" footer={{ loop: "0.41", cta: "#E5188C" }}>
      <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', Georgia, serif", minHeight: "100vh", overflowX: "hidden" }}>
        <span id="top" />
        <section style={{ background: "#E5188C", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "22px 28px 0" }}>
            <Link to="/ko/workshop" style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.08em", textTransform: "uppercase", color: "rgba(250,244,226,0.78)", textDecoration: "none" }} className="in-plain">
              ← 모든 워크숍
            </Link>
          </div>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "30px 28px 56px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(250,244,226,0.85)", marginBottom: "20px" }}>
              청년 · 1박 2일 합숙
            </div>
            <h1 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(46px, 7vw, 96px)", lineHeight: "1.06", letterSpacing: "-0.02em", margin: "0 0 22px" }}>
              섀도 시프터
            </h1>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "clamp(21px, 2.4vw, 30px)", lineHeight: "1.32", maxWidth: "26ch", margin: "0 0 34px", color: "rgba(250,244,226,0.94)" }}>
              우리는 어떻게 자기 삶의 주역이 될 수 있을까?
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <a href="#register" style={{ textDecoration: "none", color: "#E5188C", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                우리 그룹에 열기
              </a>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "64px 28px 0" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "baseline", borderTop: "2px solid #2E3B40", paddingTop: "24px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              무엇인가
            </div>
            <div style={{ maxWidth: "760px" }}>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "clamp(23px, 2.5vw, 30px)", lineHeight: "1.32", margin: "0 0 22px", letterSpacing: "-0.01em", textWrap: "pretty" }}>
                네 단어 위에 세워진 이틀의 합숙: 빛, 그림자, 전환, 역량.
              </p>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                이틀에 걸친 아홉 가지 과제, 모두 직접 손으로 하는 것들 — 그중 일부는 일부러 방에서 가장 어린 사람들에게 공동 진행을 맡깁니다. 퍼실리테이션도 하나의 역량이고, 해 보면서 배우는 것이니까요.
              </p>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 0" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "baseline", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "24px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              왜
            </div>
            <div style={{ maxWidth: "760px" }}>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontStyle: "normal", fontSize: "clamp(22px, 2.4vw, 29px)", lineHeight: "1.34", margin: "0 0 20px", textWrap: "pretty" }}>
                “물체가 빛을 만나면 그림자가 생깁니다. 그리고 우리는 행동으로 자기 그림자의 모양을 바꿀 수 있습니다.”
              </p>
              <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "19px", lineHeight: "1.55", margin: "0", color: "rgba(46,59,64,0.82)" }}>
                그 후에 달라지는 것은 작고 구체적입니다. 한 참가자의 부모는 아이가 자신들의 말을 듣기 시작했음을 알아차렸습니다. 다른 참가자는 실패에 대해, 두려움 없이 봉사를 바라보고 싶다는 마음에 대해 썼습니다. 거의 모두가 다음 회차의 진행을 돕고 싶다고 물었습니다.
              </p>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 8px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "start", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "24px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              누구를 위한
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "22px 40px", maxWidth: "900px" }}>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  참가자
                </div>
                <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.35" }}>
                  대략 18–26세 청년 · 한 그룹 18명 내외
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  기간
                </div>
                <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.35" }}>
                  이틀 합숙 · 아홉 가지 실습 과제
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  설계
                </div>
                <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.35" }}>
                  루아 로, 린 정(비비), 완치 자오 · 김태진 &amp; Vahid Buehrer와 함께
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  첫 진행
                </div>
                <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.35" }}>
                  난즈 센터, 대만 · 2023년 6월
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  공동 진행
                </div>
                <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.35" }}>
                  어린 참가자들이 프로그램의 일부를 이끕니다
                </div>
              </div>
              <div>
                <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "11.5px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(46,59,64,0.55)", marginBottom: "6px" }}>
                  언어
                </div>
                <div style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "21px", lineHeight: "1.35" }}>
                  繁 · EN · 한
                </div>
              </div>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "44px 28px 0" }}>
          <div style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: "40px", alignItems: "start", borderTop: "1.5px solid rgba(46,59,64,0.25)", paddingTop: "24px", borderBottom: "2px solid #2E3B40", paddingBottom: "34px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#E5188C" }}>
              무슨 일이 일어나는가
            </div>
            <div style={{ maxWidth: "900px", display: "flex", flexDirection: "column" }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", padding: "0 0 18px" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  명상 드로잉
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.4" }}>
                  곁의 사람들 안에 있는 빛과 그림자의 결을 알아차리기.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  마음챙김 산책
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.4" }}>
                  아침, 바깥에서, 서두르지 않고 — 어떤 말보다 먼저.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  벽화
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.4" }}>
                  벽에 곧바로, 실물 크기로, 함께 그립니다.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  케이스 클리닉
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.4" }}>
                  한 사람의 진짜 과제를 원 안의 모두가 듣습니다.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  롤 모델
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.4" }}>
                  레고로 지어 봅니다 — 되고자 하는 나를 작고 단단하게.
                </div>
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "24px", alignItems: "baseline", borderTop: "1px solid rgba(46,59,64,0.16)", borderBottom: "1.5px solid rgba(46,59,64,0.25)", padding: "18px 0" }}>
                <div style={{ flex: "0 0 auto", width: "150px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "12.5px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40" }}>
                  편지
                </div>
                <div style={{ flex: "1 1 320px", fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.4" }}>
                  각자 자신에게 편지를 씁니다 — 나중에 열어 볼.
                </div>
              </div>
            </div>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "34px 28px 10px" }}>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "16px", alignItems: "flex-start" }}>
            <figure style={{ margin: "0", flex: "0 0 auto", width: "300px", maxWidth: "100%" }}>
              <img src="/project-img/shadow-shifter.jpg" alt="Participants holding hand-written cards in front of the Shadow Shifter wall" style={{ display: "block", width: "100%", aspectRatio: "16/9", objectFit: "cover" }} />
            </figure>
            <figure style={{ margin: "0", flex: "0 0 auto", width: "300px", maxWidth: "100%" }}>
              <img src="/project-img/shadow-shifter4.jpg" alt="A Shadow Shifter session in progress" style={{ display: "block", width: "100%", aspectRatio: "16/9", objectFit: "cover" }} />
            </figure>
            <figcaption style={{ flex: "1 1 260px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "600", fontSize: "13px", lineHeight: "1.5", color: "rgba(46,59,64,0.6)", paddingTop: "4px" }}>
              {"난즈 센터, 2023년 6월. "}
              <Link to="/project/shadow-shifter">
                프로젝트 전체 보기 →
              </Link>
            </figcaption>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "40px 28px" }}>
          <div style={{ background: "#BDDAE7", padding: "44px 44px 40px" }}>
            <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "800", fontSize: "13px", letterSpacing: "0.16em", textTransform: "uppercase", color: "#2E3B40", marginBottom: "16px" }}>
              형식
            </div>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "600", fontSize: "clamp(26px, 3vw, 38px)", lineHeight: "1.1", margin: "0 0 18px", maxWidth: "24ch", textWrap: "balance" }}>
              아홉 가지 과제, 함께 고릅니다.
            </h2>
            <p style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontSize: "20px", lineHeight: "1.5", margin: "0", maxWidth: "62ch" }}>
              틀은 그대로입니다 — 빛, 그림자, 전환, 역량 — 활동과 기간, 그리고 여러분의 청년들이 얼마나 공동 진행할지는 사전에 함께 정합니다. 첫 기수의 평가는 이틀로는 부족하다는 것이었습니다. 더 긴 버전도 가능합니다.
            </p>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "8px 28px 40px" }}>
          <div style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#E5188C", marginBottom: "16px" }}>
            하나의 패턴, 여러 형태
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13.5px" }}>
            <Link to="/ko/workshop/jungle-jam" style={{ textDecoration: "none", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.35)", borderRadius: "999px", padding: "11px 20px" }} className="in-plain">
              정글 잼 — UAE 청년
            </Link>
            <Link to="/ko/workshop/light-shadow-shift" style={{ textDecoration: "none", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.35)", borderRadius: "999px", padding: "11px 20px" }} className="in-plain">
              빛, 그림자, 전환 — 여성 리트릿
            </Link>
            <Link to="/ko/workshop/mobius-making" style={{ textDecoration: "none", color: "#2E3B40", border: "1.5px solid rgba(46,59,64,0.35)", borderRadius: "999px", padding: "11px 20px" }} className="in-plain">
              뫼비우스 만들기 — 여기서 시작
            </Link>
          </div>
        </section>
        <section style={{ maxWidth: "1320px", margin: "0 auto", padding: "0 28px 44px" }}>
          <a href="#top" style={{ display: "inline-flex", alignItems: "center", gap: "10px", textDecoration: "none", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "#FAF4E2", background: "#2E3B40", borderRadius: "999px", padding: "14px 26px" }} className="in-plain">
            &uarr; 맨 위로
          </a>
        </section>
        <section id="register" style={{ background: "#E5188C", color: "#FAF4E2" }}>
          <div style={{ maxWidth: "1320px", margin: "0 auto", padding: "70px 28px", textAlign: "center" }}>
            <p style={{ fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "13px", letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(250,244,226,0.7)", margin: "0 0 18px" }}>
              함께하기
            </p>
            <h2 style={{ fontFamily: "'Newsreader', 'Noto Serif KR', serif", fontWeight: "500", fontSize: "clamp(32px, 4.6vw, 58px)", lineHeight: "1.06", margin: "0 0 28px", letterSpacing: "-0.01em", textWrap: "balance" }}>
              청년들이 직접 이끌게 하세요.
            </h2>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", fontFamily: "'Archivo', 'Noto Sans KR', sans-serif", fontWeight: "700", fontSize: "15px" }}>
              <Link to="/ko/connect" style={{ textDecoration: "none", color: "#E5188C", background: "#FAF4E2", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                대화 시작하기
              </Link>
              <Link to="/ko/workshop" style={{ textDecoration: "none", color: "#FAF4E2", background: "transparent", border: "1.5px solid rgba(250,244,226,0.7)", borderRadius: "999px", padding: "15px 32px", display: "inline-flex", alignItems: "center", lineHeight: "1.2" }} className="in-plain">
                모든 워크숍
              </Link>
            </div>
          </div>
        </section>
        <div id="connect" />
      </div>
    </SiteLayout>
  );
}
