// Generated by scripts/extract-detail-pages.mjs — do not edit by hand.
// The copy behind src/pages/templates/CommunityDetail.tsx, read out of the
// legacy pages in site/. Edit the legacy page and re-run the script.

import type { BriefFact, DetailLink } from './detail-types';
export type { BriefFact, DetailLink } from './detail-types';

/**
 * What a community's page says that its `communities` row does not carry.
 *
 * The row holds what the card walls need — title, blurb, accent, route. This
 * holds what only the full page shows. Both are keyed by slug.
 */
export interface CommunityDetail {
  slug: string;
  /** Design-token name for the hero band — `gold`, `red`. */
  accent: string;
  /** Token name for the hero's text: `ink` on a light band, `paper` on a dark one. */
  ink: string;
  /** The status pill: 'Continued', 'On hold'. At most one. */
  chips: string[];
  title: string;
  lede: string;
  /** The heading over the fact cards — 'The brief', 'What formed'. */
  briefLabel: string;
  brief: BriefFact[];
  link: DetailLink | null;
  /** Where the footer ribbon sits on this page, 0–1. */
  loop: string | null;
  /** Design-token name for the closing band. */
  ctaAccent: string | null;
}

export const COMMUNITY_DETAILS: Record<string, CommunityDetail> = {
  "animators": {
    "slug": "animators",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Continued"
    ],
    "title": "Animators",
    "lede": "Peer animators who carry MEWE sessions in their own neighborhoods — the practice, hosted locally.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "Trained peer facilitators of lightweight sessions."
      },
      {
        "label": "Status",
        "body": "Continued — active and growing."
      },
      {
        "label": "Outcomes",
        "body": "Regular neighborhood sessions and new animators."
      }
    ],
    "link": null,
    "loop": "0.784",
    "ctaAccent": "red"
  },
  "bridge-builders": {
    "slug": "bridge-builders",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Continued"
    ],
    "title": "BridgeBuilders",
    "lede": "BridgeBuilders across five cities, connecting what's divided — called by the program, at work in Asia Exchange.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "People who answered the BridgeBuilder call."
      },
      {
        "label": "Status",
        "body": "Continued — active across cities."
      },
      {
        "label": "At work",
        "body": "Collaborating through Asia Exchange."
      }
    ],
    "link": {
      "label": "See the BridgeBuilder Program →",
      "to": "/project/bridge-builder-program"
    },
    "loop": "0.852",
    "ctaAccent": "red"
  },
  "facilitators": {
    "slug": "facilitators",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Continued"
    ],
    "title": "Facilitators",
    "lede": "Pathfinder-trained facilitators who hold the MEWE workshop for others.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "Graduates of the Pathfinder training."
      },
      {
        "label": "Status",
        "body": "Continued — an active practicing community."
      },
      {
        "label": "Become one",
        "body": "The path runs through Pathfinder, on the Protagonist page."
      }
    ],
    "link": {
      "label": "See the Protagonist paths →",
      "to": "/protagonist"
    },
    "loop": "0.829",
    "ctaAccent": "red"
  },
  "in-collectives": {
    "slug": "in-collectives",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Continued"
    ],
    "title": "IN-Collectives",
    "lede": "Independent partners hosting studios in their own communities worldwide — not branches, partners.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "Practitioners who host and adapt IN studios."
      },
      {
        "label": "Status",
        "body": "Continued — the living network."
      },
      {
        "label": "Become one",
        "body": "The path runs through the Collectives page."
      }
    ],
    "link": {
      "label": "Meet the Collectives →",
      "to": "/collectives"
    },
    "loop": "0.806",
    "ctaAccent": "red"
  },
  "nepal-youth-cluster": {
    "slug": "nepal-youth-cluster",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Harvested"
    ],
    "title": "Nepal Youth Cluster",
    "lede": "Nepali youth from UAE Nepal Connect who kept practicing together after the exchange ended.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "Participants from the UNC exchange."
      },
      {
        "label": "Status",
        "body": "Harvested — a completed, documented cycle."
      },
      {
        "label": "Outcomes",
        "body": "Local initiatives and lasting cross-border ties."
      }
    ],
    "link": {
      "label": "From the UNC project →",
      "to": "/project/unc"
    },
    "loop": "0.761",
    "ctaAccent": "red"
  },
  "open-studio": {
    "slug": "open-studio",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Continued"
    ],
    "title": "Open Studio",
    "lede": "An open, drop-in MEWE space — no prerequisite, just a room where the practice is always available.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "Anyone who walks in — newcomers and regulars."
      },
      {
        "label": "Status",
        "body": "Continued — open on a recurring basis."
      },
      {
        "label": "Outcomes",
        "body": "A steady on-ramp into the wider practice."
      }
    ],
    "link": null,
    "loop": "0.875",
    "ctaAccent": "red"
  },
  "uae-youth-cluster": {
    "slug": "uae-youth-cluster",
    "accent": "red",
    "ink": "paper",
    "chips": [
      "Harvested"
    ],
    "title": "UAE Youth Cluster",
    "lede": "The young people who ran real ventures in Sharjah — many still practice as changemakers today.",
    "briefLabel": "What formed",
    "brief": [
      {
        "label": "Who formed",
        "body": "Cohort members from UAE Youth Social Innovation."
      },
      {
        "label": "Status",
        "body": "Harvested — the cycle completed, learning gathered."
      },
      {
        "label": "Outcomes",
        "body": "Alumni ventures, further workshops, documented learning."
      }
    ],
    "link": {
      "label": "From the UAE Youth project →",
      "to": "/project/uae-youth-social-innovation"
    },
    "loop": "0.738",
    "ctaAccent": "red"
  }
};
