/**
 * Writes app/.env.devdb from the local stack's own report.
 *
 *   cd app && npm run db:env
 *
 * `npm run dev` is `vite --mode devdb`, so the keys it uses come from
 * .env.devdb. Those keys belong to the Supabase running on this machine, and the
 * one authority on them is `supabase status` — not a value pasted into a doc,
 * which goes stale the first time the CLI changes what it hands out.
 *
 * **The file it writes is committed, deliberately.** Every value in it addresses
 * 127.0.0.1 and is signed with the local JWT secret the CLI publishes in its own
 * documentation, so it is the same on every machine and grants nothing anywhere
 * else. Committing it is what makes a fresh checkout's `npm run dev` work with
 * no credential handed over — the same reason database.types.ts is committed.
 * app/.env.local, which holds the hosted project's real keys, stays gitignored.
 *
 * Like db:types, this refuses to write unless the CLI exits clean and returns
 * something that parses. A stopped stack should cost you one line saying to
 * start it, not an .env.devdb with three empty values in it — which would look
 * exactly like a project with no keys and quietly serve bundled content.
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = join(HERE, '..');

const OUT = join(APP, '.env.devdb');
const ARGS = ['status', '-o', 'env'];

/**
 * The CLI as installed by the `supabase` devDependency — resolved from this
 * file rather than PATH, and shell-spawned on win32 where the shim is a .cmd
 * Node will not exec directly. Same reasoning as scripts/db-types.mjs, which
 * carries the long version of it.
 */
const isWindows = process.platform === 'win32';
const bin = join(APP, 'node_modules', '.bin', isWindows ? 'supabase.cmd' : 'supabase');

const run = spawnSync(isWindows ? `"${bin}"` : bin, ARGS, {
  cwd: APP,
  encoding: 'utf8',
  shell: isWindows,
});

if (run.error) {
  console.error(`!! Could not run the Supabase CLI at ${relative(APP, bin)}`);
  console.error(`   ${run.error.message}`);
  console.error('   Is it installed?  cd app && npm install');
  process.exit(1);
}

const stdout = run.stdout ?? '';
const stderr = run.stderr ?? '';

/** `NAME="value"` per line, which is the whole of `-o env`. */
function parse(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const match = /^([A-Z0-9_]+)="(.*)"$/.exec(line.trim());
    if (match) out[match[1]] = match[2];
  }
  return out;
}

const status = parse(stdout);

/**
 * The three the app needs, and what each becomes.
 *
 * The legacy JWT pair rather than PUBLISHABLE_KEY / SECRET_KEY on purpose: those
 * two are minted per stack, and a per-machine value cannot be committed. ANON_KEY
 * and SERVICE_ROLE_KEY are signed with the CLI's fixed local secret, so they are
 * identical everywhere and the file stays shareable. Both formats work as the
 * second argument to createClient.
 */
const WANT = [
  ['API_URL', 'VITE_SUPABASE_URL'],
  ['ANON_KEY', 'VITE_SUPABASE_ANON_KEY'],
  ['SERVICE_ROLE_KEY', 'SUPABASE_SERVICE_ROLE_KEY'],
];

const missing = WANT.filter(([from]) => !status[from]).map(([from]) => from);

if (run.status !== 0 || missing.length) {
  if (missing.length && run.status === 0) {
    console.error(`!! supabase ${ARGS.join(' ')} returned no ${missing.join(', ')}`);
  } else {
    console.error(`!! supabase ${ARGS.join(' ')} exited ${run.status}`);
  }

  const raw = (stderr.trim() || stdout.trim()).split('\n').slice(0, 8);
  if (raw[0]) console.error(raw.join('\n').replace(/^/gm, '   '));

  if (/not running|no such container|is the container|Docker/i.test(`${stderr} ${stdout}`)) {
    console.error('\n   The local stack is not up:  npx supabase start --workdir app');
    console.error('   (Docker Desktop has to be running first.)');
  }

  process.exit(run.status || 1);
}

const body = [
  '# The LOCAL Supabase stack. Generated by `npm run db:env` — do not hand-edit.',
  '#',
  '# Read only by `npm run dev` (which is `vite --mode devdb`) and, by default, by',
  '# `npm run signin-link`. The hosted project lives in .env.local instead, and is',
  '# reached by `npm run dev:live`, `npm run build` and `npm run preview`.',
  '#',
  '# Committed on purpose: every value here addresses 127.0.0.1 and is signed with',
  "# the CLI's published local JWT secret, so it is the same on every machine and",
  '# grants nothing anywhere else. They only work while the stack is up.',
  '#',
  '# Regenerate after a CLI upgrade changes what it hands out:  npm run db:env',
  '',
  ...WANT.map(([from, to]) => `${to}=${status[from]}`),
  '',
].join('\n');

let before = null;
try {
  before = readFileSync(OUT, 'utf8');
} catch {
  // First run.
}

if (before === body) {
  console.log('.env.devdb — unchanged.');
  process.exit(0);
}

writeFileSync(OUT, body);
console.log(`.env.devdb — ${before === null ? 'created' : 'updated'}.`);
console.log(`  VITE_SUPABASE_URL=${status.API_URL}`);
console.log(`  Studio: ${status.STUDIO_URL ?? 'http://127.0.0.1:54323'}   Mail: ${status.MAILPIT_URL ?? status.INBUCKET_URL ?? 'http://127.0.0.1:54324'}`);
