/**
 * Turns site/data/stories.js into typed content and seed SQL.
 *
 *   node scripts/extract-stories.mjs
 *
 * That file calls itself the single source of truth for every story on the
 * site, and it is — but it reaches the page as two globals assigned by a
 * script tag, which means nothing can typecheck it and only a browser can read
 * it. Evaluated here in a sandbox, it becomes:
 *
 *   src/lib/content/stories.ts   typed records + taxonomy, bundled
 *   ../seed-stories.sql          the same rows for the story_entries table
 *
 * Both languages stay on one record, as they are in the source: a story is one
 * thing told twice, not two stories.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(HERE, '..', '..', 'site', 'data', 'stories.js');
const OUT = join(HERE, '..', 'src', 'lib', 'content', 'stories.ts');
const SEED = join(HERE, '..', '..', 'seed-stories.sql');

// The file assigns onto `window`; give it one and nothing else.
const sandbox = {};
new Function('window', readFileSync(SOURCE, 'utf8'))(sandbox);

const taxonomy = sandbox.IN_TAXONOMY;
const stories = sandbox.IN_STORIES;

if (!taxonomy || !stories) {
  throw new Error('stories.js did not assign IN_TAXONOMY / IN_STORIES — has its shape changed?');
}

/** Image paths are page-relative in the source and root-absolute in the app. */
function resolve(path) {
  if (!path) return null;
  return /^(https?:|data:|\/)/i.test(path) ? path : '/' + path.replace(/^\.\//, '');
}

const records = stories
  .map((story) => ({
    id: story.id,
    date: story.date,
    format: story.format,
    topic: story.topic,
    color: story.color ?? null,
    href: story.href && story.href !== '#' ? story.href : null,
    draft: Boolean(story.draft),
    image: resolve(story.media?.image ?? null),
    imageFit: story.media?.fit ?? null,
    imageRatio: story.media?.ratio ?? null,
    imagePosition: story.media?.pos ?? null,
    en: story.en,
    ko: story.ko,
  }))
  .sort((a, b) => b.date.localeCompare(a.date));

writeFileSync(
  OUT,
  `// Generated by scripts/extract-stories.mjs from site/data/stories.js.
// Do not edit by hand — edit the source, or the story_entries table.

/** One story's copy in one language. */
export interface StoryCopy {
  eyebrow: string;
  title: string;
  /** The card blurb. */
  body: string;
  credit: string;
  /** Full text, one string per paragraph. Both languages carry the same count. */
  paras: string[];
  kicker?: string[];
}

export interface StoryEntry {
  /** Stable slug — this is the permalink, so it never changes. */
  id: string;
  /** ISO date; drives ordering and the month grouping on the index. */
  date: string;
  /** Key into TAXONOMY.format. */
  format: string;
  /** Key into TAXONOMY.topic. */
  topic: string;
  /** Plate colour behind the card when there is no photo. */
  color: string | null;
  /** Destination page, or null when the story reads inline on the index. */
  href: string | null;
  /** Still being written. */
  draft: boolean;
  image: string | null;
  imageFit: string | null;
  imageRatio: string | null;
  imagePosition: string | null;
  en: StoryCopy;
  ko: StoryCopy;
}

/** Format and topic keys → their label in each language. */
export const TAXONOMY: {
  format: Record<string, { en: string; ko: string }>;
  topic: Record<string, { en: string; ko: string }>;
} = ${JSON.stringify(taxonomy, null, 2)};

export const STORY_ENTRIES: StoryEntry[] = ${JSON.stringify(records, null, 2)};
`,
);

/* ------------------------------------------------------------------- seed */

const q = (v) => (v === null || v === undefined || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const json = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

writeFileSync(
  SEED,
  `-- IN Website — story entries seed
-- Generated by app/scripts/extract-stories.mjs from site/data/stories.js.
-- Run the story_entries section of schema.sql first.

insert into public.story_entries
  (id, published_on, format, topic, color, href, draft, image, image_fit, image_ratio, image_position, en, ko)
values
${records
  .map(
    (s) =>
      `  (${q(s.id)}, ${q(s.date)}, ${q(s.format)}, ${q(s.topic)}, ${q(s.color)}, ${q(s.href)}, ${s.draft}, ` +
      `${q(s.image)}, ${q(s.imageFit)}, ${q(s.imageRatio)}, ${q(s.imagePosition)}, ${json(s.en)}, ${json(s.ko)})`,
  )
  .join(',\n')}
on conflict (id) do update set
  published_on = excluded.published_on, format = excluded.format, topic = excluded.topic,
  color = excluded.color, href = excluded.href, draft = excluded.draft,
  image = excluded.image, image_fit = excluded.image_fit, image_ratio = excluded.image_ratio,
  image_position = excluded.image_position, en = excluded.en, ko = excluded.ko;
`,
);

/* ---------------------------------------------------------- constellation */

/**
 * The Constellation's points live in that page's own script — twenty of them,
 * a superset of the story collection with a contributor, a caption and up to
 * three ways to follow it (read / watch / view).
 *
 * The array is plain object literals, so it evaluates in the same sandbox
 * trick rather than being regexed apart.
 */
const constellationSource = readFileSync(
  join(HERE, '..', '..', 'site', 'Constellation.EN.dc.html'),
  'utf8',
);

const block = /data\(\)\s*\{\s*return \[([\s\S]*?)\n    \];/.exec(constellationSource);
const points = block
  ? new Function(`return [${block[1]}\n]`)().map((p) => ({
      id: p.id,
      title: p.title,
      by: p.by ?? null,
      format: p.format,
      topic: p.topic,
      arc: p.arc ?? null,
      /** yyyy-mm — the points are placed by month, not by day. */
      month: p.date,
      caption: p.caption ?? null,
      read: p.read ? toRoute(p.read) : null,
      media: p.media ?? null,
      view: p.view ? (/^https?:/.test(p.view) ? p.view : '/' + p.view.replace(/^\//, '')) : null,
    }))
  : [];

/** `Story-Index.EN.dc.html?story=x` → `/story/all?story=x`. */
function toRoute(href) {
  if (/^https?:/i.test(href)) return href;
  const [file, search] = href.split('?');
  if (file === 'Story-Index.EN.dc.html') return `/story/all${search ? '?' + search : ''}`;
  if (file === 'Story-Index.KO.dc.html') return `/ko/story/all${search ? '?' + search : ''}`;
  return href;
}

writeFileSync(
  join(HERE, '..', 'src', 'lib', 'content', 'constellation.ts'),
  `// Generated by scripts/extract-stories.mjs from site/Constellation.EN.dc.html.
// Do not edit by hand — edit the constellation_points table.

/** One light in the Constellation. */
export interface ConstellationPoint {
  id: string;
  title: string;
  /** Who it came from — often 'Anonymous', which is the point. */
  by: string | null;
  /** Key into the colour scale, and one of the two grouping modes. */
  format: string;
  topic: string;
  /** Where it sits on the MEWE loop, when it has been placed. */
  arc: string | null;
  /** yyyy-mm — points are placed by month, not by day. */
  month: string;
  caption: string | null;
  /**
   * Korean copy, absent until someone writes it — see \`inLang\`. The bundled
   * rows never carry it: they are extracted from the English page, and the
   * translation belongs in the table.
   *
   * \`topicKo\` is a label only. \`topic\` stays the grouping key, so the sky
   * clusters the same way in both languages.
   */
  titleKo?: string | null;
  byKo?: string | null;
  captionKo?: string | null;
  topicKo?: string | null;
  titleZhTw?: string | null;
  byZhTw?: string | null;
  captionZhTw?: string | null;
  topicZhTw?: string | null;
  /** Up to three ways to follow it. */
  read: string | null;
  media: string | null;
  view: string | null;
}

/** The colour each format glows. */
export const FORMAT_COLORS: Record<string, string> = {
  writing: '#F0D23C',
  drawing: '#E6328C',
  photo: '#35C0B4',
  video: '#FF5A5A',
  music: '#9B7BE0',
  dance: '#F5A81E',
  craft: '#6FCB7C',
  recipe: '#C9962B',
  symbol: '#7BC4F0',
  other: '#FAF4E2',
};

export const CONSTELLATION: ConstellationPoint[] = ${JSON.stringify(points, null, 2)};
`,
);

writeFileSync(
  join(HERE, '..', '..', 'seed-constellation.sql'),
  `-- IN Website — constellation points seed
-- Generated by app/scripts/extract-stories.mjs from site/Constellation.EN.dc.html.

insert into public.constellation_points
  (id, title, by_line, format, topic, arc, month, caption, read_href, media_href, view_href)
values
${points
  .map(
    (p) =>
      `  (${q(p.id)}, ${q(p.title)}, ${q(p.by)}, ${q(p.format)}, ${q(p.topic)}, ${q(p.arc)}, ` +
      `${q(p.month)}, ${q(p.caption)}, ${q(p.read)}, ${q(p.media)}, ${q(p.view)})`,
  )
  .join(',\n')}
on conflict (id) do update set
  title = excluded.title, by_line = excluded.by_line, format = excluded.format,
  topic = excluded.topic, arc = excluded.arc, month = excluded.month,
  caption = excluded.caption, read_href = excluded.read_href,
  media_href = excluded.media_href, view_href = excluded.view_href;
`,
);

console.log(`points:   ${points.length}`);
console.log(`stories:  ${records.length}`);
console.log(`formats:  ${Object.keys(taxonomy.format).length}`);
console.log(`topics:   ${Object.keys(taxonomy.topic).length}`);
