/**
 * Concatenates the schema and every seed into one paste-ready file.
 *
 *   node scripts/supabase-setup.mjs
 *
 * Setting the database up meant opening five files in order and pasting each
 * one, which is four chances to skip a step and one to get the order wrong —
 * the seeds fail on a table that does not exist yet, and the failure looks like
 * a broken seed rather than a missed schema.
 *
 * So: one file, in order, with a header saying what it will do. Generated rather
 * than maintained, because a hand-assembled bundle is a sixth copy of the same
 * SQL and would drift from the five the moment an extractor re-ran.
 *
 * The parts stay the source of truth. This only ever reads them.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');

/**
 * In dependency order: the schema, then the seeds that need it.
 *
 * `seed-staff.sql` is the one optional part. It is gitignored — who has admin
 * access is per-deployment and does not belong in the repository — so a
 * checkout without it is normal, and the bundle simply comes out without an
 * allowlist. That means nobody can sign in to /review, which is the honest
 * result of not having said who may.
 */
const PARTS = [
  ['schema.sql', 'tables, RLS policies, the storage bucket, and realtime'],
  ['seed.sql', 'news, workshops, projects, communities'],
  ['seed-collectives.sql', 'the IN-Collective roster'],
  ['seed-constellation.sql', 'the Constellation points'],
  ['seed-stories.sql', 'the curated story collection'],
  ['seed-staff.sql', 'the staff allowlist for /review', { optional: true }],
];

const OUT = 'supabase-setup.sql';

/**
 * Counts the rows each `insert into public.x` will write.
 *
 * Every seed is generated by an extractor with one value tuple per line, opening
 * at two spaces and a paren, so counting those lines is exact for these files
 * rather than a guess. Counting starts *after* the `values` keyword, because the
 * column list is indented and parenthesised exactly like a row and would
 * otherwise add one to every table.
 */
function rowsPerTable(sql) {
  const counts = [];
  const blocks = sql.split(/^insert into public\./m);

  for (const block of blocks.slice(1)) {
    const table = /^(\w+)/.exec(block)?.[1];
    if (!table) continue;

    const values = block.split(/^values$/m)[1];
    if (!values) continue;

    const rows = (values.match(/^ {2}\(/gm) ?? []).length;
    if (rows) counts.push([table, rows]);
  }
  return counts;
}

const loaded = PARTS.map(([file, what, options]) => {
  let sql;
  try {
    sql = readFileSync(join(ROOT, file), 'utf8');
  } catch {
    if (options?.optional) return null;
    console.error(`!! ${file} is missing. Run the extractors first:`);
    console.error('   node scripts/extract-content.mjs && node scripts/extract-stories.mjs && node scripts/extract-page-data.mjs');
    process.exit(1);
  }
  return { file, what, sql: sql.trimEnd(), rows: rowsPerTable(sql) };
}).filter(Boolean);

const inserts = loaded.flatMap((part) => part.rows);
const total = inserts.reduce((sum, [, rows]) => sum + rows, 0);
const width = Math.max(...loaded.map((part) => part.file.length));

const header = [
  '-- IN Website — one-shot Supabase setup',
  '--',
  '-- Generated by app/scripts/supabase-setup.mjs. Do not edit by hand — edit the',
  '-- part it came from, or the extractor that writes that part, and re-run:',
  '--',
  '--   cd app && node scripts/supabase-setup.mjs',
  '--',
  '-- Paste the whole file into Supabase → SQL Editor → Run. Safe to re-run as',
  '-- often as you like: every table is created `if not exists`, every column is',
  '-- added `if not exists`, and every insert is an upsert on the primary key, so',
  '-- this is both the first-time setup and the way to push content changes.',
  '--',
  '-- In order:',
  '--',
  ...loaded.map((part, i) => `--   ${i + 1}. ${part.file.padEnd(width)}  ${part.what}`),
  '--',
  `-- Inserts ${total} rows across ${inserts.length} tables:`,
  '--',
  ...inserts.map(([table, rows]) => `--   ${String(rows).padStart(4)}  ${table}`),
  '--',
  '-- Afterwards the site reads live rows and keeps reading them as you edit: every',
  '-- page stays subscribed to the tables it uses. See CONTENT.md.',
  '',
].join('\n');

const body = loaded
  .map((part, i) =>
    [
      '',
      '-- ' + '='.repeat(74),
      `-- ${i + 1}/${loaded.length} · ${part.file} — ${part.what}`,
      '-- ' + '='.repeat(74),
      '',
      part.sql,
      '',
    ].join('\n'),
  )
  .join('\n');

const out = `${header}${body}`;
writeFileSync(join(ROOT, OUT), out);

// Bytes, not characters: the SQL is full of em-dashes and Korean, so a
// character count understates the paste by a fifth.
const kb = (Buffer.byteLength(out, 'utf8') / 1024).toFixed(0);
console.log(`${OUT} — ${kb} kB, ${loaded.length} parts, ${total} rows across ${inserts.length} tables.`);
for (const [table, rows] of inserts) console.log(`  ${String(rows).padStart(4)}  ${table}`);
